const ACCESS_API_URL = `${(window.LK_API_BASE || '').replace(/\/$/, '')}/api/login`;
const accessKey = 'lk-internal-access-until';
const accessUntil = Number(localStorage.getItem(accessKey));
const accessLanguage = localStorage.getItem('lk-language') || 'ja';
document.documentElement.lang = accessLanguage;
const accessText = accessLanguage === 'en' ? {
  eyebrow:'INTERNAL ACCESS', title:'Little Kings Internal Usage Only', protected:'This website is protected by password login. Please do not share the password with others.', consent:'Apart from your own data, do not share any data without consent.', share:'Do not share this website or its password with anyone outside the Little Kings Family. The password is changed regularly and circulated internally to the Little Kings Family.', missing:'If you do not have the password, please check with the Little Kings Family.', duration:'After signing in, this browser will stay unlocked for seven days.', welcome:'Welcome to Little Kings', intro:'Little Kings is a table tennis club based in Kanagawa, Japan, primarily for elementary and junior-high school students. We welcome new members, visits, free trial sessions, and enquiries at any time.', principle:'The Sottaku Principle', principleText:'Members from Grade 1 through Grade 12 train here. Beginners and players with no previous experience receive careful instruction from the fundamentals.', growth:'We value individual talent, growth, cooperation, and independence through table tennis. We aim to be a club where members grow brightly, happily, and energetically while learning manners, respect for opponents, and respect for the rules.', close:'Why not take on the challenge with Little Kings?', contact:'CONTACT', phone:'Phone', email:'Email', password:'Password', enter:'Enter', checking:'Checking...', error:'Incorrect password or verification failed.'
} : {
  eyebrow:'内部アクセス', title:'リトルキングス 内部利用限定', protected:'このウェブサイトはパスワードで保護されています。パスワードを他の人と共有しないでください。', consent:'ご自身のデータ以外は、本人の同意なく共有しないでください。', share:'このウェブサイトとパスワードは、リトルキングスファミリー以外の方へ共有しないでください。パスワードは定期的に変更され、リトルキングスファミリー内でご案内します。', missing:'パスワードをお持ちでない場合は、リトルキングスファミリーにご確認ください。', duration:'一度ログインすると、このブラウザでは7日間アクセスできます。', welcome:'リトルキングスへようこそ', intro:'神奈川県を拠点に活動する、小学生・中学生を中心とした卓球クラブチームです。新規会員を募集しており、見学・無料体験・お問い合わせは随時受け付けています。', principle:'「啐啄」の理念', principleText:'小学1年生から高校3年生までが所属し、未経験の方や初心者の方にも基礎から丁寧に指導します。', growth:'卓球を通して個々の才能を伸ばし、成長・協調性・自立心を大切にしています。楽しさと上達を両立しながら、礼儀やマナー、相手への敬意、ルールを守る大切さを学びます。「明るく、楽しく、元気よく」成長できるクラブを目指しています。', close:'リトルキングスで一緒に頑張ってみませんか！', contact:'お問い合わせ', phone:'電話', email:'メール', password:'パスワード', enter:'入室する', checking:'確認中…', error:'パスワードが正しくないか、確認できませんでした。'
};

const isAdminPage = /(?:^|\/)admin\.html$/i.test(location.pathname);
if (!isAdminPage && accessUntil <= Date.now()) {
  localStorage.removeItem(accessKey);
  document.body.insertAdjacentHTML('afterbegin', `<section id="site-password-gate" class="site-password-gate" aria-labelledby="password-gate-title"><form id="site-password-form"><button id="gate-language-toggle" class="language-toggle" type="button">${accessLanguage === 'en' ? '日本語' : 'ENGLISH'}</button><img src="little-kings-logo.jpg" alt="Little Kings" /><p class="eyebrow">${accessText.eyebrow}</p><h1 id="password-gate-title">${accessText.title}</h1><p>${accessText.protected}</p><p>${accessText.consent}</p><p>${accessText.share}</p><p>${accessText.missing}</p><p class="access-duration">${accessText.duration}</p><section class="access-club-intro"><p class="eyebrow">KANAGAWA · JAPAN</p><h2>${accessText.welcome}</h2><p>${accessText.intro}</p><h3>${accessText.principle}</h3><p>${accessText.growth}</p><p class="access-club-close">${accessText.close}</p><aside><b>${accessText.contact}</b><span>${accessText.phone} <a href="tel:09015555060">090-1555-5060</a></span><span>${accessText.email} <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram @ritokin.ryumon</a></aside></section><label>${accessText.password}<input id="site-password" type="password" autocomplete="current-password" required /></label><button class="gold-button" type="submit">${accessText.enter}</button><p id="site-password-status" role="status"></p></form></section>`);
  document.querySelector('#gate-language-toggle').onclick = () => { localStorage.setItem('lk-language', accessLanguage === 'en' ? 'ja' : 'en'); location.reload(); }; const passwordForm = document.querySelector('#site-password-form');
  passwordForm.addEventListener('submit', async event => { event.preventDefault(); const passwordStatus = document.querySelector('#site-password-status'); passwordStatus.textContent = accessText.checking; try { const response = await fetch(ACCESS_API_URL, { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ role:'site', password:document.querySelector('#site-password').value }) }), result = await response.json(); if (!response.ok || !result.ok) throw new Error(); localStorage.setItem('lk-site-session', result.token); localStorage.setItem(accessKey, String(Date.now() + 7 * 24 * 60 * 60 * 1000)); document.querySelector('#site-password-gate').remove(); } catch { passwordStatus.textContent = accessText.error; } });
}
const environment = /\/uat(?:\/|$)/i.test(location.pathname) ? 'UAT' : 'PROD';
document.body.insertAdjacentHTML('beforeend', `<aside class="environment-badge ${environment.toLowerCase()}" aria-label="Environment: ${environment}">${environment}</aside>`);
const nav = document.querySelector('nav');
if (nav) nav.insertAdjacentHTML('beforeend', `<a href="tournament.html" id="nav-tournaments">${accessLanguage === 'en' ? 'Tournaments' : '大会'}</a><a href="admin.html" id="nav-maintenance" style="color:#8c423a;border-bottom:2px solid #8c423a;padding-bottom:0">${accessLanguage === 'en' ? 'Data Maintenance' : 'データメンテナンス'}</a>`);
