const ACCESS_API_URL = 'https://script.google.com/macros/s/AKfycbx6IaN9YT2a4bv_8W76qtNwkFCjZ_-mODBEMTK9IiJlSi91UCIgJ56MQ4WJqeKK3TiUvA/exec';
const accessKey = 'lk-internal-access-until';
const accessUntil = Number(localStorage.getItem(accessKey));

if (accessUntil <= Date.now()) {
  localStorage.removeItem(accessKey);
  document.body.insertAdjacentHTML('afterbegin', `<section id="site-password-gate" class="site-password-gate" aria-labelledby="password-gate-title"><form id="site-password-form"><img src="little-kings-logo.jpg" alt="Little Kings" /><p class="eyebrow">INTERNAL ACCESS</p><h1 id="password-gate-title">リトルキングス 内部利用限定<br /><em>Little Kings Internal Usage Only</em></h1><p>このウェブサイトはパスワードで保護されています。パスワードを他の人と共有しないでください。<br />This website is protected by password login. Please do not share the password with others.</p><p>ご自身のデータ以外は、本人の同意なく共有しないでください。<br />Apart from your own data, do not share any data without consent.</p><p class="access-duration">一度ログインすると、このブラウザでは7日間アクセスできます。<br />After signing in, this browser will stay unlocked for seven days.</p><section class="access-club-intro"><p class="eyebrow">KANAGAWA · JAPAN</p><h2>リトルキングスへようこそ</h2><p>神奈川県を拠点に活動する、小学生・中学生を中心とした卓球クラブチームです。新規会員を募集しており、見学・無料体験・お問い合わせは随時受け付けています。</p><h3>「啐啄」の理念</h3><p>小学1年生から高校3年生までが所属し、未経験の方や初心者の方にも基礎から丁寧に指導します。卓球を通して個々の才能を伸ばし、成長・協調性・自立心を大切にしています。</p><p>楽しさと上達を両立しながら、礼儀やマナー、相手への敬意、ルールを守る大切さを学びます。「明るく、楽しく、元気よく」成長できるクラブを目指しています。</p><p class="access-club-close">リトルキングスで一緒に頑張ってみませんか！</p><aside><b>お問い合わせ</b><span>電話 <a href="tel:09015555060">090-1555-5060</a></span><span>メール <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram @ritokin.ryumon</a></aside></section><label>パスワード / Password<input id="site-password" type="password" autocomplete="current-password" required /></label><button class="gold-button" type="submit">入室する / Enter</button><p id="site-password-status" role="status"></p></form></section>`);
  document.querySelector('.access-duration').insertAdjacentHTML('beforebegin', '<p>このウェブサイトとパスワードは、リトルキングスファミリー以外の方へ共有しないでください。パスワードは定期的に変更され、リトルキングスファミリー内でご案内します。<br />Do not share this website or its password with anyone outside the Little Kings Family. The password is changed regularly and circulated internally to the Little Kings Family.</p><p>パスワードをお持ちでない場合は、リトルキングスファミリーにご確認ください。<br />If you do not have the password, please check with the Little Kings Family.</p>');
  const passwordForm = document.querySelector('#site-password-form');
  passwordForm.addEventListener('submit', async event => { event.preventDefault(); const passwordStatus = document.querySelector('#site-password-status'); passwordStatus.textContent = '確認中… / Checking…'; try { const body = new URLSearchParams({ action:'verifySitePassword', password:document.querySelector('#site-password').value }), response = await fetch(ACCESS_API_URL, { method:'POST', body }), result = await response.json(); if (!result.authorized) throw new Error(); localStorage.setItem(accessKey, String(Date.now() + 7 * 24 * 60 * 60 * 1000)); document.querySelector('#site-password-gate').remove(); } catch { passwordStatus.textContent = 'パスワードが正しくないか、確認できませんでした。 / Incorrect password or verification failed.'; } });
}
