const DATA_URL = 'https://script.google.com/macros/s/AKfycbx6IaN9YT2a4bv_8W76qtNwkFCjZ_-mODBEMTK9IiJlSi91UCIgJ56MQ4WJqeKK3TiUvA/exec?action=publicData';
let data = { players: [], matches: [] };
let language = localStorage.getItem('lk-language') || 'en';
const copy = { en: { navPlayers:'Players',navMatches:'Matches',navStats:'Statistics',eyebrow:'OFFICIAL CLUB DATABASE',heroDescription:'Every point. Every player. One club.',viewResults:'View match results',matchesPlayed:'Matches played',activePlayers:'Active players',latestResult:'Latest result',winsLeader:'Wins leader',sectionStatsKicker:'THE NUMBERS',sectionStats:'Club Statistics',rankingTitle:'Win Rankings',minimumMatches:'Min. 3 matches',sectionMatchesKicker:'LIVE ARCHIVE',sectionMatches:'Latest Results',sectionPlayersKicker:'THE SQUAD',sectionPlayers:'Players',loading:'Loading live data...',updating:'Live data',lastUpdated:'Last updated' }, ja: { navPlayers:'選手',navMatches:'試合結果',navStats:'スタッツ',eyebrow:'公式クラブデータベース',heroDescription:'すべてのポイント。すべての選手。ひとつのクラブ。',viewResults:'試合結果を見る',matchesPlayed:'試合数',activePlayers:'登録選手',latestResult:'最新試合日',winsLeader:'最多勝',sectionStatsKicker:'数字で見る',sectionStats:'クラブスタッツ',rankingTitle:'勝利ランキング',minimumMatches:'最低3試合',sectionMatchesKicker:'試合アーカイブ',sectionMatches:'最新結果',sectionPlayersKicker:'選手紹介',sectionPlayers:'選手',loading:'データを読み込んでいます...',updating:'ライブデータ',lastUpdated:'最終更新' } };
function nameFor(player) { return language === 'en' && player.englishName ? player.englishName : player.displayName; }
function playerMap() { return new Map(data.players.map(p => [p.playerId, p])); }
function stats() { const map = new Map(data.players.map(p => [p.playerId,{ wins:0,losses:0,setsFor:0,setsAgainst:0 }])); data.matches.forEach(m => { if (map.has(m.player1Id)) { const x=map.get(m.player1Id); x.setsFor+=m.player1Sets;x.setsAgainst+=m.player2Sets;m.winnerId===m.player1Id?x.wins++:x.losses++; } if(map.has(m.player2Id)){const x=map.get(m.player2Id);x.setsFor+=m.player2Sets;x.setsAgainst+=m.player1Sets;m.winnerId===m.player2Id?x.wins++:x.losses++;} }); return map; }
function render() { document.documentElement.lang=language; document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=copy[language][el.dataset.i18n]); document.getElementById('language-toggle').textContent=language==='en'?'日本語':'ENGLISH'; document.getElementById('player-search').placeholder=language==='en'?'Search players':'選手を検索'; const playerStats=stats(), players=playerMap(); const ranked=data.players.map(p=>({p,s:playerStats.get(p.playerId)})).sort((a,b)=>b.s.wins-a.s.wins||b.s.setsFor-a.s.setsFor); document.getElementById('match-count').textContent=data.matches.length; document.getElementById('player-count').textContent=data.players.length; const dates=data.matches.map(m=>m.matchDate).filter(Boolean).sort(); document.getElementById('latest-date').textContent=dates.at(-1)||'-'; document.getElementById('win-leader').textContent=ranked[0]?nameFor(ranked[0].p):'-'; document.getElementById('leaderboard').innerHTML=ranked.filter(x=>x.s.wins+x.s.losses>=3).slice(0,8).map((x,i)=>{const total=x.s.wins+x.s.losses;return `<div class="leader-row"><span class="rank">${String(i+1).padStart(2,'0')}</span><strong class="leader-name">${nameFor(x.p)}</strong><span class="record">${x.s.wins}W · ${x.s.losses}L</span><span class="percentage">${Math.round(x.s.wins/total*100)}%</span></div>`}).join('') || '<div class="loading">-</div>'; document.getElementById('match-list').innerHTML=[...data.matches].sort((a,b)=>b.matchDate.localeCompare(a.matchDate)).slice(0,16).map(m=>{const a=players.get(m.player1Id)||{displayName:m.player1Name},b=players.get(m.player2Id)||{displayName:m.player2Name};return `<article class="match-card"><div class="match-meta"><span>${m.matchDate}</span><span>${m.division||m.event||'Little Kings'}</span></div><div class="match-score"><span class="match-player ${m.winnerId===m.player1Id?'winner':''}">${nameFor(a)}</span><strong class="score">${m.player1Sets} - ${m.player2Sets}</strong><span class="match-player ${m.winnerId===m.player2Id?'winner':''}">${nameFor(b)}</span></div></article>`}).join(''); renderPlayers(ranked,playerStats); document.getElementById('last-updated').textContent=`${copy[language].lastUpdated}: ${new Date(data.lastUpdated).toLocaleString(language==='ja'?'ja-JP':'en-GB')}`; }
function renderPlayers(ranked,statsMap) { const search=document.getElementById('player-search').value.toLowerCase(); document.getElementById('player-grid').innerHTML=ranked.filter(({p})=>nameFor(p).toLowerCase().includes(search)).map(({p})=>{const s=statsMap.get(p.playerId),games=s.wins+s.losses;return `<article class="player-card"><span class="player-id">${p.playerId}</span><h3 class="player-name">${nameFor(p)}</h3><div class="player-detail">${[p.playingHand,p.playingStyle].filter(Boolean).join(' · ')||'LITTLE KINGS'}</div><div class="player-record">${s.wins}W - ${s.losses}L <small>${games?Math.round(s.wins/games*100):0}%</small></div></article>`}).join(''); }
document.getElementById('language-toggle').addEventListener('click',()=>{language=language==='en'?'ja':'en';localStorage.setItem('lk-language',language);render();}); document.getElementById('player-search').addEventListener('input',()=>renderPlayers(data.players.map(p=>({p,s:stats().get(p.playerId)})).sort((a,b)=>b.s.wins-a.s.wins),stats()));
fetch(DATA_URL).then(r=>r.json()).then(result=>{if(!result.ok)throw new Error('Feed unavailable');data=result;render();document.getElementById('data-status').textContent=copy[language].updating;}).catch(()=>{document.querySelectorAll('.loading').forEach(el=>el.textContent='Unable to load live data.');});
