Chart.defaults.layout.padding = { top: 18, right: 8, bottom: 0, left: 0 };
Chart.register({ id: 'valueLabels', afterDatasetsDraw(chart) { const { ctx } = chart, isWinRate = chart.canvas.id === 'wins-chart'; if (chart.canvas.id === 'session-timeline-chart' && window.matchMedia('(max-width: 760px)').matches) return; ctx.save(); ctx.fillStyle = isWinRate ? '#090a0b' : '#f6f0e2'; ctx.font = '700 11px Barlow Condensed'; ctx.textAlign = 'center'; chart.data.datasets.forEach((dataset, datasetIndex) => chart.getDatasetMeta(datasetIndex).data.forEach((element, index) => { const value = dataset.data[index]; if (value === null || value === undefined) return; const point = element.tooltipPosition(), isBar = chart.getDatasetMeta(datasetIndex).type === 'bar', horizontalBar = isBar && chart.options.indexAxis === 'y', label = isWinRate ? `${value}%` : Math.abs(value); ctx.fillText(label, horizontalBar ? (element.x + element.base) / 2 : point.x, isBar ? (horizontalBar ? point.y + 4 : (element.y + element.base) / 2 + 4) : point.y - 8); })); ctx.restore(); } });
let data = { players: [], matches: [] }, selectedMonth = 'all', selectedYear = 'all', selectedSession = '', selectedSessionMatchup = '', sessionMatchupsExpanded = false, calendarMonth = '', recentStart = 0, leaderboardYearIndex = 0, leaderboardView = 'month', categoryLeaderboardEntries = new Map(), categoryLeaderboardYear = '', categoryLeaderboardMatches = [], monthlyCategoryEntries = new Map(), monthlyCategoryMatches = new Map(), charts = [];
let language = localStorage.getItem('lk-language') || 'ja';
const words = {
  en: { navPlayers:'Players',navMatches:'Matches',navStats:'Rankings',navSessions:'Sessions',navSurvey:'Player Profile Supplement',eyebrow:'CLUB TRAINING MATCH GAME LOG',heroDescription:'Every point. Every player. One club.',viewResults:'View match results',matchesPlayed:'Matches played',activePlayers:'Active players',latestResult:'Latest result',winsLeader:'Wins leader',sectionStatsKicker:'THE NUMBERS',sectionStats:'Club Training Statistics',rankingTitle:'Win Rankings',minimumMatches:'Min. 3 matches',sectionMatchesKicker:'CLUB TRAINING GAME LOG',sectionMatches:'Training Match Results',sectionPlayersKicker:'THE SQUAD',sectionPlayers:'Players',sessionKicker:'TRAINING LOG',sessionTitle:'Session Replay',allResults:'All results',training:'Training',tournament:'Tournament',incomplete:'Incomplete',trainingYear:'Training year',trainingMonth:'Training month',winsChart:'Win Rate Leaders',formatChart:'Score Breakdown',groupKicker:'SQUAD BREAKDOWN',groupTitle:'Group Statistics',categoryStats:'Player Category',genderStats:'Gender',threeMonthKicker:'RECENT FORM',threeMonthTitle:'Monthly Leaderboard',monthLeader:'Month leader',yearLeader:'Year leader',gamesPlayed:'games played',participated:'participated',unassigned:'Unassigned',loading:'Loading live data...',updating:'Live data',lastUpdated:'Last updated',officialSite:'Official club website',matches:'matches',players:'players',noSessions:'No training sessions found',quickAccess:'QUICK ACCESS',bookmarkSite:'Bookmark this site',findPlayer:'Find a player',playerSearch:'Name or player ID',home:'Little Kings home',mainNavigation:'Main navigation',switchLanguage:'Switch language',openDatabase:'Open Little Kings match database',databaseQr:'QR code for tinyurl.com/ritokinryumon',previousYear:'Previous year',nextYear:'Next year',helpYearly:'How to read the yearly leaderboard',helpPlayers:'How to read player profiles',loadError:'Unable to load live data.',leaderboardKicker:'RANKINGS',leaderboardTitle:'Leaderboard',monthTab:'This Month',yearTab:'This Year',latestSessionKicker:'LATEST SESSION',latestSessionTitle:'Latest Session',viewFullSession:'View full session',viewAllRankings:'View all rankings',clubOverviewKicker:'CLUB OVERVIEW',clubOverviewTitle:'Club Statistics',completedMatches:'completed',incompleteMatches:'incomplete',playersParticipated:'players participated',noCompletedMatches:'No completed matches yet' },
  ja: { navPlayers:'選手',navMatches:'試合結果',navStats:'ランキング',navSessions:'練習日',navSurvey:'選手プロフィール補足情報',eyebrow:'クラブ練習試合ゲームログ',heroDescription:'すべてのポイント。すべての選手。ひとつのクラブ。',viewResults:'試合結果を見る',matchesPlayed:'試合数',activePlayers:'登録選手',latestResult:'最新試合日',winsLeader:'最多勝',sectionStatsKicker:'数字で見る',sectionStats:'クラブ練習スタッツ',rankingTitle:'勝利ランキング',minimumMatches:'最低3試合',sectionMatchesKicker:'クラブ練習ゲームログ',sectionMatches:'練習試合結果',sectionPlayersKicker:'選手紹介',sectionPlayers:'選手',sessionKicker:'練習ログ',sessionTitle:'練習日リプレイ',allResults:'すべて',training:'クラブ練習',tournament:'大会',incomplete:'未完了',trainingYear:'練習年',trainingMonth:'練習月',winsChart:'勝率ランキング',formatChart:'スコア内訳',groupKicker:'グループ別',groupTitle:'グループスタッツ',categoryStats:'区分別',genderStats:'性別',threeMonthKicker:'直近の成績',threeMonthTitle:'月間リーダーボード',monthLeader:'月間リーダー',yearLeader:'年間リーダー',gamesPlayed:'試合',participated:'参加',unassigned:'未設定',loading:'データを読み込んでいます...',updating:'ライブデータ',lastUpdated:'最終更新',officialSite:'公式クラブサイト',matches:'試合',players:'選手',noSessions:'練習記録がありません',quickAccess:'クイックアクセス',bookmarkSite:'このサイトをブックマーク',findPlayer:'選手を探す',playerSearch:'名前または選手ID',home:'リトルキングス ホーム',mainNavigation:'メインナビゲーション',switchLanguage:'言語を切り替える',openDatabase:'リトルキングス試合データベースを開く',databaseQr:'tinyurl.com/ritokinryumon のQRコード',previousYear:'前年',nextYear:'翌年',helpYearly:'年間リーダーボードの見方',helpPlayers:'選手プロフィールの見方',loadError:'ライブデータを読み込めませんでした。',leaderboardKicker:'ランキング',leaderboardTitle:'リーダーボード',monthTab:'今月',yearTab:'今年',latestSessionKicker:'最新の練習日',latestSessionTitle:'最新セッション',viewFullSession:'セッション全体を見る',viewAllRankings:'全順位を見る',clubOverviewKicker:'クラブ概要',clubOverviewTitle:'クラブ統計',completedMatches:'完了',incompleteMatches:'未完了',playersParticipated:'人が参加',noCompletedMatches:'完了した試合はまだありません' }
};
const t = key => words[language][key];
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[character]);
document.addEventListener('error', event => { const image = event.target, portrait = image instanceof HTMLImageElement && image.closest('.player-portrait, .match-portrait, .profile-portrait, .yearly-avatar, .monthly-avatar, .hero-player-portrait, .active-player-portrait, .h2h-portraits figure'); if (!portrait || !/^(?:img\/)?[^/]+\.jpg$/.test(image.getAttribute('src') || '')) return; event.stopImmediatePropagation(); if (image.dataset.fallback) { if (portrait.classList.contains('yearly-avatar')) portrait.nextElementSibling?.classList.add('yearly-avatar-missing'); portrait.remove(); } else { image.dataset.fallback = 'true'; image.src = 'img/NoProfilePic.jpg'; } }, true);
document.addEventListener('mouseover', event => { const dot = event.target.closest('.game-result-dot'); if (!dot) return; const card = dot.closest('.match-card'); if (card) dot.title = card.innerText.replace(/\s+/g, ' ').trim(); });
const nameFor = player => language === 'en' && player.englishName ? `${player.displayName} | ${player.englishName.toUpperCase()}` : player.displayName;
const recordText = (wins, losses, games = wins + losses) => language === 'en' ? `${wins}W-${losses}L · ${games}G` : `${wins}勝-${losses}負 · ${games}試合`;
const dateLabel = date => `${date} · ${new Date(`${date}T00:00:00`).toLocaleDateString(language === 'en' ? 'en-US' : 'ja-JP',{weekday:'short'}).toUpperCase()}`;
const rubberName = id => { if (!id) return ''; if (!window.RUBBERS) return id; const r = window.RUBBERS.find(x => x.rubberId === id); return r ? r.name : id; };
const lookupValue = (field, value) => {
  if (!value) return value;
  const table = ({ gender:'genders', schoolLevel:'schoolLevels', playingHand:'playingHands', grip:'grips', playingStyle:'playingStyles', forehandRubberType:'rubberTypes', backhandRubberType:'rubberTypes' })[field];
  const item = table && (window.LK_STATIC?.[table] || []).find(entry => entry.id === value || entry.name === value || entry.nameJa === value || entry.nameEn === value);
  return item ? (language === 'en' ? item.nameEn : item.nameJa) : value;
};
const playerLink = player => `<a class="player-link" href="player.html?id=${player.playerId}">${nameFor(player)}</a>`;
const resultDots = (matches, playerId) => { const playerMatches = matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)), wins = playerMatches.filter(match => match.winnerId === playerId).length, losses = playerMatches.length - wins, winLabel = language === 'ja' ? '勝' : 'W', lossLabel = language === 'ja' ? '負' : 'L'; return `<aside class="match-result-dots"><i class="win">${winLabel}</i><b>${wins}</b><i class="loss">${lossLabel}</i><b>${losses}</b></aside>`; };
const opponentCategoryBreakdown = (matches, playerId) => { const records = new Map(); matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, rawLevel = data.players.find(player => player.playerId === opponentId)?.schoolLevel || '', category = lookupValue('schoolLevel', rawLevel) || (language === 'en' ? 'Unassigned' : '未設定'), key = rawLevel || 'unassigned', record = records.get(key) || { wins:0, losses:0, label: category }; if (match.winnerId === playerId) record.wins++; else record.losses++; records.set(key, record); }); return sortCategories([...records.values()].map(r => [r.label, { wins: r.wins, losses: r.losses }])).map(([category,record]) => `${category}: ${language === 'en' ? 'W' : '勝'} ${record.wins} · ${language === 'en' ? 'L' : '負'} ${record.losses}`).join('\n'); };
const categoryDistributionDetail = (category, record, total) => { const games = record.wins + record.losses, share = Math.round(games / total * 100), formatOpponents = opponents => [...opponents].map(([name,count]) => `${name} (${count})`).join(', ') || '-', wonAgainst = formatOpponents(record.wonAgainst), lostTo = formatOpponents(record.lostTo); return language === 'en' ? `${category}: ${games}/${total} matches (${share}%) · W ${record.wins}: ${wonAgainst} · L ${record.losses}: ${lostTo}` : `${category}: ${games}/${total}試合 (${share}%) · 勝 ${record.wins}: ${wonAgainst} · 負 ${record.losses}: ${lostTo}`; };
const openOpponentCategoryDetail = bar => { const detail = bar.getAttribute('aria-label') || bar.getAttribute('title') || '', match = detail.match(/^(.+): (\d+)\/(\d+)(?: matches|試合) \((\d+)%\) · (?:W|勝) (\d+): (.*) · (?:L|負) (\d+): (.*)$/); if (!match) return; let dialog = document.querySelector('#opponent-category-detail'); if (!dialog) { document.body.insertAdjacentHTML('beforeend', '<dialog id="opponent-category-detail" class="opponent-category-dialog"><button class="modal-close" type="button" aria-label="Close">×</button><div></div></dialog>'); dialog = document.querySelector('#opponent-category-detail'); } const [,category,games,total,share,wins,wonAgainst,losses,lostTo] = match, labels = language === 'en' ? { title:'Opponent Category Details',share:'Match share',record:'Record',won:'Won against',lost:'Lost to',close:'Close' } : { title:'対戦相手カテゴリの詳細',share:'対戦割合',record:'戦績',won:'勝利した相手',lost:'敗戦した相手',close:'閉じる' }, list = value => value === '-' ? '<li>-</li>' : value.split(', ').map(name => `<li>${escapeHtml(name)}</li>`).join(''); dialog.querySelector('.modal-close').setAttribute('aria-label', labels.close); dialog.querySelector('div').innerHTML = `<p class="eyebrow">${labels.title}</p><h2>${escapeHtml(category)}</h2><dl><div><dt>${labels.share}</dt><dd>${games}/${total} (${share}%)</dd></div><div><dt>${labels.record}</dt><dd>${recordText(Number(wins),Number(losses))}</dd></div></dl><section><h3>${labels.won} (${wins})</h3><ul>${list(wonAgainst)}</ul></section><section><h3>${labels.lost} (${losses})</h3><ul>${list(lostTo)}</ul></section>`; dialog.showModal(); };
document.addEventListener('click', event => { const bar = event.target.closest('.opponent-distribution i'); if (!bar || bar.closest('dialog')) return; event.preventDefault(); event.stopPropagation(); openOpponentCategoryDetail(bar); });
document.addEventListener('keydown', event => { if (event.key !== 'Enter' && event.key !== ' ') return; const bar = event.target.closest('.opponent-distribution i'); if (!bar || bar.closest('dialog')) return; event.preventDefault(); event.stopPropagation(); openOpponentCategoryDetail(bar); });
const opponentCategoryDistribution = (matches, playerId) => { const records = new Map(); matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, opponent = data.players.find(player => player.playerId === opponentId), rawLevel = opponent?.schoolLevel || '', category = lookupValue('schoolLevel', rawLevel) || (language === 'en' ? 'Unassigned' : '未設定'), key = rawLevel || 'unassigned', record = records.get(key) || { wins:0, losses:0, wonAgainst:new Map(), lostTo:new Map(), label: category }, opponentName = nameFor(opponent || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }); if (match.winnerId === playerId) { record.wins++; record.wonAgainst.set(opponentName, (record.wonAgainst.get(opponentName) || 0) + 1); } else { record.losses++; record.lostTo.set(opponentName, (record.lostTo.get(opponentName) || 0) + 1); } records.set(key,record); }); const entries = sortCategories([...records.values()].map(r => [r.label, { wins: r.wins, losses: r.losses, wonAgainst: r.wonAgainst, lostTo: r.lostTo }])), total = entries.reduce((sum,[,record]) => sum + record.wins + record.losses, 0); return entries.length ? `<div class="leader-opponent-distribution"><small>${language === 'en' ? 'Opponent Category Distribution' : '対戦相手カテゴリ分布'}</small><div class="opponent-distribution">${entries.map(([category,record]) => { const games = record.wins + record.losses, detail = categoryDistribution.escape(categoryDistributionDetail(category, record, total)); return `<i style="flex:${games};--category-color:${categoryDistribution.color(category)}" tabindex="0" title="${detail}" aria-label="${detail}"></i>`; }).join('')}</div><div class="opponent-distribution-labels">${entries.map(([category,record]) => `<span style="flex:${record.wins + record.losses};--category-color:${categoryDistribution.color(category)}">${categoryDistribution.escape(category)}</span>`).join('')}</div></div>` : ''; };
const leaderboardOpponentDistribution = (matches, playerIds) => { const records = new Map(); playerIds.forEach(playerId => matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, opponent = data.players.find(player => player.playerId === opponentId), rawLevel = opponent?.schoolLevel || '', category = lookupValue('schoolLevel', rawLevel) || (language === 'en' ? 'Unassigned' : '未設定'), key = rawLevel || 'unassigned', record = records.get(key) || { wins:0, losses:0, wonAgainst:new Map(), lostTo:new Map(), label: category }, opponentName = nameFor(opponent || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }); if (match.winnerId === playerId) { record.wins++; record.wonAgainst.set(opponentName, (record.wonAgainst.get(opponentName) || 0) + 1); } else { record.losses++; record.lostTo.set(opponentName, (record.lostTo.get(opponentName) || 0) + 1); } records.set(key,record); })); const entries = sortCategories([...records.values()].map(r => [r.label, { wins: r.wins, losses: r.losses, wonAgainst: r.wonAgainst, lostTo: r.lostTo }])), total = entries.reduce((sum,[,record]) => sum + record.wins + record.losses, 0); return entries.length ? `<section class="leaderboard-opponent-summary"><small>${language === 'en' ? 'Qualified Player Opponent Category Distribution' : '対象選手の対戦相手カテゴリ分布'}</small><div class="opponent-distribution">${entries.map(([category,record]) => { const games = record.wins + record.losses, detail = categoryDistribution.escape(categoryDistributionDetail(category, record, total)); return `<i style="flex:${games};--category-color:${categoryDistribution.color(category)}" tabindex="0" title="${detail}" aria-label="${detail}"></i>`; }).join('')}</div><div class="opponent-distribution-labels">${entries.map(([category,record]) => `<span style="flex:${record.wins + record.losses};--category-color:${categoryDistribution.color(category)}">${categoryDistribution.escape(category)}</span>`).join('')}</div></section>` : ''; };
const recordSummary = (stats, matches, playerId) => { const games = stats.wins + stats.losses, rate = Math.round(stats.wins / games * 100), winLabel = language === 'ja' ? '勝' : 'W', lossLabel = language === 'ja' ? '負' : 'L', categories = opponentCategoryBreakdown(matches, playerId); return `<span class="leader-record"><b class="${rate >= 50 ? 'positive' : 'negative'}" title="${categories}">${rate}%</b><small><i class="win">${winLabel}</i> ${stats.wins} <i class="loss">${lossLabel}</i> ${stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</small>${opponentCategoryDistribution(matches, playerId)}</span>`; };
const isComplete = match => Number(match.player1Sets) >= 3 || Number(match.player2Sets) >= 3;
const eligibility = (matches, matchesPerDay = 1) => { const gameDays = new Set(matches.filter(isComplete).map(match => match.matchDate)).size, minimum = gameDays * matchesPerDay; return { minimum, gameDays, text: language === 'en' ? `Eligibility: At least ${minimum} completed matches in total (${matchesPerDay} × ${gameDays} match days) for a fair comparison.` : `対象: 公平な比較のため、合計${minimum}試合以上（${matchesPerDay}試合 × ${gameDays}試合日）。` }; };
const minimumText = minimum => language === 'en' ? `min. ${minimum}` : `最低${minimum}試合`;
const categoryPrecedence = category => ({ '小学生':0, 'Elementary School':0, 'Elementary school':0, '中学生':1, 'Middle school':1, 'Junior High School':1, '高校生':2, 'High school':2, 'High School':2, '一般':3, 'Adult':3, '未設定':4, 'Unassigned':4 })[category] ?? 99;
const sortCategories = entries => entries.sort(([left], [right]) => categoryPrecedence(left) - categoryPrecedence(right) || left.localeCompare(right, 'ja'));
const isAssignedCategory = category => category && category !== t('unassigned') && category !== 'Unassigned';
const categoryLeaders = () => language === 'en' ? 'Category leaders' : 'カテゴリ首位';
const rankIcon = index => ['🥇', '🥈', '🥉'][index] || `${index + 1}`;
const phrase = key => ({ matchDays: language === 'en' ? 'match days' : '試合日', since: language === 'en' ? 'Since' : '集計開始', yearKicker: language === 'en' ? 'YEAR IN REVIEW' : '年間成績', yearTitle: language === 'en' ? 'Yearly Leaderboard' : '年間リーダーボード', selectYear: language === 'en' ? 'Select year' : '年を選択', trainingLog: language === 'en' ? 'CLUB TRAINING MATCH GAME LOG' : 'クラブ練習試合ゲームログ', matchDayVolume: language === 'en' ? 'Match-Day Volume' : '試合日別試合数', menu: language === 'en' ? 'MENU' : 'メニュー', h2h: language === 'en' ? 'HEAD TO HEAD' : '直接対決', h2hTimeline: language === 'en' ? 'Newest to oldest · Win / Draw / Loss timeline' : '新しい順 · 勝ち / 引分 / 負け タイムライン', win: language === 'en' ? 'WIN' : '勝ち', loss: language === 'en' ? 'LOSS' : '負け', draw: language === 'en' ? 'DRAW' : '引分' })[key];
const clubIntroduction = () => language === 'en' ? `<p class="eyebrow">KANAGAWA · JAPAN</p><h2>Welcome to <em>Little Kings</em></h2><p>Little Kings is a table tennis club based in Kanagawa, Japan, primarily for elementary and junior-high school students. We are accepting new members and welcome visits, free trial sessions, and enquiries at any time.</p><p>Guided by the principle of <strong>Sottaku</strong>, we support members from Grade 1 through Grade 12. Beginners and players with no previous experience are welcome: we teach the fundamentals step by step, at each player’s own level and toward their own goals.</p><h3>Grow Through Table Tennis</h3><p>We help each player develop their individual strengths while valuing growth, cooperation, and independence. Training balances enjoyment and improvement with play-based elements, alongside manners, respect for opponents, and respect for the rules. Through matches and exchanges with many people, our members learn to participate with confidence, kindness, and energy.</p><p class="club-intro-close">Why not take on the challenge with Little Kings?</p><aside class="club-contact"><b>CONTACT</b><span>Phone <a href="tel:09015555060">090-1555-5060</a></span><span>Email <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span></aside><aside class="club-instagram"><b>FOLLOW OUR ACTIVITY</b><p>See Little Kings’ latest training and club activity on Instagram.</p><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram <span>@ritokin.ryumon</span></a></aside>` : `<p class="eyebrow">KANAGAWA · JAPAN</p><h2><em>リトルキングス</em>へようこそ</h2><p>神奈川県を拠点に活動する、小学生・中学生を中心とした卓球クラブチーム、リトルキングスの公式ホームページへようこそ。</p><p>新規会員を募集しています。見学・無料体験・お問い合わせは随時受け付けています。お気軽にご連絡ください。</p><h3>「啐啄」の理念</h3><p>リトルキングスは「啐啄」を理念に掲げ、小学1年生から高校3年生までが所属しています。未経験の方や初心者の方にも、基礎から一人ひとりのレベルや目標に合わせて丁寧に指導します。</p><h3>卓球を通した成長</h3><p>卓球を通して個々の才能を伸ばし、子どもたちの成長・協調性・自立心を大切にしています。楽しさと上達を両立するために遊びの要素も取り入れながら、試合や交流の場では礼儀やマナー、相手への敬意、ルールを守ることの大切さを学びます。</p><p>多様な人との交流を通じて、子どもたちが「明るく、楽しく、元気よく」成長できるクラブを目指しています。</p><p class="club-intro-close">リトルキングスで一緒に頑張ってみませんか！</p><aside class="club-contact"><b>お問い合わせ</b><span>電話 <a href="tel:09015555060">090-1555-5060</a></span><span>メール <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span></aside><aside class="club-instagram"><b>最新の活動状況はInstagramにて！</b><p>リトルキングスのInstagramをぜひご覧ください。</p><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram <span>@ritokin.ryumon</span></a></aside>`;
const eventType = match => /club|training|練習/i.test(`${match.event} ${match.division}`) ? 'training' : 'tournament';
const visibleMatches = () => data.matches.filter(match => eventType(match) === 'training' && (selectedYear === 'all' || match.matchDate.startsWith(selectedYear)) && (selectedMonth === 'all' || match.matchDate.startsWith(selectedMonth)));
const playerMap = () => new Map(data.players.map(player => [player.playerId, player]));
function renderMatchPortraits() {
  const players = playerMap();
  document.querySelectorAll('.match-card[data-match-id]').forEach(card => {
    const match = data.matches.find(item => item.matchId === card.dataset.matchId);
    if (!match) return;
    [match.player1Id, match.player2Id].forEach((playerId, index) => {
      const player = players.get(playerId), name = card.querySelectorAll('.match-player')[index];
      if (!player || !name || name.querySelector('.match-portrait')) return;
      const portrait = document.createElement('figure'), image = document.createElement('img');
      portrait.className = 'match-portrait'; image.src = `img/${encodeURIComponent(player.playerId)}.jpg`; image.alt = nameFor(player);
      image.onerror = () => { if (image.dataset.fallback) portrait.remove(); else { image.dataset.fallback = 'true'; image.src = 'img/NoProfilePic.jpg'; } }; portrait.append(image); name.prepend(portrait);
    });
  });
}

function playerStats(matches = visibleMatches()) {
  const stats = new Map(data.players.map(player => [player.playerId, { wins: 0, losses: 0, setsFor: 0, setsAgainst: 0 }]));
  matches.filter(isComplete).forEach(match => {
    [[match.player1Id, match.player1Sets, match.player2Sets], [match.player2Id, match.player2Sets, match.player1Sets]].forEach(([id, won, lost]) => {
      const record = stats.get(id);
      if (!record) return;
      record.setsFor += won; record.setsAgainst += lost;
      if (match.winnerId === id) record.wins++; else record.losses++;
    });
  });
  return stats;
}

function rankPlayers(matches = visibleMatches()) {
  const stats = playerStats(matches);
  return data.players.map(player => ({ player, stats: stats.get(player.playerId) })).sort((a, b) => { const ap = a.stats.wins + a.stats.losses, bp = b.stats.wins + b.stats.losses; const ar = ap ? a.stats.wins / ap : 0, br = bp ? b.stats.wins / bp : 0; return br - ar || bp - ap || b.stats.wins - a.stats.wins; });
}

function matchCard(match, players) {
  const first = players.get(match.player1Id) || { displayName: match.player1Name };
  const second = players.get(match.player2Id) || { displayName: match.player2Name };
  const firstResult = match.winnerId === match.player1Id ? 'win' : match.winnerId === match.player2Id ? 'loss' : '', secondResult = match.winnerId === match.player2Id ? 'win' : match.winnerId === match.player1Id ? 'loss' : '', dot = result => result ? `<i class="game-result-dot ${result}" title="${phrase(result)}">${result === 'win' ? 'W' : 'L'}</i>` : ''; return `<button class="match-card" data-match-id="${match.matchId}"><div class="match-meta"><span>${dateLabel(match.matchDate)}</span><span class="badge ${eventType(match)}">${t(eventType(match))}</span></div><div class="match-score"><span class="match-player ${firstResult === 'win' ? 'winner' : firstResult === 'loss' ? 'loser' : ''}">${dot(firstResult)}${nameFor(first)}${first.schoolLevel ? `<small class="match-category">${lookupValue('schoolLevel', first.schoolLevel)}</small>` : ''}</span><strong class="score">${match.player1Sets} <i>:</i> ${match.player2Sets}</strong><span class="match-player ${secondResult === 'win' ? 'winner' : secondResult === 'loss' ? 'loser' : ''}">${dot(secondResult)}${nameFor(second)}${second.schoolLevel ? `<small class="match-category">${lookupValue('schoolLevel', second.schoolLevel)}</small>` : ''}</span></div><div class="match-context"><span>${match.event || 'Little Kings'}</span><b>${!isComplete(match) ? t('incomplete') : ''}</b></div></button>`;
}


function renderSession() {
  const dates = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate))].sort().reverse();
  if (!dates.length) { document.querySelector('#session-summary').textContent = t('noSessions'); return; }
  if (!dates.includes(selectedSession)) selectedSession = dates[0];
  if (!calendarMonth) calendarMonth = selectedSession.slice(0, 7);
  renderCalendar(dates);
  const chronologicalDates = [...dates].reverse(), counts = chronologicalDates.map(date => data.matches.filter(match => match.matchDate === date && eventType(match) === 'training').length), participants = chronologicalDates.map(date => new Set(data.matches.filter(match => match.matchDate === date && eventType(match) === 'training').flatMap(match => [match.player1Id,match.player2Id])).size);
  charts.push(new Chart(document.querySelector('#session-timeline-chart'), { type: 'bar', data: { labels: chronologicalDates, datasets: [{ label: t('players'), data: participants, backgroundColor: 'rgba(84,184,209,.62)', borderRadius: 4 }, { type: 'line', label: t('matches'), data: counts, borderColor: '#d6a516', backgroundColor: '#d6a516', tension: .25, pointBackgroundColor: '#f6f0e2', pointRadius: 4, order: 10 }] }, options: { plugins: { legend: { labels: { color: '#f6f0e2' } } }, scales: { x: { ticks: { color: '#a5a198', maxRotation: 45 }, grid: { display: false } }, y: { ticks: { color: '#a5a198', stepSize: 1 }, grid: { color: 'rgba(246,240,226,.1)' } } } } }));
  showSession(selectedSession);
}

function renderCalendar(dates) {
  const [year, month] = calendarMonth.split('-').map(Number);
  const monthStart = new Date(year, month - 1, 1);
  const startDay = monthStart.getDay();
  const days = new Date(year, month, 0).getDate();
  const cells = Array.from({ length: startDay }, () => '<span class="calendar-day blank"></span>');
  for (let day = 1; day <= days; day++) {
    const date = `${calendarMonth}-${String(day).padStart(2, '0')}`;
    const available = dates.includes(date);
    cells.push(`<button class="calendar-day ${available ? 'available' : ''} ${date === selectedSession ? 'selected' : ''}" ${available ? `data-date="${date}"` : 'disabled'}>${day}</button>`);
  }
  document.querySelector('#session-calendar').innerHTML = `<div class="calendar-head"><button data-direction="-1" aria-label="Previous month">‹</button><strong>${calendarMonth}</strong><button data-direction="1" aria-label="Next month">›</button></div><div class="calendar-week">${(language === 'en' ? ['S','M','T','W','T','F','S'] : ['日','月','火','水','木','金','土']).map(day => `<span>${day}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div>`;
  document.querySelector('#session-calendar').onclick = event => {
    const date = event.target.dataset.date;
    if (date) { selectedSession = date; selectedSessionMatchup = ''; sessionMatchupsExpanded = false; calendarMonth = date.slice(0, 7); renderCalendar(dates); showSession(date); return; }
    const direction = Number(event.target.dataset.direction);
    if (direction) { const next = new Date(year, month - 1 + direction, 1); calendarMonth = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`; renderCalendar(dates); }
  };
}

function renderLatestSession() {
  const trainingDates = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate))].sort().reverse();
  if (!trainingDates.length) { document.querySelector('#latest-session').innerHTML = `<p class="empty">${t('noSessions')}</p>`; return; }
  const latestDate = trainingDates[0];
  const matches = data.matches.filter(match => match.matchDate === latestDate && eventType(match) === 'training');
  const completed = matches.filter(isComplete);
  const incomplete = matches.filter(m => !isComplete(m));
  const participants = new Set(matches.flatMap(match => [match.player1Id, match.player2Id]));
  const players = playerMap();
  const topResults = completed.slice(0, 5);
  const resultRows = topResults.map(match => {
    const first = players.get(match.player1Id) || { displayName: match.player1Name };
    const second = players.get(match.player2Id) || { displayName: match.player2Name };
    const firstWin = match.winnerId === match.player1Id;
    return `<a class="latest-result-row" href="player.html?id=${match.player1Id}&opponent=${match.player2Id}"><span class="latest-result-winner ${firstWin ? '' : 'opposite'}">${nameFor(first)}</span><span class="latest-result-score">${match.player1Sets} : ${match.player2Sets}</span><span class="latest-result-loser ${firstWin ? 'opposite' : ''}">${nameFor(second)}</span></a>`;
  }).join('');
  const detail = language === 'en'
    ? `${completed.length} ${t('completedMatches')} · ${incomplete.length} ${t('incompleteMatches')} · ${participants.size} ${t('playersParticipated')}`
    : `${completed.length}${t('completedMatches')} · ${incomplete.length}${t('incompleteMatches')} · ${participants.size}${t('playersParticipated')}`;
  document.querySelector('#latest-session').innerHTML = `
    <div class="latest-session-inner">
      <div class="latest-session-header">
        <div>
          <p class="eyebrow">${t('latestSessionKicker')}</p>
          <h2>${dateLabel(latestDate)}</h2>
        </div>
        <a class="latest-session-link" href="#sessions">${t('viewFullSession')} →</a>
      </div>
      <div class="latest-session-metrics">
        <div class="latest-metric"><strong>${matches.length}</strong><span>${t('matches')}</span></div>
        <div class="latest-metric"><strong>${participants.size}</strong><span>${t('players')}</span></div>
        <div class="latest-metric"><strong>${completed.length}</strong><span>${t('completedMatches')}</span></div>
      </div>
      ${resultRows ? `<div class="latest-session-results"><small>${language === 'en' ? 'Match Results' : '試合結果'}</small>${resultRows}</div>` : `<p class="latest-session-empty">${t('noCompletedMatches')}</p>`}
    </div>`;
}

function showSession(date) {
  const matches = data.matches.filter(match => match.matchDate === date && eventType(match) === 'training');
  const participants = new Set(matches.flatMap(match => [match.player1Id, match.player2Id])).size;
  const participantLabel = language === 'en' ? `View ${participants} players participating on ${dateLabel(date)}` : `${dateLabel(date)}に参加した${participants}選手を表示`;
  document.querySelector('#session-summary').innerHTML = `<strong>${dateLabel(date)}</strong><span>${matches.length} ${t('matches')}</span><button type="button" class="session-player-open" aria-label="${escapeHtml(participantLabel)}">${participants} ${t('players')}</button>`;
  document.querySelector('#session-summary .session-player-open').onclick = () => {
    const players = playerMap(), members = [...new Set(matches.flatMap(match => [match.player1Id, match.player2Id]))].map(playerId => {
      const match = matches.find(item => item.player1Id === playerId || item.player2Id === playerId);
      return players.get(playerId) || { playerId, displayName: match?.player1Id === playerId ? match.player1Name : match?.player2Name };
    });
    openActivePlayerList(dateLabel(date), members, matches, true);
  };
  const players = playerMap(), categoryFor = playerId => lookupValue('schoolLevel', players.get(playerId)?.schoolLevel) || t('unassigned'), matchupFor = match => [categoryFor(match.player1Id), categoryFor(match.player2Id)].sort((left, right) => categoryPrecedence(left) - categoryPrecedence(right) || left.localeCompare(right, 'ja'));
  const matchups = new Map();
  matches.filter(isComplete).forEach(match => {
    const categories = matchupFor(match), key = JSON.stringify(categories), record = matchups.get(key) || { categories, count:0 };
    record.count++;
    matchups.set(key, record);
  });
  const entries = [...matchups.entries()].sort(([, left], [, right]) => categoryPrecedence(left.categories[0]) - categoryPrecedence(right.categories[0]) || categoryPrecedence(left.categories[1]) - categoryPrecedence(right.categories[1]) || left.categories.join().localeCompare(right.categories.join(), 'ja'));
  if (!entries.some(([key]) => key === selectedSessionMatchup)) selectedSessionMatchup = '';
  let breakdown = document.querySelector('#session-matchup-breakdown');
  if (!breakdown) { breakdown = document.createElement('section'); breakdown.id = 'session-matchup-breakdown'; breakdown.className = 'session-matchup-breakdown'; document.querySelector('#session-summary').insertAdjacentElement('afterend', breakdown); }
  const visibleEntries = sessionMatchupsExpanded ? entries : entries.slice(0, 3), labels = language === 'en' ? { title:'Matchup breakdown', composition:'Matchup composition', all:'Show all', less:'Show less', clear:'Clear filter', versus:'vs', completed:'completed matches' } : { title:'対戦カテゴリ内訳', composition:'対戦カテゴリ構成', all:'すべて表示', less:'表示を減らす', clear:'絞り込み解除', versus:'対', completed:'完了試合' };
  breakdown.hidden = !entries.length;
  breakdown.innerHTML = entries.length ? `<div class="session-matchup-head"><b>${labels.title}</b>${selectedSessionMatchup ? `<button type="button" data-session-matchup-clear>${labels.clear}</button>` : ''}</div><div class="session-matchup-composition" role="group" aria-label="${labels.composition}">${entries.map(([key, record]) => { const matchup = record.categories.join(` ${labels.versus} `), detail = `${matchup}: ${record.count} ${labels.completed}`; return `<button type="button" class="session-matchup-segment ${key === selectedSessionMatchup ? 'active' : ''}" data-session-matchup="${escapeHtml(key)}" aria-pressed="${key === selectedSessionMatchup}" title="${escapeHtml(detail)}" aria-label="${escapeHtml(detail)}" style="flex:${record.count};--matchup-first:${categoryDistribution.color(record.categories[0])};--matchup-second:${categoryDistribution.color(record.categories[1])}"></button>`; }).join('')}</div><div class="session-matchup-rows">${visibleEntries.map(([key, record]) => `<button type="button" class="session-matchup-row ${key === selectedSessionMatchup ? 'active' : ''}" data-session-matchup="${escapeHtml(key)}" aria-pressed="${key === selectedSessionMatchup}"><span class="session-matchup-indicators">${record.categories.map(category => `<i style="--category-color:${categoryDistribution.color(category)}"></i>`).join('')}</span><span>${record.categories.map(escapeHtml).join(` <em>${labels.versus}</em> `)}</span><b>${record.count}</b></button>`).join('')}</div>${entries.length > 3 ? `<button type="button" class="session-matchup-toggle" data-session-matchup-toggle>${sessionMatchupsExpanded ? labels.less : labels.all}</button>` : ''}` : '';
  breakdown.onclick = event => {
    if (event.target.closest('[data-session-matchup-clear]')) selectedSessionMatchup = '';
    else if (event.target.closest('[data-session-matchup-toggle]')) sessionMatchupsExpanded = !sessionMatchupsExpanded;
    else { const row = event.target.closest('[data-session-matchup]'); if (!row) return; selectedSessionMatchup = selectedSessionMatchup === row.dataset.sessionMatchup ? '' : row.dataset.sessionMatchup; }
    showSession(date);
  };
  const displayedMatches = selectedSessionMatchup ? matches.filter(match => JSON.stringify(matchupFor(match)) === selectedSessionMatchup) : matches;
  document.querySelector('#session-matches').innerHTML = displayedMatches.map(match => matchCard(match, players)).join('');
  renderMatchPortraits();
}

function openActivePlayerList(title, members, matches = data.matches, groupedByCategory = false) {
  if (!document.querySelector('#active-player-list')) document.body.insertAdjacentHTML('beforeend', '<dialog id="active-player-list" class="active-player-list"><button class="modal-close" aria-label="Close">×</button><div id="active-player-list-content"></div></dialog>');
  const labels = language === 'en' ? { kicker:groupedByCategory ? 'SESSION PARTICIPANTS' : 'ACTIVE PLAYERS', displayName:'Display Name', englishName:'Preferred English Name', id:'Player ID', category:'Category', gender:'Gender', hand:'Playing Hand', style:'Playing Style', grip:'Grip', games:'Completed Games', record:'W / L', rate:'Win %' } : { kicker:groupedByCategory ? '練習日参加選手' : 'アクティブ選手', displayName:'表示名', englishName:'希望英語名', id:'選手ID', category:'カテゴリ', gender:'性別', hand:'利き手', style:'戦型', grip:'グリップ', games:'完了試合数', record:'勝 / 負', rate:'勝率' };
  const stats = playerStats(matches), playerRow = player => {
    const record = stats.get(player.playerId) || { wins:0, losses:0 }, games = record.wins + record.losses, rate = games ? Math.round(record.wins / games * 100) : 0;
    const details = [[labels.category,lookupValue('schoolLevel',player.schoolLevel)],[labels.gender,player.gender],[labels.hand,player.playingHand],[labels.style,player.playingStyle],[labels.grip,player.grip]].filter(([, value]) => value);
    return `<li><a class="active-player-row" href="player.html?id=${encodeURIComponent(player.playerId)}"><figure class="active-player-portrait"><img src="img/${encodeURIComponent(player.playerId)}.jpg" alt="${escapeHtml(player.displayName || player.englishName || player.playerId)}"></figure><div class="active-player-main"><div class="active-player-names"><span><small>${labels.displayName}</small><b>${escapeHtml(player.displayName || '-')}</b></span><span><small>${labels.englishName}</small><b>${escapeHtml(player.englishName || '-')}</b></span></div><div class="active-player-details"><span><b>${labels.id}</b>${escapeHtml(player.playerId || '-')}</span>${details.map(([label, value]) => `<span><b>${label}</b>${escapeHtml(value)}</span>`).join('')}</div><div class="active-player-record"><span><b>${labels.games}</b>${games}</span><span><b>${labels.record}</b>${record.wins} / ${record.losses}</span><span><b>${labels.rate}</b>${rate}%</span></div></div></a></li>`;
  };
  const groups = new Map();
  if (groupedByCategory) members.forEach(player => { const category = lookupValue('schoolLevel', player.schoolLevel) || t('unassigned'); if (!groups.has(category)) groups.set(category, []); groups.get(category).push(player); });
  const content = groupedByCategory ? `<div class="session-player-groups">${sortCategories([...groups.entries()]).map(([category, players]) => `<section><h3>${escapeHtml(category)}</h3><ul>${players.map(playerRow).join('')}</ul></section>`).join('')}</div>` : `<ul>${members.map(playerRow).join('')}</ul>`;
  document.querySelector('#active-player-list-content').innerHTML = `<p class="eyebrow">${labels.kicker}</p><h2>${escapeHtml(title)}</h2><p>${members.length} ${t('players')}</p>${content}`;
  document.querySelector('#active-player-list').showModal();
}

function setupMonths() {
  const select = document.querySelector('#month-select');
  const months = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate.slice(0, 7)))].sort().reverse();
  select.innerHTML = `<option value="all">${t('allResults')}</option>${months.map(month => `<option value="${month}">${month}</option>`).join('')}`;
  select.value = months.includes(selectedMonth) ? selectedMonth : 'all';
  const years = [...new Set(months.map(month => month.slice(0, 4)))];
  const yearSelect = document.querySelector('#year-select');
  yearSelect.innerHTML = `<option value="all">${t('allResults')}</option>${years.map(year => `<option value="${year}">${year}</option>`).join('')}`;
  yearSelect.value = years.includes(selectedYear) ? selectedYear : 'all';
}

function renderPlayers(ranked) {
  const query = document.querySelector('#player-search').value.toLowerCase();
  const groups = new Map();
  ranked.filter(entry => entry.stats.wins + entry.stats.losses > 0 && nameFor(entry.player).toLowerCase().includes(query)).forEach(entry => { const category = lookupValue('schoolLevel', entry.player.schoolLevel) || t('unassigned'); if (!groups.has(category)) groups.set(category, []); groups.get(category).push(entry); });
  document.querySelector('#player-grid').innerHTML = sortCategories([...groups.entries()]).map(([category, entries]) => { const orderedEntries = category === t('unassigned') ? [...entries].sort((left,right) => right.stats.wins + right.stats.losses - left.stats.wins - left.stats.losses) : entries; return `<section class="player-category"><h3>${category}</h3><div class="player-grid">${orderedEntries.map(({ player, stats }) => {
    const total = stats.wins + stats.losses;
    const rate = total ? Math.round(stats.wins / total * 100) : 0, escape = value => String(value).replace(/[&<>'"]/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[character]), labels = language === 'en' ? { games:'Games', wins:'W', losses:'L', rate:'Win %', handStyle:'Hand / Style', grip:'Grip', forehand:'FH', backhand:'BH' } : { games:'試合', wins:'勝', losses:'負', rate:'勝率', handStyle:'利き手 / 戦型', grip:'グリップ', forehand:'フォア', backhand:'バック' }, traits = [[labels.handStyle,[player.playingHand, player.playingStyle].filter(Boolean).join(' · ')],[labels.grip,player.grip]].filter(([,value]) => value), equipment = [[labels.forehand,[player.forehandRubberType, rubberName(player.forehandRubber)].filter(Boolean).join(' / ')],[labels.backhand,[player.backhandRubberType, rubberName(player.backhandRubber)].filter(Boolean).join(' / ')]] .filter(([,value]) => value), playerId = escape(player.playerId), playerName = escape(nameFor(player)), categoryName = escape(lookupValue('schoolLevel', player.schoolLevel) || t('unassigned')), recordDetail = language === 'en' ? `${stats.wins} wins, ${stats.losses} losses, ${rate}% win rate` : `${stats.wins}勝、${stats.losses}負、勝率${rate}%`;
    return `<a class="player-card" href="player.html?id=${encodeURIComponent(player.playerId)}"><header class="player-card-head"><span class="player-id">${playerId}</span><span class="player-category-badge">${categoryName}</span></header><div class="player-card-identity"><figure class="player-portrait"><img src="img/${encodeURIComponent(player.playerId)}.jpg" alt="${playerName}" onerror="this.closest('.player-portrait').remove()"></figure><h3 class="player-name">${playerName}</h3></div><div class="player-games"><span>${labels.games}</span><strong>${total}</strong></div><div class="player-record"><span><b>${labels.wins}</b>${stats.wins}</span><span><b>${labels.losses}</b>${stats.losses}</span><span><b>${labels.rate}</b>${rate}%</span></div><div class="record-bar" role="img" aria-label="${escape(recordDetail)}"><i aria-hidden="true" style="width:${stats.wins / total * 100}%"></i><b aria-hidden="true" style="width:${stats.losses / total * 100}%"></b></div>${traits.length ? `<div class="player-traits">${traits.map(([label,value]) => `<span><b>${label}</b>${escape(value)}</span>`).join('')}</div>` : ''}${equipment.length ? `<div class="player-equipment">${equipment.map(([label,value]) => `<span><b>${label}</b>${escape(value)}</span>`).join('')}</div>` : ''}</a>`;
  }).join('')}</div></section>`; }).join('');
}

function renderGroupStats(matches) {
  const playerById = playerMap();
  const renderGroup = (field, target) => {
    const groups = new Map();
    const groupName = player => lookupValue(field, player[field]) || t('unassigned');
    data.players.forEach(player => groups.set(groupName(player), { players: 0, wins: 0, games: 0, members: [] }));
    data.players.forEach(player => { const group = groups.get(groupName(player)); group.players++; group.members.push(player); });
    matches.filter(isComplete).forEach(match => [match.player1Id, match.player2Id].forEach(id => { const player = playerById.get(id); if (!player) return; const group = groups.get(groupName(player)); group.games++; if (match.winnerId === id) group.wins++; }));
    const entries = field === 'schoolLevel' ? sortCategories([...groups.entries()]) : [...groups.entries()].sort((a, b) => b[1].games - a[1].games);
    const totalGames = entries.reduce((total, [, value]) => total + value.games, 0);
    document.querySelector(target).innerHTML = entries.map(([label, value], index) => `<button class="group-row active-group-open" type="button" data-index="${index}"><strong>${escapeHtml(label)}</strong><span>${value.players} ${t('players')}</span><span>${totalGames ? Math.round(value.games / totalGames * 100) : 0}%</span></button>`).join(''); document.querySelectorAll(`${target} .active-group-open`).forEach(button => { button.onclick = () => { const [label, value] = entries[Number(button.dataset.index)]; openActivePlayerList(label, value.members); }; });
  };
  renderGroup('schoolLevel', '#category-stats');
  renderGroup('gender', '#gender-stats');
  const setupFields = language === 'en' ? [['playingStyle','Playing Style'],['grip','Grip'],['forehandRubberType','Forehand Rubber Type'],['backhandRubberType','Backhand Rubber Type']] : [['playingStyle','戦型'],['grip','グリップ'],['forehandRubberType','フォア面ラバー種類'],['backhandRubberType','バック面ラバー種類']]; document.querySelector('#player-setup-distribution').innerHTML = setupFields.map(([field,label]) => { const reported = data.players.filter(player => player[field]), groups = new Map(); reported.forEach(player => { const value = lookupValue(field, player[field]); groups.set(value, (groups.get(value) || 0) + 1); }); const entries = [...groups.entries()].sort((left,right) => right[1] - left[1] || left[0].localeCompare(right[0],'ja')); return `<section><header><b>${label}</b><small>${reported.length}/${data.players.length} ${language === 'en' ? 'reported' : '登録'}</small></header>${entries.length ? entries.map(([value,count]) => `<div class="setup-row"><span title="${escapeHtml(value)}">${escapeHtml(value)}</span><b>${count}</b><i><em style="width:${Math.round(count / reported.length * 100)}%"></em></i></div>`).join('') : `<p>${language === 'en' ? 'No profile data yet' : 'プロフィール情報が未登録です'}</p>`}</section>`; }).join('');
}

function renderLeaderboardDashboard() {
  const months = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate.slice(0, 7)))].sort().reverse();
  const years = [...new Set(data.matches.filter(match => eventType(match) === 'training' && match.matchDate).map(match => match.matchDate.slice(0, 4)))].sort().reverse();
  const isMonth = leaderboardView === 'month';
  const helpBtn = document.querySelector('#leaderboard-help');
  const prevBtn = document.querySelector('#leaderboard-prev');
  const nextBtn = document.querySelector('#leaderboard-next');
  const label = document.querySelector('#leaderboard-period-label');
  const detail = document.querySelector('#leaderboard-detail');
  const content = document.querySelector('#leaderboard-content');
  // Update tab active state
  document.querySelectorAll('.leaderboard-tab').forEach(tab => { tab.classList.toggle('active', tab.dataset.view === leaderboardView); });
  if (isMonth) {
    recentStart = Math.min(recentStart, Math.max(0, months.length - 1));
    const month = months[recentStart] || '';
    prevBtn.disabled = recentStart >= months.length - 1;
    nextBtn.disabled = recentStart === 0;
    label.textContent = month;
    helpBtn.dataset.help = 'monthly';
    helpBtn.setAttribute('aria-label', language === 'en' ? 'How to read the monthly leaderboard' : '月間リーダーボードの見方');
    const matches = data.matches.filter(match => eventType(match) === 'training' && match.matchDate.startsWith(month));
    const participants = new Set(matches.flatMap(match => [match.player1Id, match.player2Id]));
    const periodEligibility = eligibility(matches, 2);
    const rankings = rankPlayers(matches).filter(entry => entry.stats.wins + entry.stats.losses >= periodEligibility.minimum);
    const groups = new Map();
    rankings.forEach(entry => { const category = lookupValue('schoolLevel', entry.player.schoolLevel) || t('unassigned'); if (!groups.has(category)) groups.set(category, []); groups.get(category).push(entry); });
    const categories = sortCategories([...groups.entries()].filter(([category]) => isAssignedCategory(category)));
    monthlyCategoryEntries = new Map(); monthlyCategoryMatches = new Map();
    categories.forEach(([cat, entries]) => { monthlyCategoryEntries.set(`${month}|${cat}`, entries); monthlyCategoryMatches.set(`${month}|${cat}`, matches); });
    detail.textContent = language === 'en' ? `${periodEligibility.gameDays} ${phrase('matchDays')} · ${participants.size} ${t('players')} ${t('participated')}` : `${periodEligibility.gameDays}${phrase('matchDays')} · ${participants.size}${t('players')}${t('participated')}`;
    const avatar = player => `<figure class="monthly-avatar"><img src="img/${encodeURIComponent(player.playerId)}.jpg" alt=""></figure>`;
    content.innerHTML = `<div class="leaderboard-podiums">${categories.map(([category, entries]) => `<section class="category-podium"><button class="category-ranking-open" data-month="${month}" data-category="${category}">🏆 ${category}<small>${t('viewAllRankings')}</small></button>${entries.slice(0, 3).map((entry, index) => `<div><i>${rankIcon(index)}</i>${avatar(entry.player)}<b>${playerLink(entry.player)}</b>${recordSummary(entry.stats, matches, entry.player.playerId)}</div>`).join('')}</section>`).join('')}</div>`;
  } else {
    leaderboardYearIndex = Math.min(leaderboardYearIndex, Math.max(0, years.length - 1));
    const year = years[leaderboardYearIndex] || '';
    prevBtn.disabled = leaderboardYearIndex >= years.length - 1;
    nextBtn.disabled = leaderboardYearIndex === 0;
    label.textContent = year;
    helpBtn.dataset.help = 'yearly';
    helpBtn.setAttribute('aria-label', language === 'en' ? 'How to read the yearly leaderboard' : '年間リーダーボードの見方');
    const matches = data.matches.filter(match => eventType(match) === 'training' && match.matchDate.startsWith(year));
    const rankings = rankPlayers(matches).filter(entry => entry.stats.wins + entry.stats.losses >= eligibility(matches).minimum);
    const categories = new Map();
    rankings.forEach(entry => { const category = lookupValue('schoolLevel', entry.player.schoolLevel) || t('unassigned'); if (!categories.has(category)) categories.set(category, []); categories.get(category).push(entry); });
    const categoryEntries = sortCategories([...categories.entries()].filter(([category]) => isAssignedCategory(category)));
    categoryLeaderboardEntries = new Map(categoryEntries); categoryLeaderboardYear = year; categoryLeaderboardMatches = matches;
    const participants = new Set(matches.filter(isComplete).flatMap(match => [match.player1Id, match.player2Id])).size;
    const periodEligibility = eligibility(matches);
    detail.textContent = language === 'en' ? `Top 3 by category · ${participants} players · ${periodEligibility.text}` : `カテゴリ別 TOP 3 · ${participants}人 · ${periodEligibility.text}`;
    const avatar = player => `<figure class="monthly-avatar"><img src="img/${encodeURIComponent(player.playerId)}.jpg" alt=""></figure>`;
    content.innerHTML = `<div class="leaderboard-podiums">${categoryEntries.map(([category, entries]) => `<section class="category-podium"><button class="category-ranking-open" data-category="${category}">🏆 ${category}<small>${t('viewAllRankings')}</small></button>${entries.slice(0, 3).map((entry, index) => `<div><i>${rankIcon(index)}</i>${avatar(entry.player)}<b>${playerLink(entry.player)}</b>${recordSummary(entry.stats, matches, entry.player.playerId)}</div>`).join('')}</section>`).join('')}</div>`;
  }
}

// renderThreeMonthSummary and renderYearlySummary removed — logic moved to renderLeaderboardDashboard()

function openHeadToHead(matchId) {
  const match = data.matches.find(item => item.matchId === matchId); if (!match) return;
  const map = playerMap(), first = map.get(match.player1Id), second = map.get(match.player2Id);
  const history = data.matches.filter(item => (item.player1Id === match.player1Id && item.player2Id === match.player2Id) || (item.player1Id === match.player2Id && item.player2Id === match.player1Id)).sort((a,b) => b.matchDate.localeCompare(a.matchDate));
  const firstWins = history.filter(item => item.winnerId === match.player1Id).length;
  const outcomes = history.map(item => item.winnerId === match.player1Id ? 1 : item.winnerId === match.player2Id ? -1 : 0);
  document.querySelector('#head-to-head-content').innerHTML = `<p class="eyebrow">${phrase('h2h')}</p><button class="how-to-read h2h-help" data-help="h2h" aria-label="How to read Head to Head">?</button><div class="h2h-portraits"><figure><img src="img/${first.playerId}.jpg" alt="${nameFor(first)}" onerror="this.closest('figure').remove()"></figure><span>VS</span><figure><img src="img/${second.playerId}.jpg" alt="${nameFor(second)}" onerror="this.closest('figure').remove()"></figure></div><h2>${nameFor(first)} <em>${firstWins} - ${history.filter(item => item.winnerId === match.player2Id).length}</em> ${nameFor(second)}</h2><p class="h2h-meta">${phrase('h2hTimeline')}</p><div class="h2h-chart"><canvas id="h2h-chart"></canvas></div><div class="h2h-history">${history.map(item => `<div><span>${item.matchDate}</span><strong>${item.player1Name} ${item.player1Sets}-${item.player2Sets} ${item.player2Name}</strong></div>`).join('')}</div>`;
  new Chart(document.querySelector('#h2h-chart'), { type: 'bar', data: { labels: history.map(item => item.matchDate), datasets: [{ label: nameFor(first), data: outcomes, backgroundColor: outcomes.map(value => value > 0 ? '#d6a516' : value < 0 ? '#8c423a' : '#6e6a62'), borderRadius: 3 }] }, options: { plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#a5a198' }, grid: { display: false } }, y: { min: -1, max: 1, ticks: { color: '#a5a198', stepSize: 1, callback: value => value === 1 ? phrase('win') : value === -1 ? phrase('loss') : phrase('draw') }, grid: { color: 'rgba(246,240,226,.1)' } } } } });
  const setupFor = player => [[language === 'en' ? 'Style' : '戦型',player.playingStyle],[language === 'en' ? 'Grip' : 'グリップ',player.grip],[language === 'en' ? 'FH' : 'フォア',rubberName(player.forehandRubber)],[language === 'en' ? 'BH' : 'バック',rubberName(player.backhandRubber)]].filter(([,value]) => value).map(([label,value]) => `<span><b>${label}</b>${value}</span>`).join('') || `<span>${language === 'en' ? 'No setup data' : '用具情報なし'}</span>`; document.querySelector('#head-to-head-content').insertAdjacentHTML('beforeend', `<section class="h2h-setups"><p>${language === 'en' ? 'Player Setup Context' : '選手セッティング比較'}</p><div><article><b>${nameFor(first)}</b>${setupFor(first)}</article><article><b>${nameFor(second)}</b>${setupFor(second)}</article></div></section>`); document.querySelector('#head-to-head').showModal();
}

function renderClubInsights() {
  const target = document.querySelector('#club-insights-content'); if (!target) return;
  const completed = data.matches.filter(match => eventType(match) === 'training' && isComplete(match));
  const months = [...new Set(completed.map(match => match.matchDate.slice(0,7)))].sort().reverse();
  const latest = months[0], prior = months[1], forMonth = month => completed.filter(match => match.matchDate.startsWith(month));
  const latestMatches = latest ? forMonth(latest) : [], priorMatches = prior ? forMonth(prior) : [];
  const participants = list => new Set(list.flatMap(match => [match.player1Id, match.player2Id])).size;
  const close = list => list.filter(match => Math.abs(Number(match.player1Sets) - Number(match.player2Sets)) === 1).length;
  const playerStats = new Map(); latestMatches.forEach(match => [[match.player1Id, match.player1Sets, match.player2Sets], [match.player2Id, match.player2Sets, match.player1Sets]].forEach(([id, won, lost]) => { const entry = playerStats.get(id) || { wins:0, losses:0, opponents:new Set() }; entry.wins += match.winnerId === id ? 1 : 0; entry.losses += match.winnerId === id ? 0 : 1; entry.opponents.add(match.player1Id === id ? match.player2Id : match.player1Id); playerStats.set(id, entry); }));
  const mostActive = [...playerStats.entries()].sort(([,a],[,b]) => b.wins + b.losses - a.wins - a.losses).slice(0,5);
  const categories = ['SL-001','SL-002','SL-003','SL-004']; const matrix = new Map(); latestMatches.forEach(match => { const first = data.players.find(player => player.playerId === match.player1Id), second = data.players.find(player => player.playerId === match.player2Id); const a = first?.schoolLevel, b = second?.schoolLevel; if (!a || !b) return; const key = [a,b].sort().join('|'); matrix.set(key, (matrix.get(key) || 0) + 1); });
  const label = language === 'en' ? { title:'Activity & Competition', activity:'Latest month', players:'participants', close:'close matches', change:'vs previous month', active:'Most active this month', diversity:'unique opponents', category:'Category matchups', none:'No completed training matches yet' } : { title:'活動・対戦インサイト', activity:'直近月', players:'参加選手', close:'接戦', change:'前月比', active:'今月の試合数上位', diversity:'ユニーク対戦相手', category:'カテゴリ対戦', none:'完了した練習試合はまだありません' };
  if (!latest) { target.innerHTML = `<p class="empty">${label.none}</p>`; return; }
  const delta = latestMatches.length - priorMatches.length, deltaText = `${delta >= 0 ? '+' : ''}${delta}`;
  target.innerHTML = `<div class="insight-metrics"><article><small>${label.activity} · ${latest}</small><b>${latestMatches.length}</b><span>${t('matches')} · ${participants(latestMatches)} ${label.players}</span><em>${label.change} ${deltaText}</em></article><article><small>${label.close}</small><b>${close(latestMatches)}</b><span>${latestMatches.length ? Math.round(close(latestMatches) / latestMatches.length * 100) : 0}% · 3–2 / 2–3</span></article></div><div class="insight-grid"><section><h3>${label.active}</h3><ol>${mostActive.map(([id, stat]) => { const person = data.players.find(player => player.playerId === id); const games = stat.wins + stat.losses; return `<li><a class="player-link" href="player.html?id=${id}">${nameFor(person || { displayName:id })}</a><span>${games} ${t('matches')} · ${stat.opponents.size} ${label.diversity}</span></li>`; }).join('')}</ol></section><section><h3>${label.category}</h3><div class="category-matchup-matrix">${[...matrix.entries()].sort((a,b) => b[1] - a[1]).map(([key,count]) => `<span><b>${key.split('|').map(value => lookupValue('schoolLevel', value)).join(' × ')}</b><i>${count}</i></span>`).join('') || '-'}</div></section></div>`;
}

function render() {
  document.documentElement.lang = language;
  document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
  document.querySelectorAll('[data-i18n-aria]').forEach(element => element.setAttribute('aria-label', t(element.dataset.i18nAria)));
  document.querySelectorAll('[data-i18n-alt]').forEach(element => element.alt = t(element.dataset.i18nAlt));
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element => element.placeholder = t(element.dataset.i18nPlaceholder));
  document.querySelector('#internal-notice').innerHTML = language === 'en' ? '<p class="eyebrow">IMPORTANT NOTICE</p><h2>Important Notice</h2><div class="notice-grid"><article><b>01 <span>Internal Use Only</span></b><p>Do not share this site or its password with anyone outside the Little Kings Family. The password is changed regularly and circulated internally to the Little Kings Family. Use and share only your own data, and never share another player\'s data without their consent.</p></article><article><b>02 <span>Data Guidance</span></b><p>Win percentages and rankings are for reference only. They reflect many factors, including opponents, match volume, and condition on the day. They do not define whether a player is good or bad. Use the match log to review training, identify improvements, and keep growing.</p></article><article><b>03 <span>Update Your Profile</span></b><p>To update your equipment, playing style, or other profile information, visit the <a href="admin.html">Data Maintenance</a> page and submit your changes. Changes will take effect only after a Data Approver reviews and approves them.</p></article></div>' : '<p class="eyebrow">重要なお知らせ</p><h2>重要なお知らせ</h2><div class="notice-grid"><article><b>01 <span>内部利用限定</span></b><p>このサイトとパスワードは、リトルキングスファミリー以外の方へ共有しないでください。パスワードは定期的に変更され、リトルキングスファミリー内でご案内します。ご自身のデータのみを利用・共有し、他の選手のデータは本人の同意なく共有しないでください。</p></article><article><b>02 <span>データについて</span></b><p>勝率やランキングは、対戦相手、試合数、その日のコンディションなど多くの要因による参考情報です。選手の良し悪しを判断するものではありません。この記録は、練習試合を振り返り、改善点を見つけて次の成長につなげるためのものです。</p></article><article><b>03 <span>プロフィールの更新</span></b><p>用具、プレースタイル、その他プロフィール情報の更新は、<a href="admin.html">データメンテナンス</a>ページから申請してください。変更はデータ承認者による確認・承認後に反映されます。</p></article></div>';
  document.querySelector('#language-toggle').textContent = language === 'en' ? '日本語' : 'ENGLISH';
  const tournamentNav = document.querySelector('#nav-tournaments'), maintenanceNav = document.querySelector('#nav-maintenance');
  if (tournamentNav) tournamentNav.textContent = language === 'en' ? 'Tournaments' : '大会';
  if (maintenanceNav) maintenanceNav.textContent = language === 'en' ? 'Data Maintenance' : 'データメンテナンス';
  document.querySelector('#session-timeline-title').textContent = phrase('matchDayVolume'); document.querySelector('#menu-toggle').textContent = '☰'; document.querySelector('#menu-toggle').setAttribute('aria-label', phrase('menu'));
  document.querySelector('#player-search').placeholder = language === 'en' ? 'Search players' : '選手を検索';
  const matches = visibleMatches(), ranked = rankPlayers(matches), dates = matches.map(match => match.matchDate).filter(Boolean).sort();
  charts.forEach(chart => chart.destroy()); charts = [];
  document.querySelector('#player-count').textContent = data.players.length;
  renderPlayers(ranked); renderGroupStats(matches); renderLatestSession(); renderClubInsights(); renderLeaderboardDashboard(); renderSession();
  const heroSearch = document.querySelector('#hero-player-search'); if (heroSearch && heroSearch.value.trim()) renderHeroPlayerResults(heroSearch.value.trim().toLowerCase());
  document.querySelector('#last-updated').textContent = `${t('lastUpdated')}: ${new Date(data.lastUpdated).toLocaleString(language === 'ja' ? 'ja-JP' : 'en-GB')}`;
  const latestMatchDate = data.matches.map(match => match.matchDate).filter(Boolean).sort().at(-1); document.querySelector('#match-data-status').textContent = latestMatchDate ? (language === 'en' ? `Latest match data: ${dateLabel(latestMatchDate)}` : `最新試合データ: ${dateLabel(latestMatchDate)}`) : (language === 'en' ? 'No match data recorded' : '試合データはありません');
}

document.querySelector('#language-toggle').onclick = () => { language = language === 'en' ? 'ja' : 'en'; localStorage.setItem('lk-language', language); render(); };
document.querySelector('#menu-toggle').onclick = event => { const menu = document.querySelector('nav'); const open = menu.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', open); };
document.querySelector('nav').onclick = event => { if (event.target.matches('a')) { document.querySelector('nav').classList.remove('open'); document.querySelector('#menu-toggle').setAttribute('aria-expanded', 'false'); } };
document.querySelector('#player-search').oninput = () => renderPlayers(rankPlayers());
document.querySelector('#hero-player-search').oninput = event => renderHeroPlayerResults(event.target.value.trim().toLowerCase());
// Leaderboard controls use one delegated handler so they remain reliable across redraws and touch browsers.
document.addEventListener('click', event => {
  const tab = event.target.closest('.leaderboard-tab');
  if (tab) {
    event.preventDefault();
    leaderboardView = tab.dataset.view;
    renderLeaderboardDashboard();
    return;
  }
  const direction = event.target.closest('#leaderboard-prev, #leaderboard-next');
  if (!direction || direction.disabled) return;
  event.preventDefault();
  const older = direction.id === 'leaderboard-prev';
  if (leaderboardView === 'month') recentStart += older ? 1 : -1;
  else leaderboardYearIndex += older ? 1 : -1;
  renderLeaderboardDashboard();
});
function renderHeroPlayerResults(query) {
  const labels = language === 'en' ? { displayName:'Display Name', englishName:'ローマ字表記 / Romanized name', id:'Player ID', category:'Category', gender:'Gender', handStyle:'Hand / Style', grip:'Grip', games:'Completed Games', record:'W / L', rate:'Win %', empty:'No players found' } : { displayName:'表示名', englishName:'ローマ字表記 / Romanized name', id:'選手ID', category:'カテゴリ', gender:'性別', handStyle:'利き手 / 戦型', grip:'グリップ', games:'完了試合数', record:'勝 / 負', rate:'勝率', empty:'該当する選手がいません' };
  const stats = playerStats(data.matches), results = data.players.filter(player => `${player.playerId} ${player.displayName} ${player.englishName || ''}`.toLowerCase().includes(query)).slice(0,8);
  document.querySelector('#hero-player-results').innerHTML = results.map(player => {
    const record = stats.get(player.playerId) || { wins:0, losses:0 }, games = record.wins + record.losses, rate = games ? Math.round(record.wins / games * 100) : 0;
    const details = [[labels.category,lookupValue('schoolLevel',player.schoolLevel)],[labels.gender,player.gender],[labels.handStyle,[player.playingHand,player.playingStyle].filter(Boolean).join(' / ')],[labels.grip,player.grip]].filter(([,value]) => value);
    return `<a class="hero-player-card" href="player.html?id=${encodeURIComponent(player.playerId)}"><figure class="hero-player-portrait"><img src="img/${encodeURIComponent(player.playerId)}.jpg" alt="${escapeHtml(player.displayName || player.englishName || player.playerId)}"></figure><div class="hero-player-card-main"><div class="hero-player-names"><span><small>${labels.displayName}</small><b>${escapeHtml(player.displayName || '-')}</b></span><span><small>${labels.englishName}</small><b>${escapeHtml(player.englishName?.toUpperCase() || '-')}</b></span></div><div class="hero-player-profile"><span><b>${labels.id}</b>${escapeHtml(player.playerId || '-')}</span>${details.map(([label,value]) => `<span><b>${label}</b>${escapeHtml(value)}</span>`).join('')}</div><div class="hero-player-record"><span><b>${labels.games}</b>${games}</span><span><b>${labels.record}</b>${record.wins} / ${record.losses}</span><span><b>${labels.rate}</b>${rate}%</span></div></div></a>`;
  }).join('') || `<p class="hero-player-empty">${labels.empty}</p>`;
}
const howToRead = {
  yearly: { en: { title:'How to Read the Yearly Leaderboard', intro:'Rankings compare players within the same category for the selected year.', points:['Check eligibility first: a player needs one completed match for every recorded match day that year.','Win rate is most useful alongside the W/L total and number of games. A strong rate from fewer matches is a smaller sample.','Use the opponent-category record to understand where results were earned. Different opponent pools create different challenges.','Treat the table as a review tool, not a judgement of player quality. Look for training priorities, not labels.'] }, ja: { title:'年間リーダーボードの見方', intro:'選択した年の同じカテゴリ内で順位を比較しています。', points:['まず対象条件を確認します。その年のすべての試合日に、完了試合を1試合以上行う必要があります。','勝率は勝敗数と試合数と合わせて確認します。試合数が少ない高勝率は、判断材料がまだ少ない場合があります。','対戦相手カテゴリ別の勝敗を見ると、どの相手層との結果かを理解できます。対戦相手の構成によって難易度は変わります。','順位は選手の良し悪しを決めるものではありません。次の練習課題を見つけるために活用してください。'] } },
  monthly: { en: { title:'How to Read the Monthly Leaderboard', intro:'This view is a short-term training snapshot for each displayed month.', points:['Eligibility is a total of at least 2 × the number of match days in that month.','Compare a month with the previous month to spot changes in consistency, participation, and win rate.','Read W/L and opponent-category records together. A lower rate against a stronger or unfamiliar group can still reveal useful progress.','Use the result to set one practical next focus, such as serve receive, third-ball attack, or closing close games.'] }, ja: { title:'月間リーダーボードの見方', intro:'表示月ごとの短期的な練習状況を確認するための一覧です。', points:['対象条件は、その月の試合日数 × 2試合以上の合計完了試合数です。','前月と比べて、安定感、参加状況、勝率の変化を確認してください。','勝敗と対戦相手カテゴリ別の記録を合わせて見ます。強い相手や慣れない相手が多い月は、勝率が低くても有意義な成長が見える場合があります。','サーブレシーブ、3球目攻撃、接戦の締め方など、次の練習テーマを1つ決めるために使ってください。'] } },
  volume: { en: { title:'How to Read Match-Day Volume', intro:'The chart shows how much competitive practice happened on each training day.', points:['Blue bars show participating players. The gold line shows completed and recorded matches.','More matches create more repetition and feedback, but volume alone does not measure quality.','Look for days with many matches and revisit those session results to identify recurring score patterns or difficult opponents.','Combine volume with win rate, score lines, and your own match notes before changing training priorities.'] }, ja: { title:'試合日別試合数の見方', intro:'各練習日に、どれだけ実戦形式の練習が行われたかを示すグラフです。', points:['青い棒は参加選手数、金色の線は記録された完了試合数です。','試合数が多いほど反復と振り返りの機会は増えますが、量だけで練習の質は判断できません。','試合数が多い日の結果を見直し、繰り返し出るスコア傾向や苦手な相手を確認してください。','練習テーマを変える前に、試合数、勝率、スコア、自分のメモを合わせて判断してください。'] } },
  sessions: { en: { title:'How to Read Session Replay', intro:'Choose a training date to review the individual matches played that day.', points:['Read the score, result, and opponent together. A 3-2 result contains different information from a 3-0 result.','Close losses can point to decision-making under pressure, serve/receive quality, or the final-ball pattern.','Incomplete matches are shown for the record but are excluded from performance statistics and rankings.','After reviewing a session, write down one successful pattern and one situation to practise next time.'] }, ja: { title:'練習日リプレイの見方', intro:'練習日を選ぶと、その日に行われた個別の試合を振り返れます。', points:['スコア、結果、対戦相手を一緒に確認してください。3-2の試合と3-0の試合では、得られる情報が異なります。','接戦での敗戦は、プレッシャー下の判断、サーブレシーブ、終盤の得点パターンなどの課題を示すことがあります。','未完了試合は記録として表示されますが、成績やランキングの集計には含まれません。','振り返った後、うまくできたパターンを1つ、次回練習する場面を1つ書き出してください。'] } },
  players: { en: { title:'How to Use Player Profiles', intro:'Select a player to see their training record, trends, opponent matchups, and available playing information.', points:['Use the match timeline to see consistency over several training days, rather than reacting to one result.','Opponent insights help identify repeated matchups and whether adjustments are needed in tactics or preparation.','Equipment and playing-style details are reference information for understanding a player, not a prescription for changing gear.','Discuss patterns with the player and coach, then turn the review into a small, measurable practice goal.'] }, ja: { title:'選手プロフィールの活用方法', intro:'選手を選ぶと、練習記録、成績推移、対戦相手との記録、登録済みのプレー情報を確認できます。', points:['1試合の結果だけで判断せず、複数の練習日にわたる推移から安定感を確認してください。','対戦相手分析では、繰り返し対戦する相手や、戦術・準備の見直しが必要な組み合わせを確認できます。','用具やプレースタイルの情報は選手を理解するための参考です。すぐに用具変更を勧めるためのものではありません。','選手とコーチで傾向を話し合い、小さく測定可能な練習目標に変えてください。'] } }
};
howToRead.h2h = { en: { title:'How to Read Head to Head', intro:'This view compares only the two selected players across their recorded meetings.', points:['The bars show the result of each match in time order: win, loss, or draw.','Read the score list with the timeline. Repeated close losses and repeated one-sided losses suggest different training questions.','Use the history to identify one matchup-specific focus, such as serve placement, receive choice, first attack, or rally pattern.','A Head-to-Head record is a tactical review tool, not a fixed measure of either player’s level.'] }, ja: { title:'直接対決の見方', intro:'選択した2選手の記録済み対戦だけを比較する画面です。', points:['棒は時系列の各試合結果を示し、勝ち・負け・引分を確認できます。','スコア一覧とタイムラインを合わせて見ます。接戦の敗戦が続く場合と一方的な敗戦が続く場合では、考える練習課題が異なります。','サーブのコース、レシーブの選択、先手の取り方、ラリーのパターンなど、対戦相手別の課題を1つ決めてください。','直接対決の記録は戦術を振り返るためのものであり、選手の実力を固定的に決めるものではありません。'] } };
 document.addEventListener('click', event => { const button = event.target.closest('.how-to-read'); if (!button) return; const content = howToRead[button.dataset.help]?.[language]; if (!content) return; const parentDialog = button.closest('dialog'); if (parentDialog && parentDialog.id !== 'how-to-read-dialog') { let panel = parentDialog.querySelector('.inline-how-to-read'), exists = Boolean(panel); if (!panel) { panel = document.createElement('section'); panel.className = 'inline-how-to-read'; parentDialog.querySelector('[id$="-content"]').append(panel); } panel.innerHTML = `<b>${content.title}</b><p>${content.intro}</p><ul>${content.points.map(point => `<li>${point}</li>`).join('')}</ul>`; panel.hidden = exists ? !panel.hidden : false; return; } document.querySelector('#how-to-read-content').innerHTML = `<p class="eyebrow">${language === 'en' ? 'HOW TO READ' : '見方'}</p><h2>${content.title}</h2><p>${content.intro}</p><ul>${content.points.map(point => `<li>${point}</li>`).join('')}</ul>`; document.querySelector('#how-to-read-dialog').showModal(); });
document.addEventListener('click', event => { const card = event.target.closest('.match-card'); if (card?.dataset.matchId) { const match = data.matches.find(item => item.matchId === card.dataset.matchId); if (match) location.href = `player.html?id=${match.player1Id}&opponent=${match.player2Id}`; } if (event.target.closest('.modal-close')) document.querySelectorAll('dialog[open]').forEach(dialog => dialog.close()); const categoryButton = event.target.closest('.category-ranking-open'); if (categoryButton && !categoryButton.dataset.month) { const category = categoryButton.dataset.category, entries = categoryLeaderboardEntries.get(category) || [], title = language === 'en' ? `${categoryLeaderboardYear} ${category} Rankings` : `${categoryLeaderboardYear}年 ${category} 順位`, winLabel = language === 'en' ? 'W' : '勝', lossLabel = language === 'en' ? 'L' : '負'; document.querySelector('#category-leaderboard-content').innerHTML = `<p class="eyebrow">${language === 'en' ? 'YEARLY CATEGORY RANKING' : '年間カテゴリ順位'}</p><button class="how-to-read h2h-help" data-help="yearly" aria-label="${language === 'en' ? 'How to read category rankings' : 'カテゴリ順位の見方'}">?</button><h2>${title}</h2><ol>${entries.map((entry,index) => { const games = entry.stats.wins + entry.stats.losses, rate = Math.round(entry.stats.wins / games * 100), categories = opponentCategoryBreakdown(categoryLeaderboardMatches, entry.player.playerId).replace(/\n/g, ' · '); return `<li><i>${rankIcon(index)}</i><a class="player-link" href="player.html?id=${entry.player.playerId}">${nameFor(entry.player)}</a><b>${rate}%</b><span>${winLabel}${entry.stats.wins} · ${lossLabel}${entry.stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</span><span class="leader-category-records">${categories}</span></li>`; }).join('')}</ol>`; document.querySelector('#category-leaderboard').showModal(); } });
document.addEventListener('click', event => { const button = event.target.closest('.category-ranking-open[data-month]'); if (!button) return; const category = button.dataset.category, month = button.dataset.month, entries = monthlyCategoryEntries.get(`${month}|${category}`) || [], matches = monthlyCategoryMatches.get(`${month}|${category}`) || [], title = language === 'en' ? `${month} ${category} Rankings` : `${month} ${category} 順位`, winLabel = language === 'en' ? 'W' : '勝', lossLabel = language === 'en' ? 'L' : '負'; document.querySelector('#category-leaderboard-content').innerHTML = `<p class="eyebrow">${language === 'en' ? 'MONTHLY CATEGORY RANKING' : '月間カテゴリ順位'}</p><button class="how-to-read h2h-help" data-help="monthly" aria-label="${language === 'en' ? 'How to read category rankings' : 'カテゴリ順位の見方'}">?</button><h2>${title}</h2><ol>${entries.map((entry,index) => { const games = entry.stats.wins + entry.stats.losses, rate = Math.round(entry.stats.wins / games * 100), categories = opponentCategoryBreakdown(matches, entry.player.playerId).replace(/\n/g, ' · '); return `<li><i>${rankIcon(index)}</i><a class="player-link" href="player.html?id=${entry.player.playerId}">${nameFor(entry.player)}</a><b>${rate}%</b><span>${winLabel}${entry.stats.wins} · ${lossLabel}${entry.stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</span><span class="leader-category-records">${categories}</span></li>`; }).join('')}</ol>`; document.querySelector('#category-leaderboard').showModal(); });
document.addEventListener('click', event => { const button = event.target.closest('.category-ranking-open'); if (!button) return; const matches = button.dataset.month ? monthlyCategoryMatches.get(`${button.dataset.month}|${button.dataset.category}`) || [] : categoryLeaderboardMatches; document.querySelectorAll('#category-leaderboard-content li').forEach(item => { const playerId = item.querySelector('a')?.href.match(/[?&]id=([^&]+)/)?.[1]; item.querySelector('.leader-category-records')?.remove(); if (playerId) item.insertAdjacentHTML('beforeend', opponentCategoryDistribution(matches, playerId)); }); });
const addYearlyAvatars = () => { const dialog = document.querySelector('#category-leaderboard-content'), isYearlyDialog = dialog.querySelector('.eyebrow')?.textContent.includes(language === 'en' ? 'YEARLY' : '年間'); const links = [...document.querySelectorAll('#leaderboard-content .player-link'), ...(isYearlyDialog ? dialog.querySelectorAll('.player-link') : [])]; links.filter(link => { if (link.classList.contains('yearly-avatar-missing')) return false; const parent = link.closest('b') || link.parentElement, hasAvatar = link.previousElementSibling?.matches('.yearly-avatar, .monthly-avatar') || parent?.previousElementSibling?.matches('.yearly-avatar, .monthly-avatar'); return !hasAvatar; }).forEach(link => { const playerId = new URL(link.href).searchParams.get('id'); if (!playerId) return; const portrait = document.createElement('figure'), image = document.createElement('img'); portrait.className = 'yearly-avatar'; image.src = `img/${encodeURIComponent(playerId)}.jpg`; image.alt = ''; image.onerror = () => { link.classList.add('yearly-avatar-missing'); portrait.remove(); }; portrait.append(image); link.before(portrait); }); };
new MutationObserver(addYearlyAvatars).observe(document.body, { childList:true, subtree:true });
 document.addEventListener('click', event => { const row = event.target.closest('#player-setup-distribution .setup-row'); if (!row) return; const section = row.closest('section'), fields = ['playingStyle','grip','forehandRubberType','backhandRubberType'], field = fields[[...section.parentElement.children].indexOf(section)], value = row.querySelector('span')?.getAttribute('title'), members = data.players.filter(player => lookupValue(field, player[field]) === value); if (members.length) openActivePlayerList(value, members); });
window.LKData.loadPublicData().then(result => { data = result; render(); }).catch(() => document.querySelectorAll('.loading').forEach(element => { element.textContent = t('loadError'); }));
