const API_URL = 'https://script.google.com/macros/s/AKfycbx6IaN9YT2a4bv_8W76qtNwkFCjZ_-mODBEMTK9IiJlSi91UCIgJ56MQ4WJqeKK3TiUvA/exec?action=publicData';
Chart.defaults.layout.padding = { top: 18, right: 8, bottom: 0, left: 0 };
Chart.register({ id: 'valueLabels', afterDatasetsDraw(chart) { const { ctx } = chart, isWinRate = chart.canvas.id === 'wins-chart'; if (chart.canvas.id === 'session-timeline-chart' && window.matchMedia('(max-width: 760px)').matches) return; ctx.save(); ctx.fillStyle = isWinRate ? '#090a0b' : '#f6f0e2'; ctx.font = '700 11px Barlow Condensed'; ctx.textAlign = 'center'; chart.data.datasets.forEach((dataset, datasetIndex) => chart.getDatasetMeta(datasetIndex).data.forEach((element, index) => { const value = dataset.data[index]; if (value === null || value === undefined) return; const point = element.tooltipPosition(), isBar = chart.getDatasetMeta(datasetIndex).type === 'bar', horizontalBar = isBar && chart.options.indexAxis === 'y', label = isWinRate ? `${value}%` : Math.abs(value); ctx.fillText(label, horizontalBar ? (element.x + element.base) / 2 : point.x, isBar ? (horizontalBar ? point.y + 4 : (element.y + element.base) / 2 + 4) : point.y - 8); })); ctx.restore(); } });
let data = { players: [], matches: [] }, selectedMonth = 'all', selectedYear = 'all', selectedSession = '', calendarMonth = '', recentStart = 0, leaderboardYearIndex = 0, categoryLeaderboardEntries = new Map(), categoryLeaderboardYear = '', categoryLeaderboardMatches = [], monthlyCategoryEntries = new Map(), monthlyCategoryMatches = new Map(), charts = [];
let language = localStorage.getItem('lk-language') || 'ja';
const words = {
  en: { navPlayers:'Players',navMatches:'Matches',navStats:'Statistics',navSessions:'Sessions',navSurvey:'Player Profile Supplement',eyebrow:'CLUB TRAINING MATCH GAME LOG',heroDescription:'Every point. Every player. One club.',viewResults:'View match results',matchesPlayed:'Matches played',activePlayers:'Active players',latestResult:'Latest result',winsLeader:'Wins leader',sectionStatsKicker:'THE NUMBERS',sectionStats:'Club Training Statistics',rankingTitle:'Win Rankings',minimumMatches:'Min. 3 matches',sectionMatchesKicker:'CLUB TRAINING GAME LOG',sectionMatches:'Training Match Results',sectionPlayersKicker:'THE SQUAD',sectionPlayers:'Players',sessionKicker:'TRAINING LOG',sessionTitle:'Session Replay',allResults:'All results',training:'Training',tournament:'Tournament',incomplete:'Incomplete',trainingYear:'Training year',trainingMonth:'Training month',winsChart:'Win Rate Leaders',formatChart:'Score Breakdown',groupKicker:'SQUAD BREAKDOWN',groupTitle:'Group Statistics',categoryStats:'Player Category',genderStats:'Gender',threeMonthKicker:'RECENT FORM',threeMonthTitle:'Monthly Leaderboard',monthLeader:'Month leader',yearLeader:'Year leader',gamesPlayed:'games played',participated:'participated',unassigned:'Unassigned',loading:'Loading live data...',updating:'Live data',lastUpdated:'Last updated',officialSite:'Official club website',matches:'matches',players:'players',noSessions:'No training sessions found' },
  ja: { navPlayers:'選手',navMatches:'試合結果',navStats:'スタッツ',navSessions:'練習日',navSurvey:'選手プロフィール補足情報',eyebrow:'クラブ練習試合ゲームログ',heroDescription:'すべてのポイント。すべての選手。ひとつのクラブ。',viewResults:'試合結果を見る',matchesPlayed:'試合数',activePlayers:'登録選手',latestResult:'最新試合日',winsLeader:'最多勝',sectionStatsKicker:'数字で見る',sectionStats:'クラブ練習スタッツ',rankingTitle:'勝利ランキング',minimumMatches:'最低3試合',sectionMatchesKicker:'クラブ練習ゲームログ',sectionMatches:'練習試合結果',sectionPlayersKicker:'選手紹介',sectionPlayers:'選手',sessionKicker:'練習ログ',sessionTitle:'練習日リプレイ',allResults:'すべて',training:'クラブ練習',tournament:'大会',incomplete:'未完了',trainingYear:'練習年',trainingMonth:'練習月',winsChart:'勝率ランキング',formatChart:'スコア内訳',groupKicker:'グループ別',groupTitle:'グループスタッツ',categoryStats:'区分別',genderStats:'性別',threeMonthKicker:'直近の成績',threeMonthTitle:'月間リーダーボード',monthLeader:'月間リーダー',yearLeader:'年間リーダー',gamesPlayed:'試合',participated:'参加',unassigned:'未設定',loading:'データを読み込んでいます...',updating:'ライブデータ',lastUpdated:'最終更新',officialSite:'公式クラブサイト',matches:'試合',players:'選手',noSessions:'練習記録がありません' }
};
const t = key => words[language][key];
document.addEventListener('mouseover', event => { const dot = event.target.closest('.game-result-dot'); if (!dot) return; const card = dot.closest('.match-card'); if (card) dot.title = card.innerText.replace(/\s+/g, ' ').trim(); });
const nameFor = player => language === 'en' && player.englishName ? `${player.displayName} | ${player.englishName.toUpperCase()}` : player.displayName;
const recordText = (wins, losses, games = wins + losses) => language === 'en' ? `${wins}W-${losses}L · ${games}G` : `${wins}勝-${losses}負 · ${games}試合`;
const dateLabel = date => `${date} · ${new Date(`${date}T00:00:00`).toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}`;
const playerLink = player => `<a class="player-link" href="player.html?id=${player.playerId}">${nameFor(player)}</a>`;
const resultDots = (matches, playerId) => { const playerMatches = matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)), wins = playerMatches.filter(match => match.winnerId === playerId).length, losses = playerMatches.length - wins, winLabel = language === 'ja' ? '勝' : 'W', lossLabel = language === 'ja' ? '負' : 'L'; return `<aside class="match-result-dots"><i class="win">${winLabel}</i><b>${wins}</b><i class="loss">${lossLabel}</i><b>${losses}</b></aside>`; };
const opponentCategoryBreakdown = (matches, playerId) => { const records = new Map(); matches.filter(match => isComplete(match) && (match.player1Id === playerId || match.player2Id === playerId)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, category = data.players.find(player => player.playerId === opponentId)?.schoolLevel || (language === 'en' ? 'Unassigned' : '未設定'), record = records.get(category) || { wins:0, losses:0 }; if (match.winnerId === playerId) record.wins++; else record.losses++; records.set(category,record); }); return sortCategories([...records.entries()]).map(([category,record]) => `${category}: ${language === 'en' ? 'W' : '勝'} ${record.wins} · ${language === 'en' ? 'L' : '負'} ${record.losses}`).join('\n'); };
const recordSummary = (stats, matches, playerId) => { const games = stats.wins + stats.losses, rate = Math.round(stats.wins / games * 100), winLabel = language === 'ja' ? '勝' : 'W', lossLabel = language === 'ja' ? '負' : 'L', categories = opponentCategoryBreakdown(matches, playerId); return `<span class="leader-record"><b class="${rate >= 50 ? 'positive' : 'negative'}" title="${categories}">${rate}%</b><small><i class="win">${winLabel}</i> ${stats.wins} <i class="loss">${lossLabel}</i> ${stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</small><em class="leader-category-records">${categories.replace(/\n/g,' · ')}</em></span>`; };
const isComplete = match => Number(match.player1Sets) >= 3 || Number(match.player2Sets) >= 3;
const eligibility = (matches, matchesPerDay = 1) => { const gameDays = new Set(matches.filter(isComplete).map(match => match.matchDate)).size, minimum = gameDays * matchesPerDay; return { minimum, gameDays, text: language === 'en' ? `Eligibility: ${matchesPerDay} completed match${matchesPerDay === 1 ? '' : 'es'} for every match day in the selected period.` : `対象: 選択期間内のすべての試合日につき${matchesPerDay}試合。` }; };
const minimumText = minimum => language === 'en' ? `min. ${minimum}` : `最低${minimum}試合`;
const categoryOrder = ['小学生', '中学生', '高校生', '一般'];
const sortCategories = entries => entries.sort(([left], [right]) => { const index = category => category === t('unassigned') || category === 'Unassigned' ? 98 : categoryOrder.includes(category) ? categoryOrder.indexOf(category) : 97; return index(left) - index(right) || left.localeCompare(right, 'ja'); });
const isAssignedCategory = category => category && category !== t('unassigned') && category !== 'Unassigned';
const categoryLeaders = () => language === 'en' ? 'Category leaders' : 'カテゴリ首位';
const rankIcon = index => ['🥇', '🥈', '🥉'][index] || `${index + 1}`;
const phrase = key => ({ matchDays: language === 'en' ? 'match days' : '試合日', since: language === 'en' ? 'Since' : '集計開始', yearKicker: language === 'en' ? 'YEAR IN REVIEW' : '年間成績', yearTitle: language === 'en' ? 'Yearly Leaderboard' : '年間リーダーボード', selectYear: language === 'en' ? 'Select year' : '年を選択', trainingLog: language === 'en' ? 'CLUB TRAINING MATCH GAME LOG' : 'クラブ練習試合ゲームログ', matchDayVolume: language === 'en' ? 'Match-Day Volume' : '試合日別試合数', menu: language === 'en' ? 'MENU' : 'メニュー', h2h: language === 'en' ? 'HEAD TO HEAD' : '直接対決', h2hTimeline: language === 'en' ? 'Newest to oldest · Win / Draw / Loss timeline' : '新しい順 · 勝ち / 引分 / 負け タイムライン', win: language === 'en' ? 'WIN' : '勝ち', loss: language === 'en' ? 'LOSS' : '負け', draw: language === 'en' ? 'DRAW' : '引分' })[key];
const clubIntroduction = () => language === 'en' ? `<p class="eyebrow">KANAGAWA · JAPAN</p><h2>Welcome to <em>Little Kings</em></h2><p>Little Kings is a table tennis club based in Kanagawa, Japan, primarily for elementary and junior-high school students. We are accepting new members and welcome visits, free trial sessions, and enquiries at any time.</p><p>Guided by the principle of <strong>Sottaku</strong>, we support members from Grade 1 through Grade 12. Beginners and players with no previous experience are welcome: we teach the fundamentals step by step, at each player’s own level and toward their own goals.</p><h3>Grow Through Table Tennis</h3><p>We help each player develop their individual strengths while valuing growth, cooperation, and independence. Training balances enjoyment and improvement with play-based elements, alongside manners, respect for opponents, and respect for the rules. Through matches and exchanges with many people, our members learn to participate with confidence, kindness, and energy.</p><p class="club-intro-close">Why not take on the challenge with Little Kings?</p><aside class="club-contact"><b>CONTACT</b><span>Phone <a href="tel:09015555060">090-1555-5060</a></span><span>Email <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span></aside><aside class="club-instagram"><b>FOLLOW OUR ACTIVITY</b><p>See Little Kings’ latest training and club activity on Instagram.</p><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram <span>@ritokin.ryumon</span></a></aside>` : `<p class="eyebrow">KANAGAWA · JAPAN</p><h2><em>リトルキングス</em>へようこそ</h2><p>神奈川県を拠点に活動する、小学生・中学生を中心とした卓球クラブチーム、リトルキングスの公式ホームページへようこそ。</p><p>新規会員を募集しています。見学・無料体験・お問い合わせは随時受け付けています。お気軽にご連絡ください。</p><h3>「啐啄」の理念</h3><p>リトルキングスは「啐啄」を理念に掲げ、小学1年生から高校3年生までが所属しています。未経験の方や初心者の方にも、基礎から一人ひとりのレベルや目標に合わせて丁寧に指導します。</p><h3>卓球を通した成長</h3><p>卓球を通して個々の才能を伸ばし、子どもたちの成長・協調性・自立心を大切にしています。楽しさと上達を両立するために遊びの要素も取り入れながら、試合や交流の場では礼儀やマナー、相手への敬意、ルールを守ることの大切さを学びます。</p><p>多様な人との交流を通じて、子どもたちが「明るく、楽しく、元気よく」成長できるクラブを目指しています。</p><p class="club-intro-close">リトルキングスで一緒に頑張ってみませんか！</p><aside class="club-contact"><b>お問い合わせ</b><span>電話 <a href="tel:09015555060">090-1555-5060</a></span><span>メール <a href="mailto:mmr0518@icloud.com">mmr0518@icloud.com</a></span></aside><aside class="club-instagram"><b>最新の活動状況はInstagramにて！</b><p>リトルキングスのInstagramをぜひご覧ください。</p><a href="https://www.instagram.com/ritokin.ryumon/" target="_blank" rel="noreferrer">Instagram <span>@ritokin.ryumon</span></a></aside>`;
const eventType = match => /club|training|練習/i.test(`${match.event} ${match.division}`) ? 'training' : 'tournament';
const visibleMatches = () => data.matches.filter(match => eventType(match) === 'training' && (selectedYear === 'all' || match.matchDate.startsWith(selectedYear)) && (selectedMonth === 'all' || match.matchDate.startsWith(selectedMonth)));
const playerMap = () => new Map(data.players.map(player => [player.playerId, player]));

function playerStats(matches = visibleMatches()) {
  const stats = new Map(data.players.map(player => [player.playerId, { wins: 0, losses: 0, setsFor: 0, setsAgainst: 0 }]));
  matches.filter(isComplete).forEach(match => {
    [[match.player1Id, match.player1Sets, match.player2Sets], [match.player2Id, match.player2Sets, match.player1Sets]].forEach(([id, won, lost]) => {
      const record = stats.get(id);
      if (!record) return;
      record.setsFor += won; record.setsAgainst += lost;
      if (match.winnerId === id) record.wins++; else record.losses++;
    });
  });
  return stats;
}

function rankPlayers(matches = visibleMatches()) {
  const stats = playerStats(matches);
  return data.players.map(player => ({ player, stats: stats.get(player.playerId) })).sort((a, b) => { const ap = a.stats.wins + a.stats.losses, bp = b.stats.wins + b.stats.losses; const ar = ap ? a.stats.wins / ap : 0, br = bp ? b.stats.wins / bp : 0; return br - ar || bp - ap || b.stats.wins - a.stats.wins; });
}

function matchCard(match, players) {
  const first = players.get(match.player1Id) || { displayName: match.player1Name };
  const second = players.get(match.player2Id) || { displayName: match.player2Name };
  const firstResult = match.winnerId === match.player1Id ? 'win' : match.winnerId === match.player2Id ? 'loss' : '', secondResult = match.winnerId === match.player2Id ? 'win' : match.winnerId === match.player1Id ? 'loss' : '', dot = result => result ? `<i class="game-result-dot ${result}" title="${t(result)}">${result === 'win' ? 'W' : 'L'}</i>` : ''; return `<button class="match-card" data-match-id="${match.matchId}"><div class="match-meta"><span>${dateLabel(match.matchDate)}</span><span class="badge ${eventType(match)}">${t(eventType(match))}</span></div><div class="match-score"><span class="match-player ${firstResult === 'win' ? 'winner' : firstResult === 'loss' ? 'loser' : ''}">${dot(firstResult)}${nameFor(first)}${first.schoolLevel ? `<small class="match-category">${first.schoolLevel}</small>` : ''}</span><strong class="score">${match.player1Sets} <i>:</i> ${match.player2Sets}</strong><span class="match-player ${secondResult === 'win' ? 'winner' : secondResult === 'loss' ? 'loser' : ''}">${dot(secondResult)}${nameFor(second)}${second.schoolLevel ? `<small class="match-category">${second.schoolLevel}</small>` : ''}</span></div><div class="match-context"><span>${match.event || 'Little Kings'}</span><b>${!isComplete(match) ? t('incomplete') : ''}</b></div></button>`;
}


function renderSession() {
  const dates = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate))].sort().reverse();
  if (!dates.length) { document.querySelector('#session-summary').textContent = t('noSessions'); return; }
  if (!dates.includes(selectedSession)) selectedSession = dates[0];
  if (!calendarMonth) calendarMonth = selectedSession.slice(0, 7);
  renderCalendar(dates);
  const chronologicalDates = [...dates].reverse(), counts = chronologicalDates.map(date => data.matches.filter(match => match.matchDate === date && eventType(match) === 'training').length), participants = chronologicalDates.map(date => new Set(data.matches.filter(match => match.matchDate === date && eventType(match) === 'training').flatMap(match => [match.player1Id,match.player2Id])).size);
  charts.push(new Chart(document.querySelector('#session-timeline-chart'), { type: 'bar', data: { labels: chronologicalDates, datasets: [{ label: t('players'), data: participants, backgroundColor: 'rgba(84,184,209,.62)', borderRadius: 4 }, { type: 'line', label: t('matches'), data: counts, borderColor: '#d6a516', backgroundColor: '#d6a516', tension: .25, pointBackgroundColor: '#f6f0e2', pointRadius: 4, order: 10 }] }, options: { plugins: { legend: { labels: { color: '#f6f0e2' } } }, scales: { x: { ticks: { color: '#a5a198', maxRotation: 45 }, grid: { display: false } }, y: { ticks: { color: '#a5a198', stepSize: 1 }, grid: { color: 'rgba(246,240,226,.1)' } } } } }));
  showSession(selectedSession);
}

function renderCalendar(dates) {
  const [year, month] = calendarMonth.split('-').map(Number);
  const monthStart = new Date(year, month - 1, 1);
  const startDay = monthStart.getDay();
  const days = new Date(year, month, 0).getDate();
  const cells = Array.from({ length: startDay }, () => '<span class="calendar-day blank"></span>');
  for (let day = 1; day <= days; day++) {
    const date = `${calendarMonth}-${String(day).padStart(2, '0')}`;
    const available = dates.includes(date);
    cells.push(`<button class="calendar-day ${available ? 'available' : ''} ${date === selectedSession ? 'selected' : ''}" ${available ? `data-date="${date}"` : 'disabled'}>${day}</button>`);
  }
  document.querySelector('#session-calendar').innerHTML = `<div class="calendar-head"><button data-direction="-1" aria-label="Previous month">‹</button><strong>${calendarMonth}</strong><button data-direction="1" aria-label="Next month">›</button></div><div class="calendar-week">${['S','M','T','W','T','F','S'].map(day => `<span>${day}</span>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div>`;
  document.querySelector('#session-calendar').onclick = event => {
    const date = event.target.dataset.date;
    if (date) { selectedSession = date; calendarMonth = date.slice(0, 7); renderCalendar(dates); showSession(date); return; }
    const direction = Number(event.target.dataset.direction);
    if (direction) { const next = new Date(year, month - 1 + direction, 1); calendarMonth = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}`; renderCalendar(dates); }
  };
}

function showSession(date) {
  const matches = data.matches.filter(match => match.matchDate === date && eventType(match) === 'training');
  const participants = new Set(matches.flatMap(match => [match.player1Id, match.player2Id])).size;
  document.querySelector('#session-summary').innerHTML = `<strong>${dateLabel(date)}</strong><span>${matches.length} ${t('matches')}</span><span>${participants} ${t('players')}</span>`;
  document.querySelector('#session-matches').innerHTML = matches.map(match => matchCard(match, playerMap())).join('');
}

function setupMonths() {
  const select = document.querySelector('#month-select');
  const months = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate.slice(0, 7)))].sort().reverse();
  select.innerHTML = `<option value="all">${t('allResults')}</option>${months.map(month => `<option value="${month}">${month}</option>`).join('')}`;
  select.value = months.includes(selectedMonth) ? selectedMonth : 'all';
  const years = [...new Set(months.map(month => month.slice(0, 4)))];
  const yearSelect = document.querySelector('#year-select');
  yearSelect.innerHTML = `<option value="all">${t('allResults')}</option>${years.map(year => `<option value="${year}">${year}</option>`).join('')}`;
  yearSelect.value = years.includes(selectedYear) ? selectedYear : 'all';
}

function renderPlayers(ranked) {
  const query = document.querySelector('#player-search').value.toLowerCase();
  const groups = new Map();
  ranked.filter(entry => entry.stats.wins + entry.stats.losses > 0 && nameFor(entry.player).toLowerCase().includes(query)).forEach(entry => { const category = entry.player.schoolLevel || t('unassigned'); if (!groups.has(category)) groups.set(category, []); groups.get(category).push(entry); });
  document.querySelector('#player-grid').innerHTML = sortCategories([...groups.entries()]).map(([category, entries]) => `<section class="player-category"><h3>${category}</h3><div class="player-grid">${entries.map(({ player, stats }) => {
    const total = stats.wins + stats.losses;
    return `<a class="player-card" href="player.html?id=${player.playerId}"><span class="player-id">${player.playerId}</span><h3 class="player-name">${nameFor(player)}</h3><div class="player-detail">${[player.playingHand, player.playingStyle].filter(Boolean).join(' · ') || 'LITTLE KINGS'}</div><div class="player-record">${stats.wins}W - ${stats.losses}L <small>${total ? Math.round(stats.wins / total * 100) : 0}%</small></div><div class="record-bar"><i style="width:${stats.wins / total * 100}%"></i><b style="width:${stats.losses / total * 100}%"></b></div></a>`;
  }).join('')}</div></section>`).join('');
}

function renderGroupStats(matches) {
  const playerById = playerMap();
  const renderGroup = (field, target) => {
    const groups = new Map();
    data.players.forEach(player => groups.set(player[field] || t('unassigned'), { players: 0, wins: 0, games: 0, names: [] }));
    data.players.forEach(player => { const group = groups.get(player[field] || t('unassigned')); group.players++; group.names.push(nameFor(player)); });
    matches.filter(isComplete).forEach(match => [match.player1Id, match.player2Id].forEach(id => { const player = playerById.get(id); if (!player) return; const group = groups.get(player[field] || t('unassigned')); group.games++; if (match.winnerId === id) group.wins++; }));
    const entries = field === 'schoolLevel' ? sortCategories([...groups.entries()]) : [...groups.entries()].sort((a, b) => b[1].games - a[1].games);
    const totalGames = entries.reduce((total, [, value]) => total + value.games, 0);
    document.querySelector(target).innerHTML = entries.map(([label, value]) => `<div class="group-row" tabindex="0" title="${language === 'en' ? 'Players' : '選手'}: ${value.names.join(' · ')}"><strong>${label}</strong><span>${value.players} ${t('players')}</span><span>${totalGames ? Math.round(value.games / totalGames * 100) : 0}%</span><aside><b>${language === 'en' ? 'Players' : '選手'}</b>${value.names.join(' · ')}</aside></div>`).join('');
  };
  renderGroup('schoolLevel', '#category-stats');
  renderGroup('gender', '#gender-stats');
  const setupFields = language === 'en' ? [['playingStyle','Playing Style'],['grip','Grip'],['forehandRubber','Forehand Rubber'],['backhandRubber','Backhand Rubber']] : [['playingStyle','戦型 / Playing Style'],['grip','グリップ / Grip'],['forehandRubber','フォア面ラバー / Forehand Rubber'],['backhandRubber','バック面ラバー / Backhand Rubber']]; document.querySelector('#player-setup-distribution').innerHTML = setupFields.map(([field,label]) => { const reported = data.players.filter(player => player[field]), groups = new Map(); reported.forEach(player => groups.set(player[field], (groups.get(player[field]) || 0) + 1)); const entries = [...groups.entries()].sort((left,right) => right[1] - left[1] || left[0].localeCompare(right[0],'ja')); return `<section><header><b>${label}</b><small>${reported.length}/${data.players.length} ${language === 'en' ? 'reported' : '登録'}</small></header>${entries.length ? entries.map(([value,count]) => `<div class="setup-row"><span title="${value}">${value}</span><b>${count}</b><i><em style="width:${Math.round(count / reported.length * 100)}%"></em></i></div>`).join('') : `<p>${language === 'en' ? 'No profile data yet' : 'プロフィール情報が未登録です'}</p>`}</section>`; }).join('');
}

function renderThreeMonthSummary() {
  const allMonths = [...new Set(data.matches.filter(match => eventType(match) === 'training').map(match => match.matchDate.slice(0, 7)))].sort().reverse();
  recentStart = Math.min(recentStart, Math.max(0, allMonths.length - 2));
  const months = allMonths.slice(recentStart, recentStart + 2);
  document.querySelector('#recent-prev').disabled = recentStart >= allMonths.length - 2;
  document.querySelector('#recent-next').disabled = recentStart === 0;
  monthlyCategoryEntries = new Map(); monthlyCategoryMatches = new Map(); const report = months.map(month => {
    const matches = data.matches.filter(match => eventType(match) === 'training' && match.matchDate.startsWith(month));
    const participants = new Set(matches.flatMap(match => [match.player1Id, match.player2Id]));
    const periodEligibility = eligibility(matches, 2), rankings = rankPlayers(matches).filter(entry => entry.stats.wins + entry.stats.losses >= periodEligibility.minimum);
    const groups = new Map();
    rankings.forEach(entry => { const category = entry.player.schoolLevel || t('unassigned'); if (!groups.has(category)) groups.set(category, []); groups.get(category).push(entry); });
    const categories = sortCategories([...groups.entries()].filter(([category]) => isAssignedCategory(category)));
    categories.forEach(([category, entries]) => { monthlyCategoryEntries.set(`${month}|${category}`, entries); monthlyCategoryMatches.set(`${month}|${category}`, matches); }); const leaders = categories.map(([category, entries]) => `<section class="category-podium"><button class="category-ranking-open" data-month="${month}" data-category="${category}">🏆 ${category}<small>${language === 'en' ? 'View all rankings' : '全順位を見る'}</small></button>${entries.slice(0, 3).map((entry, index) => `<div><i>${rankIcon(index)}</i><b>${playerLink(entry.player)}</b>${recordSummary(entry.stats, matches, entry.player.playerId)}</div>`).join('')}</section>`).join('');
    const champions = categories.map(([category, entries]) => { const entry = entries[0], games = entry.stats.wins + entry.stats.losses, winLabel = language === 'en' ? 'W' : '勝', lossLabel = language === 'en' ? 'L' : '負'; return `<div><span>${category}</span><b>${playerLink(entry.player)}</b><small>${Math.round(entry.stats.wins / games * 100)}% · ${language === 'en' ? `${games}G` : `${games}試合`} · <i class="win">${winLabel}</i>${entry.stats.wins} <i class="loss">${lossLabel}</i>${entry.stats.losses}</small></div>`; }).join('');
    return { month, matches, participants, leaders, champions, eligibility: periodEligibility };
  });
  document.querySelector('#three-month-summary').innerHTML = `<div class="three-month-cards">${report.map(item => `<article><header><p>${item.month}</p><strong>${item.matches.length}<small>${t('matches')}</small></strong><span>${item.eligibility.gameDays} ${phrase('matchDays')} · ${item.participants.size} ${t('players')} ${t('participated')}</span><small class="eligibility">${item.eligibility.text}</small></header><div class="champion-strip"><b>🏆 ${categoryLeaders()}</b>${item.champions}</div><div class="podiums">${item.leaders}</div></article>`).join('')}</div>`;
}

function renderYearlySummary() {
  const years = [...new Set(data.matches.filter(match => eventType(match) === 'training' && match.matchDate).map(match => match.matchDate.slice(0,4)))].sort().reverse(); leaderboardYearIndex = Math.min(leaderboardYearIndex, Math.max(0, years.length - 1)); const year = years[leaderboardYearIndex] || '', matches = data.matches.filter(match => eventType(match) === 'training' && match.matchDate.startsWith(year)), rankings = rankPlayers(matches).filter(entry => entry.stats.wins + entry.stats.losses >= eligibility(matches).minimum);
  const categories = new Map();
  rankings.forEach(entry => { const category = entry.player.schoolLevel || t('unassigned'); if (!categories.has(category)) categories.set(category, []); categories.get(category).push(entry); });
  const categoryEntries = sortCategories([...categories.entries()].filter(([category]) => isAssignedCategory(category)));
  categoryLeaderboardEntries = new Map(categoryEntries); categoryLeaderboardYear = year; categoryLeaderboardMatches = matches; const participants = new Set(matches.filter(isComplete).flatMap(match => [match.player1Id,match.player2Id])).size, periodEligibility = eligibility(matches), winLabel = language === 'ja' ? '勝' : 'W', lossLabel = language === 'ja' ? '負' : 'L'; document.querySelector('#overall-link-title').textContent = language === 'en' ? `${year} Yearly Leaderboard` : `${year}年リーダーボード`; document.querySelector('#overall-year-prev').disabled = leaderboardYearIndex >= years.length - 1; document.querySelector('#overall-year-next').disabled = leaderboardYearIndex === 0; document.querySelector('#overall-link-detail').textContent = language === 'en' ? `Top 3 by category · ${participants} players · ${periodEligibility.text}` : `カテゴリ別 TOP 3 · ${participants}人 · ${periodEligibility.text}`; document.querySelector('#overall-stat-list').innerHTML = categoryEntries.map(([category, entries]) => `<section><button class="category-ranking-open" data-category="${category}">🏆 ${category}<small>${language === 'en' ? 'View all rankings' : '全順位を見る'}</small></button>${entries.slice(0,3).map((entry,index) => { const games = entry.stats.wins + entry.stats.losses, rate = Math.round(entry.stats.wins / games * 100), categories = opponentCategoryBreakdown(matches, entry.player.playerId); return `<span><i>${rankIcon(index)}</i><a class="player-link" href="player.html?id=${entry.player.playerId}">${nameFor(entry.player)}<small class="alltime-record"><b class="${rate >= 50 ? 'positive' : 'negative'}" title="${categories}">${rate}%</b><em><i class="win">${winLabel}</i>${entry.stats.wins} <i class="loss">${lossLabel}</i>${entry.stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</em><em class="leader-category-records">${categories.replace(/\n/g,' · ')}</em></small></a></span>`; }).join('')}</section>`).join('');
}

function openHeadToHead(matchId) {
  const match = data.matches.find(item => item.matchId === matchId); if (!match) return;
  const map = playerMap(), first = map.get(match.player1Id), second = map.get(match.player2Id);
  const history = data.matches.filter(item => (item.player1Id === match.player1Id && item.player2Id === match.player2Id) || (item.player1Id === match.player2Id && item.player2Id === match.player1Id)).sort((a,b) => b.matchDate.localeCompare(a.matchDate));
  const firstWins = history.filter(item => item.winnerId === match.player1Id).length;
  const outcomes = history.map(item => item.winnerId === match.player1Id ? 1 : item.winnerId === match.player2Id ? -1 : 0);
  document.querySelector('#head-to-head-content').innerHTML = `<p class="eyebrow">${phrase('h2h')}</p><button class="how-to-read h2h-help" data-help="h2h" aria-label="How to read Head to Head">?</button><h2>${nameFor(first)} <em>${firstWins} - ${history.filter(item => item.winnerId === match.player2Id).length}</em> ${nameFor(second)}</h2><p class="h2h-meta">${phrase('h2hTimeline')}</p><div class="h2h-chart"><canvas id="h2h-chart"></canvas></div><div class="h2h-history">${history.map(item => `<div><span>${item.matchDate}</span><strong>${item.player1Name} ${item.player1Sets}-${item.player2Sets} ${item.player2Name}</strong></div>`).join('')}</div>`;
  new Chart(document.querySelector('#h2h-chart'), { type: 'bar', data: { labels: history.map(item => item.matchDate), datasets: [{ label: nameFor(first), data: outcomes, backgroundColor: outcomes.map(value => value > 0 ? '#d6a516' : value < 0 ? '#8c423a' : '#6e6a62'), borderRadius: 3 }] }, options: { plugins: { legend: { display: false } }, scales: { x: { ticks: { color: '#a5a198' }, grid: { display: false } }, y: { min: -1, max: 1, ticks: { color: '#a5a198', stepSize: 1, callback: value => value === 1 ? phrase('win') : value === -1 ? phrase('loss') : phrase('draw') }, grid: { color: 'rgba(246,240,226,.1)' } } } } });
  const setupFor = player => [[language === 'en' ? 'Style' : '戦型',player.playingStyle],[language === 'en' ? 'Grip' : 'グリップ',player.grip],[language === 'en' ? 'FH' : 'フォア',player.forehandRubber],[language === 'en' ? 'BH' : 'バック',player.backhandRubber]].filter(([,value]) => value).map(([label,value]) => `<span><b>${label}</b>${value}</span>`).join('') || `<span>${language === 'en' ? 'No setup data' : '用具情報なし'}</span>`; document.querySelector('#head-to-head-content').insertAdjacentHTML('beforeend', `<section class="h2h-setups"><p>${language === 'en' ? 'Player Setup Context' : '選手セッティング比較'}</p><div><article><b>${nameFor(first)}</b>${setupFor(first)}</article><article><b>${nameFor(second)}</b>${setupFor(second)}</article></div></section>`); document.querySelector('#head-to-head').showModal();
}

function render() {
  document.documentElement.lang = language;
  document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); });
  document.querySelector('#language-toggle').textContent = language === 'en' ? '日本語' : 'ENGLISH';
  document.querySelector('#session-timeline-title').textContent = phrase('matchDayVolume'); document.querySelector('#menu-toggle').textContent = '☰'; document.querySelector('#menu-toggle').setAttribute('aria-label', phrase('menu'));
  document.querySelector('#player-search').placeholder = language === 'en' ? 'Search players' : '選手を検索';
  const matches = visibleMatches(), ranked = rankPlayers(matches), dates = matches.map(match => match.matchDate).filter(Boolean).sort();
  charts.forEach(chart => chart.destroy()); charts = [];
  document.querySelector('#player-count').textContent = data.players.length;
  renderPlayers(ranked); renderGroupStats(matches); renderThreeMonthSummary(); renderYearlySummary(); renderSession();
  document.querySelector('#last-updated').textContent = `${t('lastUpdated')}: ${new Date(data.lastUpdated).toLocaleString(language === 'ja' ? 'ja-JP' : 'en-GB')}`;
  const latestMatchDate = data.matches.map(match => match.matchDate).filter(Boolean).sort().at(-1); document.querySelector('#match-data-status').textContent = latestMatchDate ? (language === 'en' ? `Latest match data: ${dateLabel(latestMatchDate)}` : `最新試合データ: ${dateLabel(latestMatchDate)}`) : (language === 'en' ? 'No match data recorded' : '試合データはありません');
}

document.querySelector('#language-toggle').onclick = () => { language = language === 'en' ? 'ja' : 'en'; localStorage.setItem('lk-language', language); render(); };
document.querySelector('#menu-toggle').onclick = event => { const menu = document.querySelector('nav'); const open = menu.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', open); };
document.querySelector('nav').onclick = event => { if (event.target.matches('a')) { document.querySelector('nav').classList.remove('open'); document.querySelector('#menu-toggle').setAttribute('aria-expanded', 'false'); } };
document.querySelector('#player-search').oninput = () => renderPlayers(rankPlayers());
document.querySelector('#hero-player-finder').onclick = () => { const panel = document.querySelector('#hero-player-panel'); panel.hidden = !panel.hidden; if (!panel.hidden) { const input = document.querySelector('#hero-player-search'); input.focus(); input.dispatchEvent(new Event('input')); } };
document.querySelector('#hero-player-search').oninput = event => { const query = event.target.value.trim().toLowerCase(), results = data.players.filter(player => `${player.playerId} ${player.displayName} ${player.englishName || ''}`.toLowerCase().includes(query)).slice(0,8); document.querySelector('#hero-player-results').innerHTML = results.map(player => `<a href="player.html?id=${player.playerId}">${nameFor(player)}<small>${player.playerId}${player.schoolLevel ? ` · ${player.schoolLevel}` : ''}</small></a>`).join('') || `<small>${language === 'en' ? 'No players found' : '該当する選手がいません'}</small>`; };
document.querySelector('#recent-prev').onclick = () => { recentStart++; renderThreeMonthSummary(); };
document.querySelector('#recent-next').onclick = () => { recentStart--; renderThreeMonthSummary(); };
document.querySelector('#overall-year-prev').onclick = () => { leaderboardYearIndex++; renderYearlySummary(); };
document.querySelector('#overall-year-next').onclick = () => { leaderboardYearIndex--; renderYearlySummary(); };
const howToRead = {
  yearly: { en: { title:'How to Read the Yearly Leaderboard', intro:'Rankings compare players within the same category for the selected year.', points:['Check eligibility first: a player needs one completed match for every recorded match day that year.','Win rate is most useful alongside the W/L total and number of games. A strong rate from fewer matches is a smaller sample.','Use the opponent-category record to understand where results were earned. Different opponent pools create different challenges.','Treat the table as a review tool, not a judgement of player quality. Look for training priorities, not labels.'] }, ja: { title:'年間リーダーボードの見方', intro:'選択した年の同じカテゴリ内で順位を比較しています。', points:['まず対象条件を確認します。その年のすべての試合日に、完了試合を1試合以上行う必要があります。','勝率は勝敗数と試合数と合わせて確認します。試合数が少ない高勝率は、判断材料がまだ少ない場合があります。','対戦相手カテゴリ別の勝敗を見ると、どの相手層との結果かを理解できます。対戦相手の構成によって難易度は変わります。','順位は選手の良し悪しを決めるものではありません。次の練習課題を見つけるために活用してください。'] } },
  monthly: { en: { title:'How to Read the Monthly Leaderboard', intro:'This view is a short-term training snapshot for each displayed month.', points:['Eligibility requires two completed matches for every recorded match day in that month.','Compare a month with the previous month to spot changes in consistency, participation, and win rate.','Read W/L and opponent-category records together. A lower rate against a stronger or unfamiliar group can still reveal useful progress.','Use the result to set one practical next focus, such as serve receive, third-ball attack, or closing close games.'] }, ja: { title:'月間リーダーボードの見方', intro:'表示月ごとの短期的な練習状況を確認するための一覧です。', points:['対象条件は、その月のすべての試合日に完了試合を2試合以上行うことです。','前月と比べて、安定感、参加状況、勝率の変化を確認してください。','勝敗と対戦相手カテゴリ別の記録を合わせて見ます。強い相手や慣れない相手が多い月は、勝率が低くても有意義な成長が見える場合があります。','サーブレシーブ、3球目攻撃、接戦の締め方など、次の練習テーマを1つ決めるために使ってください。'] } },
  volume: { en: { title:'How to Read Match-Day Volume', intro:'The chart shows how much competitive practice happened on each training day.', points:['Blue bars show participating players. The gold line shows completed and recorded matches.','More matches create more repetition and feedback, but volume alone does not measure quality.','Look for days with many matches and revisit those session results to identify recurring score patterns or difficult opponents.','Combine volume with win rate, score lines, and your own match notes before changing training priorities.'] }, ja: { title:'試合日別試合数の見方', intro:'各練習日に、どれだけ実戦形式の練習が行われたかを示すグラフです。', points:['青い棒は参加選手数、金色の線は記録された完了試合数です。','試合数が多いほど反復と振り返りの機会は増えますが、量だけで練習の質は判断できません。','試合数が多い日の結果を見直し、繰り返し出るスコア傾向や苦手な相手を確認してください。','練習テーマを変える前に、試合数、勝率、スコア、自分のメモを合わせて判断してください。'] } },
  sessions: { en: { title:'How to Read Session Replay', intro:'Choose a training date to review the individual matches played that day.', points:['Read the score, result, and opponent together. A 3-2 result contains different information from a 3-0 result.','Close losses can point to decision-making under pressure, serve/receive quality, or the final-ball pattern.','Incomplete matches are shown for the record but are excluded from performance statistics and rankings.','After reviewing a session, write down one successful pattern and one situation to practise next time.'] }, ja: { title:'練習日リプレイの見方', intro:'練習日を選ぶと、その日に行われた個別の試合を振り返れます。', points:['スコア、結果、対戦相手を一緒に確認してください。3-2の試合と3-0の試合では、得られる情報が異なります。','接戦での敗戦は、プレッシャー下の判断、サーブレシーブ、終盤の得点パターンなどの課題を示すことがあります。','未完了試合は記録として表示されますが、成績やランキングの集計には含まれません。','振り返った後、うまくできたパターンを1つ、次回練習する場面を1つ書き出してください。'] } },
  players: { en: { title:'How to Use Player Profiles', intro:'Select a player to see their training record, trends, opponent matchups, and available playing information.', points:['Use the match timeline to see consistency over several training days, rather than reacting to one result.','Opponent insights help identify repeated matchups and whether adjustments are needed in tactics or preparation.','Equipment and playing-style details are reference information for understanding a player, not a prescription for changing gear.','Discuss patterns with the player and coach, then turn the review into a small, measurable practice goal.'] }, ja: { title:'選手プロフィールの活用方法', intro:'選手を選ぶと、練習記録、成績推移、対戦相手との記録、登録済みのプレー情報を確認できます。', points:['1試合の結果だけで判断せず、複数の練習日にわたる推移から安定感を確認してください。','対戦相手分析では、繰り返し対戦する相手や、戦術・準備の見直しが必要な組み合わせを確認できます。','用具やプレースタイルの情報は選手を理解するための参考です。すぐに用具変更を勧めるためのものではありません。','選手とコーチで傾向を話し合い、小さく測定可能な練習目標に変えてください。'] } }
};
howToRead.h2h = { en: { title:'How to Read Head to Head', intro:'This view compares only the two selected players across their recorded meetings.', points:['The bars show the result of each match in time order: win, loss, or draw.','Read the score list with the timeline. Repeated close losses and repeated one-sided losses suggest different training questions.','Use the history to identify one matchup-specific focus, such as serve placement, receive choice, first attack, or rally pattern.','A Head-to-Head record is a tactical review tool, not a fixed measure of either player’s level.'] }, ja: { title:'直接対決の見方', intro:'選択した2選手の記録済み対戦だけを比較する画面です。', points:['棒は時系列の各試合結果を示し、勝ち・負け・引分を確認できます。','スコア一覧とタイムラインを合わせて見ます。接戦の敗戦が続く場合と一方的な敗戦が続く場合では、考える練習課題が異なります。','サーブのコース、レシーブの選択、先手の取り方、ラリーのパターンなど、対戦相手別の課題を1つ決めてください。','直接対決の記録は戦術を振り返るためのものであり、選手の実力を固定的に決めるものではありません。'] } };
document.addEventListener('click', event => { const button = event.target.closest('.how-to-read'); if (!button) return; const content = howToRead[button.dataset.help]?.[language]; if (!content) return; const parentDialog = button.closest('dialog'); if (parentDialog && parentDialog.id !== 'how-to-read-dialog') { let panel = parentDialog.querySelector('.inline-how-to-read'), exists = Boolean(panel); if (!panel) { panel = document.createElement('section'); panel.className = 'inline-how-to-read'; parentDialog.querySelector('[id$="-content"]').append(panel); } panel.innerHTML = `<b>${content.title}</b><p>${content.intro}</p><ul>${content.points.map(point => `<li>${point}</li>`).join('')}</ul>`; panel.hidden = exists ? !panel.hidden : false; return; } document.querySelector('#how-to-read-content').innerHTML = `<p class="eyebrow">HOW TO READ</p><h2>${content.title}</h2><p>${content.intro}</p><ul>${content.points.map(point => `<li>${point}</li>`).join('')}</ul>`; document.querySelector('#how-to-read-dialog').showModal(); });
document.addEventListener('click', event => { const card = event.target.closest('.match-card'); if (card?.dataset.matchId) { const match = data.matches.find(item => item.matchId === card.dataset.matchId); if (match) location.href = `player.html?id=${match.player1Id}&opponent=${match.player2Id}`; } if (event.target.closest('.modal-close')) document.querySelectorAll('dialog[open]').forEach(dialog => dialog.close()); const categoryButton = event.target.closest('.category-ranking-open'); if (categoryButton && !categoryButton.dataset.month) { const category = categoryButton.dataset.category, entries = categoryLeaderboardEntries.get(category) || [], title = language === 'en' ? `${categoryLeaderboardYear} ${category} Rankings` : `${categoryLeaderboardYear}年 ${category} 順位`, winLabel = language === 'en' ? 'W' : '勝', lossLabel = language === 'en' ? 'L' : '負'; document.querySelector('#category-leaderboard-content').innerHTML = `<p class="eyebrow">YEARLY CATEGORY RANKING</p><button class="how-to-read h2h-help" data-help="yearly" aria-label="How to read category rankings">?</button><h2>${title}</h2><ol>${entries.map((entry,index) => { const games = entry.stats.wins + entry.stats.losses, rate = Math.round(entry.stats.wins / games * 100), categories = opponentCategoryBreakdown(categoryLeaderboardMatches, entry.player.playerId).replace(/\n/g, ' · '); return `<li><i>${rankIcon(index)}</i><a class="player-link" href="player.html?id=${entry.player.playerId}">${nameFor(entry.player)}</a><b>${rate}%</b><span>${winLabel}${entry.stats.wins} · ${lossLabel}${entry.stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</span><span class="leader-category-records">${categories}</span></li>`; }).join('')}</ol>`; document.querySelector('#category-leaderboard').showModal(); } });
document.addEventListener('click', event => { const button = event.target.closest('.category-ranking-open[data-month]'); if (!button) return; const category = button.dataset.category, month = button.dataset.month, entries = monthlyCategoryEntries.get(`${month}|${category}`) || [], matches = monthlyCategoryMatches.get(`${month}|${category}`) || [], title = language === 'en' ? `${month} ${category} Rankings` : `${month} ${category} 順位`, winLabel = language === 'en' ? 'W' : '勝', lossLabel = language === 'en' ? 'L' : '負'; document.querySelector('#category-leaderboard-content').innerHTML = `<p class="eyebrow">MONTHLY CATEGORY RANKING</p><button class="how-to-read h2h-help" data-help="monthly" aria-label="How to read category rankings">?</button><h2>${title}</h2><ol>${entries.map((entry,index) => { const games = entry.stats.wins + entry.stats.losses, rate = Math.round(entry.stats.wins / games * 100), categories = opponentCategoryBreakdown(matches, entry.player.playerId).replace(/\n/g, ' · '); return `<li><i>${rankIcon(index)}</i><a class="player-link" href="player.html?id=${entry.player.playerId}">${nameFor(entry.player)}</a><b>${rate}%</b><span>${winLabel}${entry.stats.wins} · ${lossLabel}${entry.stats.losses} · ${language === 'en' ? `${games}G` : `${games}試合`}</span><span class="leader-category-records">${categories}</span></li>`; }).join('')}</ol>`; document.querySelector('#category-leaderboard').showModal(); });
fetch('./public-data.json').then(response => { if (!response.ok) throw new Error(); return response.json(); }).catch(() => fetch(API_URL).then(response => response.json())).then(result => { if (!result.ok) throw new Error(); data = result; render(); }).catch(() => document.querySelectorAll('.loading').forEach(element => { element.textContent = 'Unable to load live data.'; }));
