(() => {
  'use strict';

  const app = document.querySelector('#insights-app');
  const params = new URLSearchParams(location.search);
  let data;
  let language = localStorage.getItem('lk-language') || 'ja';
  let activeView = location.hash.slice(1) || 'session';
  let selectedDate = params.get('session') || '';
  let comparisonDate = params.get('compare') || '';
  let growthSearch = '';
  let growthCategory = '';
  const growthPageSize = 12;
  let growthLimit = growthPageSize;
  let sessionChart;
  let sessionTrendChart;
  let comparisonScoreChart;
  let comparisonDumbbellChart;

  const words = {
    en: {
      title: 'Training Insights', subtitle: 'Session trends, player development, and match patterns',
      session: 'Session Insights', growth: 'Player Growth', tournament: 'Tournament Readiness',
      completedOnly: 'Completed statistics require one player to reach three sets. Match participation is not attendance.',
      selectSession: 'Training date', compareSession:'Compare with', recorded: 'Recorded matches', complete: 'Completed', participants: 'Match participants', pairings: 'Unique pairings',
      close: 'Close matches', incomplete: 'Incomplete records', attention: 'Review signals', noSignals: 'No notable review signals for this session.',
      workload: 'Recorded / complete', record: 'Record', setDiff: 'Avg. set diff.', change: 'vs previous 5', diversity: 'Opponents', confidence: 'Evidence',
      stronger: 'Stronger', medium: 'Medium', limited: 'Limited', improving: 'Higher recent set differential', declining: 'Lower recent set differential', stable: 'Similar recent set differential', more: 'More matches needed',
      oneMatch: 'Only one recorded match', closeLoss: 'Close loss to review', decisiveLoss: 'Decisive-loss pattern to review', movementUp: 'Recent set differential is higher', movementDown: 'Recent set differential is lower',
      sessionPlayers: 'Player session summary', recurring: 'Recurring pairings', matches: 'Session matches', priorMeetings: 'prior meetings',
      sessionTrend: 'Last 12 training dates', trendNote: 'Recorded volume, match participation, completion, and close-match share', workloadDistribution: 'Selected-session workload distribution', pairingHeatmap: 'Pairing heatmap', heatmapNote: 'Recorded meetings among this session’s participants across the latest six training dates', maxRepeat: 'Highest repeat count', reflections: 'Player reflections', reflectionNote: 'Player self-feedback; not a coach evaluation or attendance record', effort: 'Avg. effort', confidenceLabel: 'Avg. confidence', addReflection: 'Add reflection', wentWell: 'Went well', nextFocus: 'Next focus', noReflections: 'No approved reflections for this date.', sessionReflections:'Session reflections', matchReflections:'Match reflections', whatWorked:'What worked', challenge:'Main difficulty', nextPlan:'Next-match plan',
      playerSearch: 'Search player', allCategories: 'All categories', growthIntro: 'Transparent rolling results; not an official ranking or development score. Coach-arranged opponent difficulty may change between periods.',
      sampledPlayers: 'Players with 10-match sample', improvingPlayers: 'Higher recent set diff.', limitedPlayers: 'Limited samples', inactivePlayers: 'No matches in last 3 sessions',
      last10: 'Last 10', previous10: 'Previous 10', lastFive: 'Last 5', previousFive: 'Previous 5', scorelines: 'Scorelines', sessions: 'Sessions',
      normalized: 'Last 10 per match day', activity: 'Recorded-match activity', opponentMix: 'Opponent category mix',
      readinessIntro: 'Training and tournament records remain separate. Training results are scouting context only.', field: 'Field opponents', known: 'Known opponents', coverage: 'Field coverage', priority: 'Priority opponents', recentForm: 'Recent training form', missing: 'Missing scouting data', noTournaments: 'No Little Kings tournament entries found.',
      openProfile: 'Open profile', openTournament: 'Open tournament hub', lastUpdated: 'Last updated', unknown: 'Unassigned', noData: 'No data available.', printReport:'Print / Save PDF', sessionReport:'Session summary', metadataUnrecorded:'Session metadata not recorded', participantOverlap:'Participant overlap', scoreComparison:'Scoreline comparison', playerMovement:'Common-player set differential', comparisonCaution:'Comparison only: participant and opponent mixes may differ.', categoryMatrix:'Category matchup matrix', calendarActivity:'Training activity calendar', venue:'Venue', sessionType:'Session type', coachGoal:'Coach goal', coachNote:'Coach note', source:'Source / verification'
    },
    ja: {
      title: '練習分析', subtitle: '練習セッション・選手の成長・対戦傾向を分析',
      session: 'セッション分析', growth: '選手の成長', tournament: '大会準備',
      completedOnly: '完了スタッツはどちらかが3セット到達した試合のみ。試合参加は出席記録ではありません。',
      selectSession: '練習日', compareSession:'比較する練習日', recorded: '登録試合', complete: '完了', participants: '試合参加選手', pairings: '対戦組合せ',
      close: '接戦', incomplete: '未完了記録', attention: '振り返りシグナル', noSignals: 'このセッションに顕著な振り返りシグナルはありません。',
      workload: '登録 / 完了', record: '戦績', setDiff: '平均セット差', change: '前5試合比', diversity: '対戦相手', confidence: 'データ量',
      stronger: '比較的十分', medium: '中程度', limited: '少数', improving: '直近のセット差が上昇', declining: '直近のセット差が低下', stable: '直近のセット差は同程度', more: 'データ不足',
      oneMatch: '登録試合が1試合のみ', closeLoss: '振り返りたい接戦負け', decisiveLoss: '振り返りたい大差敗戦', movementUp: '直近のセット差が上昇', movementDown: '直近のセット差が低下',
      sessionPlayers: '選手別セッション概要', recurring: '継続対戦カード', matches: 'セッション試合', priorMeetings: '過去対戦',
      sessionTrend: '直近12回の練習推移', trendNote: '登録試合数・試合参加選手数・完了率・接戦率', workloadDistribution: '選択セッションの試合数分布', pairingHeatmap: '対戦組合せヒートマップ', heatmapNote: '今回の参加選手について、直近6回の練習日に登録された対戦回数', maxRepeat: '最多反復回数', reflections: '選手振り返り', reflectionNote: '選手本人の自己振り返りです。コーチ評価・出席記録ではありません', effort: '平均がんばり度', confidenceLabel: '平均自信', addReflection: '振り返りを書く', wentWell: 'うまくできたこと', nextFocus: '次に意識すること', noReflections: 'この日の承認済み振り返りはありません。', sessionReflections:'セッション振り返り', matchReflections:'試合振り返り', whatWorked:'機能したこと', challenge:'一番難しかったこと', nextPlan:'次の対戦プラン',
      playerSearch: '選手を検索', allCategories: '全カテゴリ', growthIntro: '透明性のある移動結果です。公式ランキングや総合成長スコアではありません。コーチ設定による対戦難易度は期間ごとに変わる場合があります。',
      sampledPlayers: '10試合サンプル', improvingPlayers: '直近セット差が上昇', limitedPlayers: '少数サンプル', inactivePlayers: '直近3回に試合なし',
      last10: '直近10試合', previous10: 'その前の10試合', lastFive: '直近5試合', previousFive: 'その前の5試合', scorelines: 'スコア内訳', sessions: '試合日',
      normalized: '直近10試合の日別平均', activity: '試合記録のある直近活動', opponentMix: '対戦カテゴリ構成',
      readinessIntro: '練習試合と大会結果は分けて表示します。練習結果はスカウティング参考情報のみです。', field: '同部門の対戦候補', known: '対戦記録あり', coverage: 'フィールド把握率', priority: '優先対戦相手', recentForm: '直近の練習成績', missing: '未スカウト', noTournaments: 'リトルキングス選手の大会登録がありません。',
      openProfile: 'プロフィールを見る', openTournament: '大会ハブを開く', lastUpdated: '最終更新', unknown: '未設定', noData: 'データがありません。', printReport:'印刷・PDF保存', sessionReport:'セッション概要', metadataUnrecorded:'セッション情報未登録', participantOverlap:'共通の試合参加選手', scoreComparison:'スコア内訳比較', playerMovement:'共通選手のセット差比較', comparisonCaution:'比較情報です。参加選手や対戦相手の構成が異なる場合があります。', categoryMatrix:'カテゴリ対戦マトリクス', calendarActivity:'練習活動カレンダー', venue:'会場', sessionType:'セッション種別', coachGoal:'指導目標', coachNote:'指導メモ', source:'出典・確認'
    }
  };
  words.en.noReflections = 'No published reflections for this date.';
  words.ja.noReflections = 'この日の公開済み振り返りはありません。';
  const t = key => words[language][key];
  const analysisGuides = {
    session: {
      en:{title:'How to Use Session Insights',intro:'Use this view to review what was recorded on two training dates. It compares sessions; it does not score the quality of a session.',read:['Recorded includes every saved match; completed includes only matches where a player reached three sets. Result rates use completed matches.','Match participants are players with a recorded match, not an attendance list. Close matches are 3–2 or 2–3.','The common-player chart compares average set differential only for players recorded on both dates. Opponents and training goals may still differ.'],action:'Open the underlying matches and reflections, then choose one session-wide pattern or one player-specific situation to discuss and practise.',limit:'Do not conclude that a higher volume, close-match rate, or set differential means a better session. Point-by-point play, attendance, coach-assigned difficulty, and session conditions are not fully recorded.'},
      ja:{title:'セッション分析の使い方',intro:'2つの練習日に登録された内容を振り返るための画面です。練習日を比較しますが、練習の質を採点するものではありません。',read:['登録試合は保存された全試合、完了試合はどちらかが3セットに到達した試合です。結果の割合は完了試合のみで集計します。','試合参加選手は試合記録がある選手で、出席者一覧ではありません。接戦は3–2または2–3です。','共通選手グラフは両日に記録がある選手の平均セット差を比較します。対戦相手や練習目標が異なる場合があります。'],action:'元の試合と振り返りを開き、全体で1つ、または選手ごとに1つ、話し合って練習する場面を選んでください。',limit:'試合数、接戦率、セット差が高いだけで「より良い練習日」と判断しないでください。ポイント内容、出席、コーチ設定の難易度、当日の条件は十分に記録されていません。'},
    },
    growth: {
      en:{title:'How to Use Player Growth',intro:'Use this view to find result patterns worth reviewing. It is not an ability grade, official ranking, or prediction.',read:['Last 10 combines W–L, average set differential, opponent variety, match days, and scorelines. Read them together.','The recent comparison uses the last five versus the previous five. A label appears only with at least three matches in each window and a ±0.5 average-set change.','Higher or lower recent results describe the recorded sample only. Coaches may have arranged stronger or different opponents.'],action:'Open the player profile and actual matches, ask what changed, and agree on one observable next focus such as receive choice, first attack, or closing a close game.',limit:'Do not use a label to rank development or assume its cause. The data does not record point patterns, physical condition, every training activity, or coach-assigned opponent difficulty.'},
      ja:{title:'選手の成長データの使い方',intro:'振り返る価値がある結果パターンを探す画面です。実力評価、公式順位、将来予測ではありません。',read:['直近10試合は、勝敗、平均セット差、相手の多様性、試合日数、スコア内訳を合わせて確認します。','直近比較は直近5試合とその前の5試合です。両方3試合以上、平均セット差±0.5以上のときだけ表示します。','直近結果の上昇・低下は記録サンプルの説明です。コーチがより強い相手や異なる相手を設定している場合があります。'],action:'選手プロフィールと実際の試合を開き、何が変わったかを確認して、レシーブ選択、先手、接戦の締め方など次の観察可能な課題を1つ決めてください。',limit:'表示ラベルで成長順位をつけたり、原因を決めつけたりしないでください。ポイント内容、体調、練習全体、コーチ設定の対戦難易度は記録されていません。'},
    },
    tournament: {
      en:{title:'How to Use Tournament Readiness',intro:'Use this view to organize known information before an event—not to predict who will win.',read:['Field opponents are other listed players in the same recorded division. Coverage is the share with at least one documented Little Kings meeting.','Known-opponent records show training and tournament evidence separately. Training results are scouting context, not tournament results.','Priority opponents are listed representatives or recommended players. Priority does not mean they are automatically the strongest or most likely opponent.'],action:'Review known scorelines, identify missing opponents, then prepare one or two adaptable match plans rather than a plan based on a single past result.',limit:'Published fields may be incomplete, draws can change, and past matches may not reflect current form. No record means “unknown,” not “easy” or “never played.”'},
      ja:{title:'大会準備データの使い方',intro:'大会前に分かっている情報を整理する画面です。勝敗を予測するものではありません。',read:['同部門の対戦候補は、記録された同じ部門の他選手です。把握率は、リトルキングスとの対戦記録が1試合以上ある相手の割合です。','既知の相手は、練習試合と大会試合を分けて表示します。練習結果はスカウティング参考情報であり、大会結果ではありません。','優先相手は代表または推薦として登録された選手です。必ず最強、または必ず対戦するという意味ではありません。'],action:'既知のスコアを確認し、情報がない相手を把握したうえで、過去1試合だけに依存しない1〜2個の対応可能な試合プランを準備してください。',limit:'公開フィールドが未完成の場合や組合せ変更があります。過去結果が現在の状態を表すとは限りません。記録なしは「不明」であり、「簡単」「未対戦確定」ではありません。'},
    }
  };
  const analysisGuide = key => window.LKHowToRead.details(analysisGuides[key]?.[language] || analysisGuides[key]?.en, language);
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[character]);
  const eventType = match => /club|training|練習/i.test(`${match.event || ''} ${match.division || ''}`) ? 'Training' : 'Tournament';
  const isComplete = match => Number(match.player1Sets) >= 3 || Number(match.player2Sets) >= 3;
  const trainingMatches = () => (data.matches || []).filter(match => eventType(match) === 'Training');
  const completedMatches = () => trainingMatches().filter(isComplete);
  const playerMap = () => new Map([...(data.players || []).map(player => [player.playerId, player]), ...(data.externalOpponents || []).map(player => [player.externalOpponentId, { ...player, playerId: player.externalOpponentId }])]);
  const nameFor = player => language === 'en' && player?.englishName ? `${player.displayName} | ${player.englishName.toUpperCase()}` : player?.displayName || player?.playerId || '-';
  const opponentId = (match, id) => match.player1Id === id ? match.player2Id : match.player1Id;
  const scoreFor = (match, id) => ({ own:Number(match.player1Id === id ? match.player1Sets : match.player2Sets), other:Number(match.player1Id === id ? match.player2Sets : match.player1Sets) });
  const won = (match, id) => match.winnerId === id;
  const lookup = (table, value) => {
    const entry = (window.LK_STATIC?.[table] || []).find(item => item.id === value || item.name === value || item.nameJa === value || item.nameEn === value);
    return entry ? (language === 'en' ? entry.nameEn : entry.nameJa) : value || t('unknown');
  };
  const summary = (matches, id) => {
    const wins = matches.filter(match => won(match,id)).length;
    const sets = matches.reduce((total,match) => { const score=scoreFor(match,id); return { own:total.own+score.own, other:total.other+score.other }; }, {own:0,other:0});
    return { games:matches.length, wins, losses:matches.length-wins, setDiff:sets.own-sets.other, average:matches.length ? (sets.own-sets.other)/matches.length : 0 };
  };
  const signed = value => `${value > 0 ? '+' : ''}${Number(value).toFixed(1)}`;
  const confidence = count => count >= 10 ? t('stronger') : count >= 5 ? t('medium') : t('limited');
  const checked = value => value === true || value === 'true' || value === 1;
  const dates = () => [...new Set(trainingMatches().map(match => match.matchDate).filter(Boolean))].sort();
  const categoryOf = player => lookup('schoolLevels', player?.schoolLevel);
  const resultLabel = (wins, losses) => language === 'en' ? `${wins}W-${losses}L` : `${wins}勝-${losses}負`;
  const playerMatches = id => completedMatches().filter(match => match.player1Id === id || match.player2Id === id).sort((a,b) => `${a.matchDate}${a.matchId || ''}`.localeCompare(`${b.matchDate}${b.matchId || ''}`));
  function growthRecord(player) {
    const all = playerMatches(player.playerId), last10 = all.slice(-10), previous10 = all.slice(-20,-10), last5 = all.slice(-5), previous5 = all.slice(-10,-5);
    const current = summary(last10,player.playerId), prior = summary(previous10,player.playerId), recent = summary(last5,player.playerId), previous = summary(previous5,player.playerId);
    const enough = last5.length >= 3 && previous5.length >= 3, delta = recent.average - previous.average;
    const signal = !enough ? 'more' : delta >= .5 ? 'improving' : delta <= -.5 ? 'declining' : 'stable';
    const opponents = new Set(last10.map(match => opponentId(match,player.playerId))), sessions = new Set(last10.map(match => match.matchDate)), latestSix = dates().slice(-6), activeDates = new Set(trainingMatches().filter(match => latestSix.includes(match.matchDate) && (match.player1Id === player.playerId || match.player2Id === player.playerId)).map(match => match.matchDate)), people = new Map([...(data.players || []).map(item => [item.playerId,item]),...(data.externalOpponents || []).map(item => [item.externalOpponentId,item])]), categoryCounts = new Map();
    last10.forEach(match => { const opponent = people.get(opponentId(match,player.playerId)), category = categoryOf(opponent); categoryCounts.set(category,(categoryCounts.get(category)||0)+1); });
    const categoryMix = [...categoryCounts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ja'));
    return { player, all, last10, previous10, last5, previous5, current, prior, recent, previous, delta, signal, opponents:opponents.size, sessions:sessions.size, activeDates:activeDates.size, recentSessionCount:latestSix.length, categoryMix };
  }

  function shell(content) {
    const labels = { session:t('session'), growth:t('growth'), tournament:t('tournament') };
    return `<section class="insights-hero"><div><p class="eyebrow">TRAINING INTELLIGENCE</p><h1>${t('title')}</h1><span>${t('subtitle')}</span></div><aside><b>${dates().length}</b><small>${language === 'en' ? 'recorded training dates' : '登録練習日'}</small><em>${t('lastUpdated')}: ${new Date(data.lastUpdated).toLocaleString(language === 'en' ? 'en-GB' : 'ja-JP')}</em></aside></section><nav class="insights-tabs" aria-label="${t('title')}">${Object.entries(labels).map(([key,label]) => `<button type="button" data-insights-view="${key}" class="${activeView === key ? 'active' : ''}">${label}</button>`).join('')}</nav><p class="insights-method">${activeView === 'tournament' ? t('readinessIntro') : t('completedOnly')}</p>${analysisGuide(activeView)}<section id="insights-content">${content}</section>`;
  }

  function sessionPlayerRecord(player, recorded, completed) {
    const recordedMatches = recorded.filter(match => match.player1Id === player.playerId || match.player2Id === player.playerId), currentMatches = completed.filter(match => match.player1Id === player.playerId || match.player2Id === player.playerId), current = summary(currentMatches,player.playerId), prior = playerMatches(player.playerId).filter(match => match.matchDate < selectedDate).slice(-5), priorStats = summary(prior,player.playerId), delta = currentMatches.length >= 2 && prior.length >= 3 ? current.average-priorStats.average : null, opponents = new Set(recordedMatches.map(match => opponentId(match,player.playerId)));
    return { player,recordedMatches,currentMatches,current,prior,priorStats,delta,opponents:opponents.size };
  }

  function renderSession() {
    const allDates = dates(); selectedDate = allDates.includes(selectedDate) ? selectedDate : allDates.at(-1) || '';
    const comparisonChoices=allDates.filter(date=>date!==selectedDate);comparisonDate=comparisonChoices.includes(comparisonDate)?comparisonDate:(comparisonChoices.filter(date=>date<selectedDate).at(-1)||comparisonChoices.at(-1)||'');
    const recorded = trainingMatches().filter(match => match.matchDate === selectedDate), completed = recorded.filter(isComplete), ids = [...new Set(recorded.flatMap(match => [match.player1Id,match.player2Id]))], map = playerMap(), rows = ids.map(id => sessionPlayerRecord(map.get(id) || {playerId:id,displayName:id},recorded,completed));
    const pairingKeys = new Set(completed.map(match => [match.player1Id,match.player2Id].sort().join('|'))), close = completed.filter(match => Math.abs(Number(match.player1Sets)-Number(match.player2Sets)) === 1);
    const latestThree = allDates.slice(-3), activeRecent = new Set(trainingMatches().filter(match => latestThree.includes(match.matchDate)).flatMap(match => [match.player1Id,match.player2Id])), stale = (data.players || []).filter(player => !activeRecent.has(player.playerId));
    const signals = [];
    rows.forEach(row => {
      if (row.recordedMatches.length === 1) signals.push({tone:'neutral',player:row.player,text:t('oneMatch')});
      const closeLosses = row.currentMatches.filter(match => !won(match,row.player.playerId) && Math.abs(scoreFor(match,row.player.playerId).own-scoreFor(match,row.player.playerId).other) === 1).length;
      if (closeLosses) signals.push({tone:'neutral',player:row.player,text:`${t('closeLoss')}: ${closeLosses}`});
      if (row.current.games >= 2 && row.current.average <= -2) signals.push({tone:'negative',player:row.player,text:`${t('decisiveLoss')}: ${signed(row.current.average)}`});
      if (row.delta !== null && row.delta >= .75) signals.push({tone:'positive',player:row.player,text:`${t('movementUp')}: ${signed(row.delta)}`});
      if (row.delta !== null && row.delta <= -.75) signals.push({tone:'negative',player:row.player,text:`${t('movementDown')}: ${signed(row.delta)}`});
    });
    signals.sort((left,right) => ({negative:0,positive:1,neutral:2}[left.tone]-{negative:0,positive:1,neutral:2}[right.tone]));
    const pairingRows = [...pairingKeys].map(key => { const [one,two]=key.split('|'), session=completed.filter(match => [match.player1Id,match.player2Id].sort().join('|')===key), history=completedMatches().filter(match => match.matchDate < selectedDate && [match.player1Id,match.player2Id].sort().join('|')===key), oneWins=session.filter(match => match.winnerId===one).length; return {one,two,session,history,oneWins}; }).sort((a,b) => b.history.length-a.history.length || b.session.length-a.session.length);
    const trendDates=allDates.filter(date=>date<=selectedDate).slice(-12), trendRecords=trendDates.map(date=>{const day=trainingMatches().filter(match=>match.matchDate===date),done=day.filter(isComplete),people=new Set(day.flatMap(match=>[match.player1Id,match.player2Id])),closeMatches=done.filter(match=>Math.abs(Number(match.player1Sets)-Number(match.player2Sets))===1);return {date,recorded:day.length,participants:people.size,completion:day.length?Math.round(done.length/day.length*100):0,close:done.length?Math.round(closeMatches.length/done.length*100):0};});
    const heatmapDates=allDates.filter(date=>date<=selectedDate).slice(-6),heatmapPlayers=rows.map(row=>row.player).sort((a,b)=>nameFor(a).localeCompare(nameFor(b),'ja')),heatmapPlayerIds=new Set(heatmapPlayers.map(player=>player.playerId)),heatmapMatches=trainingMatches().filter(match=>heatmapDates.includes(match.matchDate)&&heatmapPlayerIds.has(match.player1Id)&&heatmapPlayerIds.has(match.player2Id)),heatCounts=new Map();
    heatmapMatches.forEach(match=>{const key=[match.player1Id,match.player2Id].sort().join('|');heatCounts.set(key,(heatCounts.get(key)||0)+1);});
    const heatMax=Math.max(0,...heatCounts.values()),shortName=person=>(person?.displayName||person?.playerId||'-').slice(0,5),heatCell=(rowPlayer,columnPlayer)=>{if(rowPlayer.playerId===columnPlayer.playerId)return '<span class="heat-cell diagonal" aria-hidden="true"></span>';const count=heatCounts.get([rowPlayer.playerId,columnPlayer.playerId].sort().join('|'))||0,title=`${nameFor(rowPlayer)} vs ${nameFor(columnPlayer)} · ${count} ${language==='en'?'recorded matches':'登録試合'}`,level=count?Math.max(1,Math.ceil(count/Math.max(1,heatMax)*5)):0,profileId=String(rowPlayer.playerId).startsWith('LK-')?rowPlayer.playerId:String(columnPlayer.playerId).startsWith('LK-')?columnPlayer.playerId:'',opponentId=profileId===rowPlayer.playerId?columnPlayer.playerId:rowPlayer.playerId,content=`<b>${count||''}</b>`;return count&&profileId?`<a class="heat-cell level-${level}" href="player.html?id=${encodeURIComponent(profileId)}&opponent=${encodeURIComponent(opponentId)}#opponents" title="${escapeHtml(title)}" aria-label="${escapeHtml(title)}">${content}</a>`:`<span class="heat-cell level-${level}" title="${escapeHtml(title)}">${content}</span>`;};
    const heatmap=`<div class="pairing-heatmap-scroll"><div class="pairing-heatmap-grid" style="--heatmap-size:${heatmapPlayers.length}"><span class="heat-corner">VS</span>${heatmapPlayers.map(person=>`<span class="heat-column" title="${escapeHtml(nameFor(person))}">${escapeHtml(shortName(person))}</span>`).join('')}${heatmapPlayers.map(rowPlayer=>`<span class="heat-row" title="${escapeHtml(nameFor(rowPlayer))}">${escapeHtml(shortName(rowPlayer))}</span>${heatmapPlayers.map(columnPlayer=>heatCell(rowPlayer,columnPlayer)).join('')}`).join('')}</div></div>`;
    const workloadBands=[{label:'1',count:rows.filter(row=>row.recordedMatches.length===1).length},{label:'2–3',count:rows.filter(row=>row.recordedMatches.length>=2&&row.recordedMatches.length<=3).length},{label:'4–5',count:rows.filter(row=>row.recordedMatches.length>=4&&row.recordedMatches.length<=5).length},{label:'6+',count:rows.filter(row=>row.recordedMatches.length>=6).length}],maxWorkload=Math.max(1,...workloadBands.map(band=>band.count));
    const reflections=(data.sessionFeedback||[]).filter(item=>item.sessionDate===selectedDate).sort((a,b)=>(a.playerName||'').localeCompare(b.playerName||'','ja')),matchReflections=(data.matchFeedback||[]).filter(item=>item.matchType==='training'&&item.matchDate===selectedDate).sort((a,b)=>(a.playerName||'').localeCompare(b.playerName||'','ja')),average=field=>reflections.length?(reflections.reduce((total,item)=>total+Number(item[field]||0),0)/reflections.length).toFixed(1):'—';
    const comparisonMatches=trainingMatches().filter(match=>match.matchDate===comparisonDate),comparisonCompleted=comparisonMatches.filter(isComplete),comparisonIds=new Set(comparisonMatches.flatMap(match=>[match.player1Id,match.player2Id])),comparisonPairs=new Set(comparisonCompleted.map(match=>[match.player1Id,match.player2Id].sort().join('|'))),comparisonClose=comparisonCompleted.filter(match=>Math.abs(Number(match.player1Sets)-Number(match.player2Sets))===1),overlap=ids.filter(id=>comparisonIds.has(id));
    const workloadFor=(list,participantIds)=>{const counts=[...participantIds].map(id=>list.filter(match=>match.player1Id===id||match.player2Id===id).length);return [{label:'1',count:counts.filter(value=>value===1).length},{label:'2–3',count:counts.filter(value=>value>=2&&value<=3).length},{label:'4–5',count:counts.filter(value=>value>=4&&value<=5).length},{label:'6+',count:counts.filter(value=>value>=6).length}];},comparisonWorkload=workloadFor(comparisonMatches,comparisonIds),comparisonWorkloadMax=Math.max(1,...workloadBands.map(item=>item.count),...comparisonWorkload.map(item=>item.count));
    const metricDelta=(current,previous,suffix='')=>`${previous} → ${current}${suffix} (${current-previous>=0?'+':''}${current-previous}${suffix})`,sessionRecord=(data.sessions||[]).find(item=>item.sessionDate===selectedDate),comparisonRecord=(data.sessions||[]).find(item=>item.sessionDate===comparisonDate);
    const commonRows=overlap.map(id=>{const person=map.get(id)||{playerId:id,displayName:id},currentStats=summary(completed.filter(match=>match.player1Id===id||match.player2Id===id),id),previousStats=summary(comparisonCompleted.filter(match=>match.player1Id===id||match.player2Id===id),id);return {id,name:nameFor(person),current:currentStats.average,previous:previousStats.average,delta:currentStats.average-previousStats.average};}).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,18);
    const scorelineCount=(list,score)=>list.filter(match=>`${Math.max(Number(match.player1Sets),Number(match.player2Sets))}-${Math.min(Number(match.player1Sets),Number(match.player2Sets))}`===score).length,comparisonScorelines=['3-0','3-1','3-2'];
    const categories=[...new Set([...recorded,...comparisonMatches].flatMap(match=>[categoryOf(map.get(match.player1Id)),categoryOf(map.get(match.player2Id))]))].sort((a,b)=>a.localeCompare(b,'ja'));
    const categoryCell=(row,column)=>{const calculate=list=>{const matched=list.filter(match=>{const one=categoryOf(map.get(match.player1Id)),two=categoryOf(map.get(match.player2Id));return row===column?one===row&&two===column:(one===row&&two===column)||(one===column&&two===row);}),done=matched.filter(isComplete);return `${matched.length}/${done.length}`;};return `<span title="${escapeHtml(`${row} vs ${column} · ${language==='en'?'recorded/completed':'登録/完了'}`)}"><b>${calculate(recorded)}</b><small>${calculate(comparisonMatches)}</small></span>`;};
    const categoryMatrix=categories.length?`<div class="category-compare-matrix" style="--category-count:${categories.length}"><i></i>${categories.map(category=>`<strong>${escapeHtml(category)}</strong>`).join('')}${categories.map(row=>`<strong>${escapeHtml(row)}</strong>${categories.map(column=>categoryCell(row,column)).join('')}`).join('')}</div>`:`<p class="empty">${t('noData')}</p>`;
    const maxCalendar=Math.max(1,...allDates.map(date=>trainingMatches().filter(match=>match.matchDate===date).length)),calendar=`<div class="activity-calendar">${allDates.map(date=>{const count=trainingMatches().filter(match=>match.matchDate===date).length,level=Math.max(1,Math.ceil(count/maxCalendar*5));return `<button type="button" data-session-calendar-date="${date}" class="level-${level}${date===selectedDate?' selected':''}" title="${date} · ${count} ${language==='en'?'matches':'試合'}"><b>${date.slice(5)}</b><small>${count}</small></button>`;}).join('')}</div>`;
    const exactSeen=new Set(),possibleDuplicates=recorded.reduce((count,match)=>{const first=match.player1Id<=match.player2Id?`${match.player1Id}:${match.player1Sets}|${match.player2Id}:${match.player2Sets}`:`${match.player2Id}:${match.player2Sets}|${match.player1Id}:${match.player1Sets}`,key=`${match.matchDate}|${first}`;if(exactSeen.has(key))return count+1;exactSeen.add(key);return count;},0),missingSessionLinks=recorded.filter(match=>!match.sessionId).length,unusualScores=recorded.filter(match=>Number(match.player1Sets)>3||Number(match.player2Sets)>3).length;
    const metadata=(record,date)=>record?`<article><b>${escapeHtml(date)}</b><span><small>${t('venue')}</small>${escapeHtml(record.venue||'—')}</span><span><small>${t('sessionType')}</small>${escapeHtml(record.sessionType||'—')} · ${escapeHtml(record.matchFormat||'—')}</span><span><small>${t('coachGoal')}</small>${escapeHtml(record.coachGoal||'—')}</span><span><small>${t('coachNote')}</small>${escapeHtml(record.coachNote||'—')}</span><span><small>${t('source')}</small>${escapeHtml([record.source,record.verifiedAt].filter(Boolean).join(' · ')||'—')}</span></article>`:`<article class="unrecorded"><b>${escapeHtml(date)}</b><p>${t('metadataUnrecorded')}</p></article>`;
    const content = `<div class="insights-filter-bar comparison-filter"><label><span>${t('selectSession')}</span><select id="insights-session-date">${[...allDates].reverse().map(date => `<option value="${date}" ${date===selectedDate?'selected':''}>${date}</option>`).join('')}</select></label><label><span>${t('compareSession')}</span><select id="insights-comparison-date">${[...comparisonChoices].reverse().map(date=>`<option value="${date}" ${date===comparisonDate?'selected':''}>${date}</option>`).join('')}</select></label><button id="print-session-report" type="button">${t('printReport')}</button></div>
      <section class="session-report"><header class="session-report-title"><div><p>${t('sessionReport')}</p><h2>${selectedDate}</h2><span>${language==='en'?'Compared with':'比較'} ${comparisonDate||'—'}</span></div><p>${t('comparisonCaution')}</p></header><div class="session-metadata-compare">${metadata(sessionRecord,selectedDate)}${metadata(comparisonRecord,comparisonDate)}</div>
      <div class="insights-kpis"><article><small>${t('recorded')}</small><b>${recorded.length}</b><span>${t('complete')} ${completed.length} · ${t('incomplete')} ${recorded.length-completed.length}</span></article><article><small>${t('participants')}</small><b>${ids.length}</b><span>${language === 'en' ? 'with recorded matches' : '試合記録あり'}</span></article><article><small>${t('pairings')}</small><b>${pairingKeys.size}</b><span>${completed.length} ${t('matches').toLowerCase()}</span></article><article><small>${t('close')}</small><b>${completed.length ? Math.round(close.length/completed.length*100) : 0}%</b><span>${close.length} · 3–2 / 2–3</span></article></div>
      <div class="comparison-kpis"><span><small>${t('recorded')}</small><b>${metricDelta(recorded.length,comparisonMatches.length)}</b></span><span><small>${t('participants')}</small><b>${metricDelta(ids.length,comparisonIds.size)}</b></span><span><small>${t('pairings')} · ${language==='en'?'unique / repeats':'組数 / 再戦'}</small><b>${comparisonPairs.size}/${Math.max(0,comparisonCompleted.length-comparisonPairs.size)} → ${pairingKeys.size}/${Math.max(0,completed.length-pairingKeys.size)}</b></span><span><small>${t('participantOverlap')}</small><b>${overlap.length}</b></span><span><small>${t('close')}</small><b>${metricDelta(completed.length?Math.round(close.length/completed.length*100):0,comparisonCompleted.length?Math.round(comparisonClose.length/comparisonCompleted.length*100):0,'%')}</b></span></div>
      <section class="workload-comparison"><h3>${language==='en'?'Workload distribution comparison':'試合数分布比較'}</h3><div>${workloadBands.map((band,index)=>`<article><b>${band.label} ${language==='en'?'matches':'試合'}</b><span><small>${comparisonDate}</small><i><em style="width:${comparisonWorkload[index].count/comparisonWorkloadMax*100}%"></em></i><strong>${comparisonWorkload[index].count}</strong></span><span><small>${selectedDate}</small><i><em style="width:${band.count/comparisonWorkloadMax*100}%"></em></i><strong>${band.count}</strong></span></article>`).join('')}</div></section><div class="report-data-quality"><b>${language==='en'?'Data quality':'データ品質'}</b><span>${recorded.length-completed.length} ${t('incomplete')}</span><span>${missingSessionLinks} ${language==='en'?'without session ID':'セッションID未登録'}</span><span>${possibleDuplicates} ${language==='en'?'possible duplicates':'重複候補'}</span><span>${unusualScores} ${language==='en'?'unusual scores':'通常外スコア'}</span></div>
      <div class="comparison-chart-grid"><article class="chart-card"><h3>${t('scoreComparison')}</h3><canvas id="comparison-score-chart" role="img" aria-label="${escapeHtml(t('scoreComparison'))}"></canvas></article><article class="chart-card"><h3>${t('playerMovement')}</h3><canvas id="comparison-dumbbell-chart" role="img" aria-label="${escapeHtml(t('playerMovement'))}"></canvas></article></div>
      <section class="insights-panel category-comparison"><header><div><p>${t('categoryMatrix')}</p><small>${language==='en'?'Each cell: selected recorded/completed above; comparison below':'各セル：上段は選択日、下段は比較日の登録/完了'}</small></div></header>${categoryMatrix}</section><section class="insights-panel activity-calendar-panel"><header><div><p>${t('calendarActivity')}</p><small>${language==='en'?'Recorded match volume by training date':'練習日別の登録試合数'}</small></div></header>${calendar}</section></section>
      <article class="chart-card insights-trend-chart"><h3>${t('sessionTrend')}</h3><p>${t('trendNote')}</p><canvas id="insights-session-trend-chart" role="img" aria-label="${escapeHtml(t('trendNote'))}"></canvas></article>
      <section class="insights-panel workload-distribution"><header><div><p>${t('workloadDistribution')}</p><small>${selectedDate} · ${ids.length} ${language==='en'?'match participants':'試合参加選手'}</small></div></header><div>${workloadBands.map(band=>`<span><small>${band.label} ${language==='en'?'matches':'試合'}</small><i><b style="width:${band.count/maxWorkload*100}%"></b></i><strong>${band.count}</strong></span>`).join('')}</div></section>
      <section class="insights-panel session-reflections"><header><div><p>${t('reflections')}</p><small>${t('reflectionNote')}</small></div><a href="feedback.html?date=${encodeURIComponent(selectedDate)}">${t('addReflection')} →</a></header><div class="reflection-kpis"><span><small>${t('sessionReflections')}</small><b>${reflections.length}</b></span><span><small>${t('matchReflections')}</small><b>${matchReflections.length}</b></span><span><small>${t('effort')}</small><b>${average('effort')}</b></span><span><small>${t('confidenceLabel')}</small><b>${average('confidence')}</b></span></div><h3 class="reflection-group-title">${t('sessionReflections')}</h3><div class="session-reflection-list">${reflections.map(item=>`<article><header><a href="player.html?id=${encodeURIComponent(item.playerId)}">${escapeHtml(item.playerName||item.playerId)}</a><span>${t('effort')} <b>${item.effort}/5</b> · ${t('confidenceLabel')} <b>${item.confidence}/5</b></span></header><div><small>${t('wentWell')}</small><p>${escapeHtml(item.wentWell)}</p><small>${t('nextFocus')}</small><p>${escapeHtml(item.nextFocus)}</p></div></article>`).join('')||`<p class="empty">${t('noReflections')}</p>`}</div><h3 class="reflection-group-title">${t('matchReflections')}</h3><div class="session-reflection-list match-reflection-list">${matchReflections.map(item=>`<article><header><a href="player.html?id=${encodeURIComponent(item.playerId)}">${escapeHtml(item.playerName||item.playerId)}</a><span>${escapeHtml(item.score)} · ${escapeHtml(item.opponentName||item.opponentId)}</span></header><div><small>${t('whatWorked')}</small><p>${escapeHtml(item.whatWorked)}</p><small>${t('challenge')}</small><p>${escapeHtml(item.challenge)}</p><small>${t('nextPlan')}</small><p>${escapeHtml(item.nextPlan)}</p></div></article>`).join('')||`<p class="empty">${t('noReflections')}</p>`}</div></section>
      <div class="insights-session-grid"><section class="insights-panel insights-attention"><header><p>${t('attention')}</p><b>${signals.length}</b></header><div>${signals.slice(0,8).map(signal => `<a class="${signal.tone}" href="player.html?id=${encodeURIComponent(signal.player.playerId)}#matches"><strong>${escapeHtml(nameFor(signal.player))}</strong><span>${escapeHtml(signal.text)}</span></a>`).join('') || `<p class="empty">${t('noSignals')}</p>`}</div>${signals.length>8?`<p class="insights-result-note">${language==='en'?`Showing 8 highest-priority signals of ${signals.length}`:`優先度の高い8件を表示（全${signals.length}件）`}</p>`:''}${stale.length ? `<details><summary>${t('inactivePlayers')} · ${stale.length}</summary><div class="insights-chip-list">${stale.map(player => `<a href="player.html?id=${encodeURIComponent(player.playerId)}#matches">${escapeHtml(nameFor(player))}</a>`).join('')}</div></details>` : ''}</section><article class="chart-card insights-score-chart"><h3>${language === 'en' ? 'Session scoreline distribution' : 'セッションスコア内訳'}</h3><canvas id="insights-session-chart" role="img" aria-label="${language === 'en' ? 'Completed match scoreline distribution for the selected training date' : '選択した練習日の完了試合スコア内訳'}"></canvas></article></div>
      <section class="insights-panel"><header><div><p>${t('sessionPlayers')}</p><small>${selectedDate}</small></div></header><div class="insights-table-wrap"><table class="insights-table"><thead><tr><th>${language==='en'?'Player':'選手'}</th><th>${t('workload')}</th><th>${t('record')}</th><th>${t('setDiff')}</th><th>${t('change')}</th><th>${t('diversity')}</th></tr></thead><tbody>${rows.sort((a,b)=>b.recordedMatches.length-a.recordedMatches.length||b.current.average-a.current.average).map(row => `<tr><th><a href="player.html?id=${encodeURIComponent(row.player.playerId)}#matches">${escapeHtml(nameFor(row.player))}</a><small>${escapeHtml(categoryOf(row.player))}</small></th><td>${row.recordedMatches.length} / ${row.current.games}</td><td>${resultLabel(row.current.wins,row.current.losses)}</td><td class="${row.current.average>0?'positive':row.current.average<0?'negative':''}">${row.current.games?signed(row.current.average):'—'}</td><td>${row.delta===null?'—':signed(row.delta)}</td><td>${row.opponents}</td></tr>`).join('')}</tbody></table></div></section>
      <section class="insights-panel"><header><div><p>${t('recurring')}</p><small>${language==='en'?'Top 6 by prior meetings':'過去対戦数 上位6組'}</small></div></header><div class="insights-pairings">${pairingRows.slice(0,6).map(pair => { const one=map.get(pair.one)||{playerId:pair.one,displayName:pair.one},two=map.get(pair.two)||{playerId:pair.two,displayName:pair.two}; return `<article><div><a href="player.html?id=${encodeURIComponent(pair.one)}&opponent=${encodeURIComponent(pair.two)}#opponents">${escapeHtml(nameFor(one))}</a><i>VS</i><a href="player.html?id=${encodeURIComponent(pair.two)}&opponent=${encodeURIComponent(pair.one)}#opponents">${escapeHtml(nameFor(two))}</a></div><b>${pair.oneWins}-${pair.session.length-pair.oneWins}</b><small>${pair.history.length} ${t('priorMeetings')}</small></article>`; }).join('') || `<p class="empty">${t('noData')}</p>`}</div></section>
      <section class="insights-panel pairing-heatmap-panel"><header><div><p>${t('pairingHeatmap')}</p><small>${t('heatmapNote')}</small></div><b>${heatMax}<small>${t('maxRepeat')}</small></b></header><p class="heatmap-period">${heatmapDates.join(' · ')}</p>${heatmap}</section>
      <details class="insights-panel insights-match-details"><summary>${t('matches')} · ${recorded.length}</summary><div class="insights-match-list">${recorded.map(match => { const one=map.get(match.player1Id)||{displayName:match.player1Name},two=map.get(match.player2Id)||{displayName:match.player2Name},session=match.sessionId||(language==='en'?'Session ID not recorded':'セッションID未登録'),format=match.matchFormat||(language==='en'?'Format not recorded':'形式未登録'); return `<article class="${isComplete(match)?'':'incomplete'}"><small>${session} · ${format}</small><span><b>${escapeHtml(nameFor(one))}</b><strong>${match.player1Sets}-${match.player2Sets}</strong><b>${escapeHtml(nameFor(two))}</b></span></article>`; }).join('')}</div></details>`;
    app.innerHTML = shell(content); bindCommon();
    const updateShareUrl=()=>{const url=new URL(location.href);url.searchParams.set('session',selectedDate);if(comparisonDate)url.searchParams.set('compare',comparisonDate);else url.searchParams.delete('compare');url.hash='session';history.replaceState(null,'',url);};
    document.querySelector('#insights-session-date').onchange = event => { selectedDate=event.target.value; renderSession(); updateShareUrl(); };
    document.querySelector('#insights-comparison-date').onchange = event => { comparisonDate=event.target.value; renderSession(); updateShareUrl(); };
    document.querySelector('#print-session-report').onclick=()=>window.print();
    document.querySelectorAll('[data-session-calendar-date]').forEach(button=>button.onclick=()=>{selectedDate=button.dataset.sessionCalendarDate;renderSession();updateShareUrl();});
    const scorelines=['3-0','3-1','3-2'], values=scorelines.map(score => completed.filter(match => { const high=Math.max(Number(match.player1Sets),Number(match.player2Sets)),low=Math.min(Number(match.player1Sets),Number(match.player2Sets)); return `${high}-${low}`===score; }).length);
    comparisonScoreChart=new Chart(document.querySelector('#comparison-score-chart'),{type:'bar',data:{labels:[comparisonDate,selectedDate],datasets:comparisonScorelines.map((score,index)=>({label:score,data:[scorelineCount(comparisonCompleted,score),scorelineCount(completed,score)],backgroundColor:['#d6a516','#c18e13','#8c423a'][index],borderRadius:3}))},options:{maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{labels:{color:'#f6f0e2',boxWidth:12}}},scales:{x:{beginAtZero:true,stacked:true,ticks:{color:'#a5a198',precision:0},grid:{color:'rgba(246,240,226,.08)'}},y:{stacked:true,ticks:{color:'#f6f0e2'},grid:{display:false}}}}});
    comparisonDumbbellChart=new Chart(document.querySelector('#comparison-dumbbell-chart'),{type:'scatter',data:{datasets:commonRows.map((row,index)=>({label:row.name,data:[{x:row.previous,y:row.name},{x:row.current,y:row.name}],showLine:true,borderColor:row.delta>=0?'rgba(129,199,132,.75)':'rgba(198,106,97,.75)',backgroundColor:['#a5a198','#d6a516'],pointBackgroundColor:['#a5a198','#d6a516'],pointRadius:4,borderWidth:2}))},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:context=>`${context.dataset.label}: ${Number(context.raw.x).toFixed(1)}`}}},scales:{x:{title:{display:true,text:t('setDiff'),color:'#a5a198'},ticks:{color:'#a5a198'},grid:{color:'rgba(246,240,226,.08)'}},y:{type:'category',labels:commonRows.map(row=>row.name),ticks:{color:'#f6f0e2',font:{size:9}},grid:{display:false}}}}});
    sessionChart = new Chart(document.querySelector('#insights-session-chart'),{type:'bar',data:{labels:scorelines,datasets:[{data:values,backgroundColor:scorelines.map(score=>score.startsWith('3-')?'#d6a516':'#8c423a'),borderRadius:4}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:'#f6f0e2'},grid:{display:false}},y:{beginAtZero:true,ticks:{color:'#a5a198',precision:0},grid:{color:'rgba(246,240,226,.08)'}}}}});
    sessionTrendChart = new Chart(document.querySelector('#insights-session-trend-chart'),{type:'bar',data:{labels:trendDates,datasets:[{label:language==='en'?'Recorded matches':'登録試合',data:trendRecords.map(record=>record.recorded),backgroundColor:'rgba(214,165,22,.72)',borderRadius:3,yAxisID:'count'},{label:language==='en'?'Match participants':'試合参加選手',data:trendRecords.map(record=>record.participants),backgroundColor:'rgba(246,240,226,.3)',borderRadius:3,yAxisID:'count'},{type:'line',label:language==='en'?'Completion rate':'完了率',data:trendRecords.map(record=>record.completion),borderColor:'#f6f0e2',backgroundColor:'#f6f0e2',borderDash:[5,4],pointRadius:3,tension:.25,yAxisID:'rate'},{type:'line',label:language==='en'?'Close-match rate':'接戦率',data:trendRecords.map(record=>record.close),borderColor:'#c66a61',backgroundColor:'#c66a61',pointRadius:3,tension:.25,yAxisID:'rate'}]},options:{maintainAspectRatio:false,interaction:{mode:'index',intersect:false},onClick:(event,elements)=>{if(!elements.length)return;selectedDate=trendDates[elements[0].index];renderSession();},onHover:(event,elements)=>{if(event.native?.target)event.native.target.style.cursor=elements.length?'pointer':'default';},plugins:{legend:{labels:{color:'#f6f0e2',boxWidth:12,font:{size:10}}},tooltip:{callbacks:{footer:()=>language==='en'?'Click to open this training date':'クリックしてこの練習日を表示',label:context=>context.dataset.yAxisID==='rate'?`${context.dataset.label}: ${context.raw}%`:`${context.dataset.label}: ${context.raw}`}}},scales:{x:{ticks:{color:'#a5a198',maxRotation:45,minRotation:0},grid:{display:false}},count:{beginAtZero:true,position:'left',ticks:{color:'#a5a198'},grid:{color:'rgba(246,240,226,.08)'}},rate:{beginAtZero:true,max:100,position:'right',ticks:{color:'#c9b46d',callback:value=>`${value}%`},grid:{drawOnChartArea:false}}}}});
  }

  function growthRow(record) {
    const p=record.player, scorelines=['3-0','3-1','3-2','2-3','1-3','0-3'];
    const scoreCount=scorelines.map(score => record.last10.filter(match => { const s=scoreFor(match,p.playerId); return `${s.own}-${s.other}`===score; }).length);
    const matchesPerSession=record.sessions?record.current.games/record.sessions:0,winsPerSession=record.sessions?record.current.wins/record.sessions:0,mix=record.categoryMix.slice(0,3).map(([category,count])=>`${category} ${count}`).join(' · ')||'—';
    return `<article class="growth-row" data-name="${escapeHtml(`${p.displayName||''} ${p.englishName||''} ${p.playerId}`.toLowerCase())}" data-category="${escapeHtml(p.schoolLevel||'')}"><header><div><a href="player.html?id=${encodeURIComponent(p.playerId)}#matches">${escapeHtml(nameFor(p))}</a><small>${escapeHtml(categoryOf(p))} · ${record.all.length} ${language==='en'?'completed matches':'完了試合'}</small></div><span class="signal ${record.signal}">${t(record.signal)}</span></header><div class="growth-metrics"><span><small>${t('last10')}</small><b>${resultLabel(record.current.wins,record.current.losses)}</b><em>${t('setDiff')} ${signed(record.current.average)}</em></span><span><small>${t('change')}</small><b>${record.delta===null?'—':signed(record.delta)}</b><em>${t('confidence')} ${confidence(record.last10.length)}</em></span><span><small>${t('diversity')}</small><b>${record.opponents}</b><em>${record.sessions} ${t('sessions')}</em></span><span><small>${t('normalized')}</small><b>${matchesPerSession.toFixed(1)}</b><em>${winsPerSession.toFixed(1)} ${language==='en'?'wins / day':'勝 / 日'}</em></span></div><div class="growth-context"><span><small>${t('activity')}</small><b>${record.activeDates} / ${record.recentSessionCount || '—'}</b></span><span><small>${t('opponentMix')}</small><b>${escapeHtml(mix)}</b></span></div><div class="growth-scorelines">${scorelines.map((score,index)=>`<span class="${score.startsWith('3-')?'win':'loss'}"><b>${score}</b><i>${scoreCount[index]}</i></span>`).join('')}</div></article>`;
  }

  function renderGrowth() {
    const records=(data.players||[]).map(growthRecord), sampled=records.filter(record=>record.last10.length>=10), improving=records.filter(record=>record.signal==='improving'), limited=records.filter(record=>record.last10.length<5), latestThree=dates().slice(-3), recentIds=new Set(trainingMatches().filter(match=>latestThree.includes(match.matchDate)).flatMap(match=>[match.player1Id,match.player2Id])), inactive=records.filter(record=>!recentIds.has(record.player.playerId));
    const categories=[...new Map((data.players||[]).map(player=>[player.schoolLevel||'',categoryOf(player)])).entries()];
    const signalOrder={improving:0,stable:1,declining:2,more:3}, sorted=[...records].sort((a,b)=>signalOrder[a.signal]-signalOrder[b.signal]||b.last10.length-a.last10.length||nameFor(a.player).localeCompare(nameFor(b.player),'ja'));
    const content=`<div class="insights-filter-bar growth-filters"><label><span>${t('playerSearch')}</span><input id="growth-search" type="search" value="${escapeHtml(growthSearch)}" placeholder="${t('playerSearch')}" /></label><label><span>${language==='en'?'Category':'カテゴリ'}</span><select id="growth-category"><option value="">${t('allCategories')}</option>${categories.map(([value,label])=>`<option value="${escapeHtml(value)}" ${growthCategory===value?'selected':''}>${escapeHtml(label)}</option>`).join('')}</select></label></div><p class="growth-method">${t('growthIntro')}</p>
      <div class="insights-kpis"><article><small>${t('sampledPlayers')}</small><b>${sampled.length}</b><span>${language==='en'?'10 completed matches':'完了10試合'}</span></article><article><small>${t('improvingPlayers')}</small><b>${improving.length}</b><span>≥ +0.5 ${t('setDiff')}</span></article><article><small>${t('limitedPlayers')}</small><b>${limited.length}</b><span>&lt; 5 ${language==='en'?'matches':'試合'}</span></article><article><small>${t('inactivePlayers')}</small><b>${inactive.length}</b><span>${latestThree.join(' · ')}</span></article></div><section class="growth-list"></section><button id="growth-load-more" class="progressive-load" type="button"></button>`;
    app.innerHTML=shell(content); bindCommon();
    const list=document.querySelector('.growth-list'),moreButton=document.querySelector('#growth-load-more');
    const paint=()=>{const filtered=sorted.filter(record=>{const haystack=`${record.player.displayName||''} ${record.player.englishName||''} ${record.player.playerId}`.toLowerCase();return(!growthSearch||haystack.includes(growthSearch.toLowerCase()))&&(!growthCategory||record.player.schoolLevel===growthCategory);});list.innerHTML=filtered.slice(0,growthLimit).map(growthRow).join('')||`<p class="empty">${t('noData')}</p>`;const remaining=Math.max(0,filtered.length-growthLimit);moreButton.hidden=!remaining;moreButton.textContent=language==='en'?`Show ${Math.min(growthPageSize,remaining)} more · ${remaining} remaining`:`さらに${Math.min(growthPageSize,remaining)}件表示 · 残り${remaining}件`;};
    document.querySelector('#growth-search').oninput=event=>{growthSearch=event.target.value.trim();growthLimit=growthPageSize;paint();};
    document.querySelector('#growth-category').onchange=event=>{growthCategory=event.target.value;growthLimit=growthPageSize;paint();};
    moreButton.onclick=()=>{growthLimit+=growthPageSize;paint();}; paint();
  }

  function renderTournamentReadiness() {
    const tournaments=new Map((data.tournaments||[]).map(item=>[item.tournamentId,item])), progress=data.tournamentProgress||[], people=new Map([...(data.players||[]).map(item=>[item.playerId,item]),...(data.externalOpponents||[]).map(item=>[item.externalOpponentId,item])]), training=completedMatches(), eventMatches=(data.tournamentMatches||[]).filter(isComplete);
    const entries=progress.filter(item=>String(item.playerId||'').startsWith('LK-')).sort((a,b)=>(tournaments.get(b.tournamentId)?.date||'').localeCompare(tournaments.get(a.tournamentId)?.date||'')||String(a.division).localeCompare(String(b.division),'ja'));
    const pairMatches=(list,one,two)=>list.filter(match=>(match.player1Id===one&&match.player2Id===two)||(match.player2Id===one&&match.player1Id===two));
    const cards=entries.map(entry=>{
      const tournament=tournaments.get(entry.tournamentId)||{name:entry.tournamentId}, player=people.get(entry.playerId)||{playerId:entry.playerId,displayName:entry.playerName||entry.playerId}, field=progress.filter(item=>item.tournamentId===entry.tournamentId&&item.division===entry.division&&item.playerId!==entry.playerId), known=field.map(item=>{const trainingRecord=pairMatches(training,entry.playerId,item.playerId),eventRecord=pairMatches(eventMatches,entry.playerId,item.playerId),matches=[...trainingRecord,...eventRecord];return {item,trainingRecord,eventRecord,matches,stats:summary(matches,entry.playerId)};}).filter(record=>record.matches.length).sort((a,b)=>b.matches.length-a.matches.length), priority=field.filter(item=>checked(item.recommended)||checked(item.qualified)).slice(0,6), recent=growthRecord(player), coverage=field.length?Math.round(known.length/field.length*100):0;
      const knownRows=known.slice(0,6).map(record=>{const person=people.get(record.item.playerId)||{displayName:record.item.playerName||record.item.playerId},sources=[];if(record.trainingRecord.length)sources.push(`${language==='en'?'training':'練習'} ${record.trainingRecord.length}`);if(record.eventRecord.length)sources.push(`${language==='en'?'event':'大会'} ${record.eventRecord.length}`);return `<button type="button" data-shared-h2h-player="${escapeHtml(entry.playerId)}" data-shared-h2h-opponent="${escapeHtml(record.item.playerId)}">${escapeHtml(nameFor(person))}<small>${resultLabel(record.stats.wins,record.stats.losses)} · ${sources.join(' / ')}</small></button>`;}).join('');
      return `<article class="readiness-workspace-card"><header><div><p>${escapeHtml(tournament.name||tournament.nameJa||entry.tournamentId)}</p><h2><a href="player.html?id=${encodeURIComponent(entry.playerId)}#overview">${escapeHtml(nameFor(player))}</a></h2><small>${escapeHtml(entry.division||'')} · ${escapeHtml(tournament.date||'')}</small></div><span>${coverage}%<small>${t('coverage')}</small></span></header><div class="readiness-workspace-metrics"><span><small>${t('field')}</small><b>${field.length}</b></span><span><small>${t('known')}</small><b>${known.length}</b></span><span><small>${t('missing')}</small><b>${field.length-known.length}</b></span><span><small>${t('recentForm')}</small><b>${resultLabel(recent.current.wins,recent.current.losses)}</b></span></div><section><h3>${t('known')}</h3><div class="insights-chip-list readiness-known">${knownRows||'—'}</div></section><section><h3>${t('priority')}</h3><div class="insights-chip-list">${priority.map(item=>{const person=people.get(item.playerId)||{displayName:item.playerName||item.playerId};return `<span>${escapeHtml(nameFor(person))}<small>${checked(item.recommended)?(language==='en'?'Recommended':'推薦'):(language==='en'?'Representative':'代表')}</small></span>`;}).join('')||'—'}</div></section></article>`;
    });
    const initialLimit=6;
    app.innerHTML=shell(`<div class="readiness-toolbar"><a href="tournament.html">${t('openTournament')} →</a></div><section class="readiness-workspace">${cards.slice(0,initialLimit).join('')||`<p class="empty">${t('noTournaments')}</p>`}</section>${cards.length>initialLimit?`<button id="readiness-load-more" class="progressive-load" type="button">${language==='en'?`Show ${cards.length-initialLimit} more`:`さらに${cards.length-initialLimit}件表示`}</button>`:''}`); bindCommon();
    document.querySelector('#readiness-load-more')?.addEventListener('click',event=>{document.querySelector('.readiness-workspace').innerHTML=cards.join('');event.currentTarget.remove();bindCommon();});
  }

  function bindCommon() {
    document.documentElement.lang=language;
    document.querySelector('#language-toggle').textContent=language==='en'?'日本語':'ENGLISH';
    const tournamentNav=document.querySelector('#nav-tournaments'),insightsNav=document.querySelector('#nav-insights'),maintenanceNav=document.querySelector('#nav-maintenance');
    const homeNav=document.querySelector('#insights-nav-home'),playersNav=document.querySelector('#insights-nav-players'),sessionsNav=document.querySelector('#insights-nav-sessions');
    if(homeNav)homeNav.textContent=language==='en'?'Home':'ホーム';
    if(playersNav)playersNav.textContent=language==='en'?'Players':'選手';
    if(sessionsNav)sessionsNav.textContent=language==='en'?'Sessions':'セッション';
    if(tournamentNav)tournamentNav.textContent=language==='en'?'Tournaments':'大会';
    if(insightsNav)insightsNav.textContent=language==='en'?'Training Insights':'練習分析';
    if(maintenanceNav)maintenanceNav.textContent=language==='en'?'Data Maintenance':'データメンテナンス';
    document.querySelectorAll('[data-insights-view]').forEach(button=>button.onclick=()=>{activeView=button.dataset.insightsView;history.replaceState(null,'',`#${activeView}`);render();});
    document.querySelectorAll('[data-shared-h2h-player]').forEach(button=>button.onclick=()=>window.LKHeadToHead?.open({data,playerId:button.dataset.sharedH2hPlayer,opponentId:button.dataset.sharedH2hOpponent,language}));
  }
  function render() {
    if (sessionChart) { sessionChart.destroy(); sessionChart=null; }
    if (sessionTrendChart) { sessionTrendChart.destroy(); sessionTrendChart=null; }
    if (comparisonScoreChart) { comparisonScoreChart.destroy(); comparisonScoreChart=null; }
    if (comparisonDumbbellChart) { comparisonDumbbellChart.destroy(); comparisonDumbbellChart=null; }
    if (!['session','growth','tournament'].includes(activeView)) activeView='session';
    if (activeView==='growth') renderGrowth(); else if (activeView==='tournament') renderTournamentReadiness(); else renderSession();
  }
  document.querySelector('#language-toggle').onclick=()=>{language=language==='en'?'ja':'en';localStorage.setItem('lk-language',language);render();};
  document.querySelector('#menu-toggle').onclick=event=>{const nav=document.querySelector('.site-header nav');const open=nav.classList.toggle('open');event.currentTarget.setAttribute('aria-expanded',String(open));};
  window.addEventListener('hashchange',()=>{activeView=location.hash.slice(1)||'session';render();});
  window.LKData.loadPublicData().then(result=>{data=result;if(!dates().includes(selectedDate))selectedDate=dates().at(-1)||'';render();}).catch(error=>{app.innerHTML=`<section class="insights-loading"><p class="empty">${escapeHtml(error.message)}</p></section>`;});
})();
