const API_URL = 'https://script.google.com/macros/s/AKfycbx6IaN9YT2a4bv_8W76qtNwkFCjZ_-mODBEMTK9IiJlSi91UCIgJ56MQ4WJqeKK3TiUvA/exec?action=publicData';
Chart.register({ id: 'valueLabels', afterDatasetsDraw(chart) { const { ctx } = chart; ctx.save(); ctx.fillStyle = '#f6f0e2'; ctx.font = '700 11px Barlow Condensed'; ctx.textAlign = 'center'; chart.data.datasets.forEach((dataset, datasetIndex) => chart.getDatasetMeta(datasetIndex).data.forEach((element, index) => { const value = dataset.data[index]; if (value === null || value === undefined) return; const point = element.tooltipPosition(); const isBar = chart.getDatasetMeta(datasetIndex).type === 'bar'; ctx.fillText(Math.abs(value), point.x, isBar ? (value < 0 ? point.y + 13 : point.y - 7) : point.y - 8); })); ctx.restore(); } });
const playerId = new URLSearchParams(location.search).get('id');
let data, player, matches, language = localStorage.getItem('lk-language') || 'en', profileCharts = [];
const words = { en: { profile:'PLAYER PROFILE', wins:'WINS', losses:'LOSSES', rate:'WIN RATE', diff:'SET DIFF.', performance:'CLUB TRAINING PERFORMANCE', timeline:'Match-Day Timeline', timelineChart:'Matches, Wins & Losses by Date', career:'Career Snapshot', insight:'OPPONENT INSIGHT', matchup:'Monthly & Yearly Matchups', archive:'MATCH ARCHIVE', history:'Historic Training Matches', monthly:'Latest Month', yearly:'Latest Year', played:'Most Played', beat:'Most Wins Against', lost:'Most Losses Against', matches:'matches', win:'WIN', loss:'LOSS', h2h:'HEAD TO HEAD', allPlayers:'← All players' }, ja: { profile:'選手プロフィール', wins:'勝利', losses:'敗戦', rate:'勝率', diff:'セット差', performance:'クラブ練習成績', timeline:'試合日別タイムライン', timelineChart:'日別の試合数・勝敗', career:'通算スナップショット', insight:'対戦相手分析', matchup:'月間・年間対戦成績', archive:'試合アーカイブ', history:'練習試合履歴', monthly:'直近月', yearly:'直近年', played:'対戦数上位', beat:'勝利数上位', lost:'敗戦数上位', matches:'試合', win:'勝ち', loss:'負け', h2h:'直接対決', allPlayers:'← 選手一覧' } };
const t = key => words[language][key];
const eventType = match => /club|training|練習/i.test(`${match.event} ${match.division}`) ? 'Training' : 'Tournament';
const nameFor = item => language === 'en' && item.englishName ? item.englishName : item.displayName;
const playerMap = () => new Map(data.players.map(item => [item.playerId, item]));
function opponentRows(period) {
  const records = new Map();
  matches.filter(match => match.matchDate.startsWith(period)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id; const opponent = playerMap().get(opponentId) || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }; const record = records.get(opponentId) || { opponent, played:0, won:0, lost:0 }; record.played++; if (match.winnerId === playerId) record.won++; else if (match.winnerId) record.lost++; records.set(opponentId, record); });
  return [...records.values()];
}
function opponentList(entries, key) { return entries.sort((a,b) => b[key] - a[key] || b.played - a.played).slice(0,5).map(entry => `<li><b><a class="player-link" href="player.html?id=${entry.opponent.playerId}">${nameFor(entry.opponent)}</a></b><span>${entry.played} ${t('matches')} · ${entry.won}W-${entry.lost}L</span><aside class="record-bar"><i style="width:${entry.won / entry.played * 100}%"></i><b style="width:${entry.lost / entry.played * 100}%"></b></aside></li>`).join('') || '<li>-</li>'; }
function openHeadToHead(matchId) {
  const match = matches.find(item => item.matchId === matchId), map = playerMap(), opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, opponent = map.get(opponentId) || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name };
  const history = matches.filter(item => (item.player1Id === playerId && item.player2Id === opponentId) || (item.player2Id === playerId && item.player1Id === opponentId));
  const wins = history.filter(item => item.winnerId === playerId).length;
  document.querySelector('#head-to-head-content').innerHTML = `<p class="eyebrow">${t('h2h')}</p><h2>${nameFor(player)} <em>${wins} - ${history.filter(item => item.winnerId === opponentId).length}</em> ${nameFor(opponent)}</h2><div class="h2h-history">${history.map(item => `<div><span>${item.matchDate}</span><strong>${item.player1Sets}-${item.player2Sets}</strong></div>`).join('')}</div>`;
  document.querySelector('#head-to-head').showModal();
}
function render() {
  profileCharts.forEach(chart => chart.destroy()); profileCharts = [];
  const won = matches.filter(match => match.winnerId === playerId).length, lost = matches.filter(match => match.winnerId && match.winnerId !== playerId).length, sets = matches.reduce((total, match) => total + (match.player1Id === playerId ? match.player1Sets - match.player2Sets : match.player2Sets - match.player1Sets), 0), dates = [...new Set(matches.map(match => match.matchDate))].sort();
  document.documentElement.lang = language; document.querySelector('#language-toggle').textContent = language === 'en' ? '日本語' : 'ENGLISH'; document.querySelector('.back-link').textContent = t('allPlayers');
  document.querySelector('#profile-hero').innerHTML = `<div><p class="eyebrow">${t('profile')}</p><span class="player-id">${player.playerId}</span><h1>${nameFor(player)}</h1><p class="hero-ja">${player.displayName}</p><p class="profile-details">${[player.schoolLevel, player.gender, player.playingHand, player.grip, player.playingStyle].filter(Boolean).join(' · ') || 'Little Kings Table Tennis Club'}</p></div><div class="profile-record"><strong>${won}<small>${t('wins')}</small></strong><strong>${lost}<small>${t('losses')}</small></strong><strong>${matches.length ? Math.round(won / matches.length * 100) : 0}%<small>${t('rate')}</small></strong><strong>${sets > 0 ? '+' : ''}${sets}<small>${t('diff')}</small></strong></div>`;
  [['#performance-kicker','performance'],['#timeline-title','timeline'],['#timeline-chart-title','timelineChart'],['#career-title','career'],['#opponent-kicker','insight'],['#opponent-title','matchup'],['#archive-kicker','archive'],['#archive-title','history']].forEach(([selector,key]) => document.querySelector(selector).textContent = t(key));
  const dateWins = dates.map(date => matches.filter(match => match.matchDate === date && match.winnerId === playerId).length), dateLosses = dates.map(date => matches.filter(match => match.matchDate === date && match.winnerId && match.winnerId !== playerId).length);
  profileCharts.push(new Chart(document.querySelector('#monthly-chart'), { type:'bar', data:{ labels:dates, datasets:[{label:t('wins'),data:dateWins,backgroundColor:'#d6a516'},{label:t('losses'),data:dateLosses.map(value => -value),backgroundColor:'#8c423a'},{type:'line',label:'Net W-L',data:dateWins.map((value,index) => value-dateLosses[index]),borderColor:'#f6f0e2',backgroundColor:'#f6f0e2',pointBackgroundColor:'#f6f0e2',pointRadius:4,tension:.25}]}, options:{scales:{x:{ticks:{color:'#f6f0e2'},grid:{display:false}},y:{ticks:{color:'#a5a198'},grid:{color:'rgba(246,240,226,.1)'}}},plugins:{legend:{labels:{color:'#f6f0e2'}}}} }));
  profileCharts.push(new Chart(document.querySelector('#career-chart'), { type:'doughnut', data:{labels:[t('wins'),t('losses')],datasets:[{data:[won,lost],backgroundColor:['#d6a516','#5e5b55'],borderWidth:0}]},options:{plugins:{legend:{labels:{color:'#f6f0e2'}}},cutout:'68%'} }));
  const latestMonth = dates.at(-1)?.slice(0,7) || '', latestYear = dates.at(-1)?.slice(0,4) || '', block = (label, period) => { const rows = opponentRows(period); return `<article><h3>${label}: ${period}</h3><div class="opponent-columns"><section><h4>${t('played')}</h4><ul>${opponentList(rows,'played')}</ul></section><section><h4>${t('beat')}</h4><ul>${opponentList(rows,'won')}</ul></section><section><h4>${t('lost')}</h4><ul>${opponentList(rows,'lost')}</ul></section></div></article>`; }; document.querySelector('#opponent-stats').innerHTML = block(t('monthly'),latestMonth) + block(t('yearly'),latestYear);
  document.querySelector('#profile-matches').innerHTML = [...dates].reverse().map(date => { const day = matches.filter(match => match.matchDate === date), dayWins = day.filter(match => match.winnerId === playerId).length, dayLosses = day.filter(match => match.winnerId && match.winnerId !== playerId).length, decided = dayWins + dayLosses; return `<section class="match-date-group"><header><strong>${date}</strong><span>${day.length} ${t('matches')} · ${dayWins}W-${dayLosses}L · ${decided ? Math.round(dayWins / decided * 100) : 0}%</span><aside class="record-bar"><i style="width:${decided ? dayWins / decided * 100 : 0}%"></i><b style="width:${decided ? dayLosses / decided * 100 : 0}%"></b></aside></header><div class="match-list">${day.map(match => { const opponent = match.player1Id === playerId ? match.player2Name : match.player1Name, score = match.player1Id === playerId ? `${match.player1Sets} - ${match.player2Sets}` : `${match.player2Sets} - ${match.player1Sets}`, result = match.winnerId === playerId ? 'win' : 'loss'; return `<button class="match-card result-${result}" data-match-id="${match.matchId}"><div class="result-label">${t(result)}</div><div class="match-score"><span class="match-player ${result === 'win' ? 'winner' : ''}">${nameFor(player)}</span><strong class="score">${score}</strong><span class="match-player">${opponent}</span></div></button>`; }).join('')}</div></section>`; }).join('');
}
fetch('./public-data.json').then(response => response.ok ? response.json() : Promise.reject()).catch(() => fetch(API_URL).then(response => response.json())).then(result => { data=result; player=data.players.find(item => item.playerId === playerId); if (!player) throw Error(); matches=data.matches.filter(match => (match.player1Id===playerId || match.player2Id===playerId) && eventType(match)==='Training').sort((a,b)=>b.matchDate.localeCompare(a.matchDate)); document.title=`${player.displayName} | Little Kings`; render(); }).catch(() => document.querySelector('#profile-hero').innerHTML='<div class="loading">Unable to load this player profile.</div>');
document.querySelector('#language-toggle').onclick=()=>{language=language==='en'?'ja':'en';localStorage.setItem('lk-language',language);render();}; document.addEventListener('click',event=>{const card=event.target.closest('.match-card');if(card?.dataset.matchId)openHeadToHead(card.dataset.matchId);if(event.target.closest('.modal-close'))document.querySelector('#head-to-head').close();});
