const API_URL = 'https://script.google.com/macros/s/AKfycbx6IaN9YT2a4bv_8W76qtNwkFCjZ_-mODBEMTK9IiJlSi91UCIgJ56MQ4WJqeKK3TiUvA/exec?action=publicData';
Chart.register({ id: 'zeroLine', beforeDatasetsDraw(chart) { if (chart.canvas.id !== 'monthly-chart') return; const y = chart.scales.y.getPixelForValue(0), { ctx, chartArea } = chart; ctx.save(); ctx.strokeStyle = '#f6f0e2'; ctx.lineWidth = 1.5; ctx.setLineDash([5,4]); ctx.beginPath(); ctx.moveTo(chartArea.left,y); ctx.lineTo(chartArea.right,y); ctx.stroke(); ctx.restore(); } }, { id: 'valueLabels', afterDatasetsDraw(chart) { const { ctx } = chart; ctx.save(); ctx.fillStyle = '#f6f0e2'; ctx.font = '700 11px Barlow Condensed'; ctx.textAlign = 'center'; chart.data.datasets.forEach((dataset, datasetIndex) => { if (dataset.hideValueLabels) return; chart.getDatasetMeta(datasetIndex).data.forEach((element, index) => { const value = dataset.data[index]; if (value === null || value === undefined) return; const point = element.tooltipPosition(), isBar = chart.getDatasetMeta(datasetIndex).type === 'bar', label = dataset.showSignedLabels ? value : Math.abs(value); ctx.fillText(label, point.x, isBar ? (value < 0 ? point.y + 13 : point.y - 7) : point.y - 8); }); }); ctx.restore(); } });
const playerId = new URLSearchParams(location.search).get('id'), requestedOpponentId = new URLSearchParams(location.search).get('opponent');
let data, player, matches, language = localStorage.getItem('lk-language') || 'ja', monthlyIndex = 0, yearlyIndex = 0, statsMonthStart = 0, statsOverallPeriod = 'all', profileCharts = [];
const words = { en: { profile:'PLAYER PROFILE', wins:'WINS', losses:'LOSSES', rate:'WIN RATE', diff:'SET DIFF.', performance:'CLUB TRAINING PERFORMANCE', timeline:'Match-Day Timeline', timelineChart:'Matches, Wins & Losses by Date', career:'Career Snapshot', periodStats:'MATCH STATISTICS', periodStatsTitle:'Monthly, Yearly & All-Time', rank:'Rank', latestMonth:'Latest Month', latestYear:'Latest Year', insight:'OPPONENT INSIGHT', matchup:'Monthly & Yearly Matchups', archive:'MATCH ARCHIVE', history:'Historic Training Matches', monthly:'Monthly', yearly:'Yearly', allTime:'All-Time', played:'Most Played', beat:'Most Wins Against', lost:'Most Losses Against', matches:'matches', training:'Training', win:'WIN', loss:'LOSS', incomplete:'INCOMPLETE', net:'Net W-L', cumulativeNet:'Cumulative Net W-L', h2h:'HEAD TO HEAD', allPlayers:'← All players' }, ja: { profile:'選手プロフィール', wins:'勝利', losses:'敗戦', rate:'勝率', diff:'セット差', performance:'クラブ練習成績', timeline:'試合日別タイムライン', timelineChart:'日別の試合数・勝敗', career:'通算スナップショット', periodStats:'試合スタッツ', periodStatsTitle:'月間・年間・通算成績', rank:'順位', latestMonth:'直近月', latestYear:'直近年', insight:'対戦相手分析', matchup:'月間・年間対戦成績', archive:'試合アーカイブ', history:'練習試合履歴', monthly:'月間', yearly:'年間', allTime:'通算', played:'対戦数上位', beat:'勝利数上位', lost:'敗戦数上位', matches:'試合', training:'練習試合', win:'勝ち', loss:'負け', incomplete:'未完了', net:'勝敗差', cumulativeNet:'累積勝敗差', h2h:'直接対決', allPlayers:'← 選手一覧' } };
const t = key => words[language][key];
const eventType = match => /club|training|練習/i.test(`${match.event} ${match.division}`) ? 'Training' : 'Tournament';
const isComplete = match => Number(match.player1Sets) >= 3 || Number(match.player2Sets) >= 3;
const nameFor = item => language === 'en' && item.englishName ? `${item.displayName} | ${item.englishName}` : item.displayName;
const playerMap = () => new Map(data.players.map(item => [item.playerId, item]));
function opponentRows(period) {
  const records = new Map();
  matches.filter(match => isComplete(match) && match.matchDate.startsWith(period)).forEach(match => { const opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id; const opponent = playerMap().get(opponentId) || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }; const record = records.get(opponentId) || { opponent, played:0, won:0, lost:0 }; record.played++; if (match.winnerId === playerId) record.won++; else if (match.winnerId) record.lost++; records.set(opponentId, record); });
  return [...records.values()];
}
function opponentList(entries, key) { return entries.sort((a,b) => b[key] - a[key] || b.played - a.played).slice(0,5).map(entry => `<li><b><a class="player-link" href="player.html?id=${entry.opponent.playerId}">${nameFor(entry.opponent)}</a></b><span>${entry.played} ${t('matches')} · ${entry.won}W-${entry.lost}L</span><aside class="record-bar"><i style="width:${entry.won / entry.played * 100}%"></i><b style="width:${entry.lost / entry.played * 100}%"></b></aside></li>`).join('') || '<li>-</li>'; }
function periodStatCard(period, selected) {
  const wins = selected.filter(match => match.winnerId === playerId).length, losses = selected.filter(match => match.winnerId && match.winnerId !== playerId).length, sets = selected.reduce((total, match) => total + (match.player1Id === playerId ? match.player1Sets - match.player2Sets : match.player2Sets - match.player1Sets), 0), rate = selected.length ? Math.round(wins / selected.length * 100) : 0, category = player.schoolLevel || '', records = new Map();
  data.matches.filter(match => eventType(match) === 'Training' && isComplete(match) && (period === 'all' || match.matchDate.startsWith(period))).forEach(match => [[match.player1Id, match.winnerId === match.player1Id], [match.player2Id, match.winnerId === match.player2Id]].forEach(([id, won]) => { if ((playerMap().get(id)?.schoolLevel || '') !== category) return; const record = records.get(id) || { id, wins:0, games:0 }; record.games++; if (won) record.wins++; records.set(id, record); })); const ranked = [...records.values()].sort((left,right) => right.wins / right.games - left.wins / left.games || right.games - left.games || right.wins - left.wins), rank = ranked.findIndex(record => record.id === playerId) + 1, title = period === 'all' ? t('allTime') : period;
  return `<article class="period-stat-card"><header><p>${title}</p><small class="period-rank">🏆 ${t('rank')} ${rank || '-'} / ${ranked.length}</small></header><div><strong>${selected.length}</strong><small>${t('matches')}</small></div><section><span><b>${wins}</b>${t('wins')}</span><span><b>${losses}</b>${t('losses')}</span><span><b>${rate}%</b>${t('rate')}</span><span><b>${sets > 0 ? '+' : ''}${sets}</b>${t('diff')}</span></section><aside class="record-bar"><i style="width:${selected.length ? wins / selected.length * 100 : 0}%"></i><b style="width:${selected.length ? losses / selected.length * 100 : 0}%"></b></aside></article>`;
}
function renderPeriodStats(completed, dates) {
  const months = [...new Set(dates.map(date => date.slice(0,7)))].reverse(), years = [...new Set(dates.map(date => date.slice(0,4)))].reverse(); statsMonthStart = Math.min(statsMonthStart, Math.max(0, months.length - 3)); document.querySelector('#player-month-prev').disabled = statsMonthStart >= months.length - 3; document.querySelector('#player-month-next').disabled = statsMonthStart === 0; document.querySelector('#monthly-period-stats').innerHTML = months.slice(statsMonthStart, statsMonthStart + 3).map(month => periodStatCard(month, completed.filter(match => match.matchDate.startsWith(month)))).join(''); const select = document.querySelector('#player-overall-select'); if (statsOverallPeriod !== 'all' && !years.includes(statsOverallPeriod)) statsOverallPeriod = 'all'; select.innerHTML = `<option value="all">${t('allTime')}</option>${years.map(year => `<option value="${year}">${year}</option>`).join('')}`; select.value = statsOverallPeriod; document.querySelector('#overall-period-stats').innerHTML = periodStatCard(statsOverallPeriod, statsOverallPeriod === 'all' ? completed : completed.filter(match => match.matchDate.startsWith(statsOverallPeriod)));
}
function openHeadToHead(matchId) {
  const match = matches.find(item => item.matchId === matchId), map = playerMap(), opponentId = match.player1Id === playerId ? match.player2Id : match.player1Id, opponent = map.get(opponentId) || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }, history = matches.filter(item => (item.player1Id === playerId && item.player2Id === opponentId) || (item.player2Id === playerId && item.player1Id === opponentId)).sort((left,right) => left.matchDate.localeCompare(right.matchDate)), decided = history.filter(isComplete), outcomes = decided.map(item => item.winnerId === playerId ? 1 : -1), cumulative = outcomes.reduce((values,value) => [...values, (values.at(-1) || 0) + value], []), wins = outcomes.filter(value => value > 0).length;
  const playerLink = item => `<a class="player-link" href="player.html?id=${item.playerId}">${nameFor(item)}</a>`; document.querySelector('#head-to-head-content').innerHTML = `<p class="eyebrow">${t('h2h')}</p><h2>${playerLink(player)} <em>${wins} - ${outcomes.filter(value => value < 0).length}</em> ${playerLink(opponent)}</h2><div class="h2h-chart"><canvas id="h2h-chart"></canvas></div><div class="h2h-history">${[...history].reverse().map(item => { const score = item.player1Id === playerId ? `${item.player1Sets}-${item.player2Sets}` : `${item.player2Sets}-${item.player1Sets}`, result = !isComplete(item) ? 'incomplete' : item.winnerId === playerId ? 'win' : 'loss'; return `<div class="h2h-result-${result}"><span>${item.matchDate}</span><strong>${playerLink(player)} <em>${score}</em> ${playerLink(opponent)}${result === 'incomplete' ? ` · ${t('incomplete')}` : ''}</strong></div>`; }).join('')}</div>`;
  profileCharts.push(new Chart(document.querySelector('#h2h-chart'), { type:'bar', data:{ labels:decided.map(item => item.matchDate), datasets:[{label:t('net'),data:outcomes,backgroundColor:outcomes.map(value => value > 0 ? '#d6a516' : '#8c423a'),borderRadius:3},{type:'line',label:t('cumulativeNet'),data:cumulative,borderColor:'#54b8d1',pointBackgroundColor:'#54b8d1',pointRadius:4,tension:.25,order:10,showSignedLabels:true}]}, options:{plugins:{legend:{labels:{color:'#f6f0e2'}}},scales:{x:{ticks:{color:'#a5a198'},grid:{display:false}},y:{ticks:{color:'#a5a198',stepSize:1},grid:{color:'rgba(246,240,226,.1)'}}}} }));
  document.querySelector('#head-to-head').showModal();
}
function render() {
  profileCharts.forEach(chart => chart.destroy()); profileCharts = [];
  const completed = matches.filter(isComplete), won = completed.filter(match => match.winnerId === playerId).length, lost = completed.filter(match => match.winnerId && match.winnerId !== playerId).length, dates = [...new Set(completed.map(match => match.matchDate))].sort();
  document.documentElement.lang = language; document.querySelector('#language-toggle').textContent = language === 'en' ? '日本語' : 'ENGLISH'; document.querySelector('.back-link').textContent = t('allPlayers');
  const latestMonth = dates.at(-1)?.slice(0,7), latestYear = dates.at(-1)?.slice(0,4), profileRecord = (label, period) => { const periodMatches = period ? completed.filter(match => match.matchDate.startsWith(period)) : completed, periodWins = periodMatches.filter(match => match.winnerId === playerId).length, periodLosses = periodMatches.filter(match => match.winnerId && match.winnerId !== playerId).length, rate = periodMatches.length ? Math.round(periodWins / periodMatches.length * 100) : 0; return `<strong><small>${label}</small><b>${rate}%</b><em>${periodWins}W-${periodLosses}L</em></strong>`; }; document.querySelector('#profile-hero').innerHTML = `<div><p class="eyebrow">${t('profile')}</p><span class="player-id">${player.playerId}</span><h1>${nameFor(player)}</h1>${language === 'en' ? '' : `<p class="hero-ja">${player.displayName}</p>`}<p class="profile-details">${[player.schoolLevel, player.gender, player.playingHand, player.grip, player.playingStyle].filter(Boolean).join(' · ') || 'Little Kings Table Tennis Club'}</p></div><div class="profile-record">${profileRecord(t('allTime'))}${profileRecord(t('latestMonth'), latestMonth)}${profileRecord(t('latestYear'), latestYear)}</div>`;
  [['#performance-kicker','performance'],['#timeline-title','timeline'],['#timeline-chart-title','timelineChart'],['#career-title','career'],['#period-stats-kicker','periodStats'],['#monthly-stats-title','monthly'],['#overall-stats-kicker','periodStats'],['#overall-stats-title','periodStatsTitle'],['#opponent-kicker','insight'],['#opponent-title','matchup'],['#archive-kicker','archive'],['#archive-title','history']].forEach(([selector,key]) => document.querySelector(selector).textContent = t(key)); document.querySelector('#player-overall-label').textContent = language === 'en' ? 'Select period' : '期間を選択';
  const dateWins = dates.map(date => completed.filter(match => match.matchDate === date && match.winnerId === playerId).length), dateLosses = dates.map(date => completed.filter(match => match.matchDate === date && match.winnerId && match.winnerId !== playerId).length);
  const net = dateWins.map((value,index) => value-dateLosses[index]), cumulativeNet = net.reduce((values,value) => [...values, (values.at(-1) || 0) + value], []); profileCharts.push(new Chart(document.querySelector('#monthly-chart'), { type:'bar', data:{ labels:dates, datasets:[{label:t('wins'),data:dateWins,backgroundColor:'#d6a516'},{label:t('losses'),data:dateLosses.map(value => -value),backgroundColor:'#8c423a'},{type:'line',label:t('net'),data:net,borderColor:'#f6f0e2',segment:{borderColor:context => context.p0.parsed.y >= 0 && context.p1.parsed.y >= 0 ? '#d6a516' : context.p0.parsed.y <= 0 && context.p1.parsed.y <= 0 ? '#8c423a' : '#f6f0e2'},pointBackgroundColor:net.map(value => value > 0 ? '#d6a516' : value < 0 ? '#8c423a' : '#f6f0e2'),pointBorderColor:'#090a0b',pointBorderWidth:2,pointRadius:5,tension:.25,order:10},{type:'line',label:t('cumulativeNet'),data:cumulativeNet,borderColor:'#54b8d1',backgroundColor:'#54b8d1',pointBackgroundColor:'#54b8d1',pointBorderColor:'#090a0b',pointRadius:4,tension:.25,order:11,showSignedLabels:true}]}, options:{maintainAspectRatio:false,scales:{x:{ticks:{color:'#f6f0e2'},grid:{display:false}},y:{ticks:{color:'#a5a198'},grid:{color:'rgba(246,240,226,.1)'}}},plugins:{legend:{labels:{color:'#f6f0e2'}}}} }));
  profileCharts.push(new Chart(document.querySelector('#career-chart'), { type:'doughnut', data:{labels:[t('wins'),t('losses')],datasets:[{data:[won,lost],backgroundColor:['#d6a516','#5e5b55'],borderWidth:0}]},options:{plugins:{legend:{labels:{color:'#f6f0e2'}}},cutout:'68%'} }));
  renderPeriodStats(completed, dates);
  const months = [...new Set(dates.map(date => date.slice(0,7)))].reverse(), years = [...new Set(dates.map(date => date.slice(0,4)))].reverse(); monthlyIndex = Math.min(monthlyIndex, Math.max(0,months.length-1)); yearlyIndex = Math.min(yearlyIndex, Math.max(0,years.length-1)); const block = (label, period, type, index, count) => { const rows = opponentRows(period); return `<article><h3>${label}: ${period}<span class="opponent-nav"><button data-period="${type}" data-direction="1" ${index >= count - 1 ? 'disabled' : ''}>‹</button><button data-period="${type}" data-direction="-1" ${index === 0 ? 'disabled' : ''}>›</button></span></h3><div class="opponent-columns"><section><h4>${t('played')}</h4><ul>${opponentList(rows,'played')}</ul></section><section><h4>${t('beat')}</h4><ul>${opponentList(rows,'won')}</ul></section><section><h4>${t('lost')}</h4><ul>${opponentList(rows,'lost')}</ul></section></div></article>`; }; document.querySelector('#opponent-stats').innerHTML = block(t('monthly'),months[monthlyIndex] || '', 'month', monthlyIndex, months.length) + block(t('yearly'),years[yearlyIndex] || '', 'year', yearlyIndex, years.length);
  const archiveDates = [...new Set(matches.map(match => match.matchDate))].sort(); document.querySelector('#profile-matches').innerHTML = [...archiveDates].reverse().map(date => { const day = matches.filter(match => match.matchDate === date), completeDay = day.filter(isComplete), dayWins = completeDay.filter(match => match.winnerId === playerId).length, dayLosses = completeDay.filter(match => match.winnerId && match.winnerId !== playerId).length, decided = dayWins + dayLosses; return `<section class="match-date-group"><header><strong>${date}</strong><span>${day.length} ${t('matches')} · ${dayWins}W-${dayLosses}L · ${decided ? Math.round(dayWins / decided * 100) : 0}%</span></header><div class="match-list">${day.map(match => { const opponent = playerMap().get(match.player1Id === playerId ? match.player2Id : match.player1Id) || { displayName: match.player1Id === playerId ? match.player2Name : match.player1Name }, score = match.player1Id === playerId ? `${match.player1Sets} - ${match.player2Sets}` : `${match.player2Sets} - ${match.player1Sets}`, result = !isComplete(match) ? 'incomplete' : match.winnerId === playerId ? 'win' : 'loss'; return `<button class="match-card player-session-card result-${result}" data-match-id="${match.matchId}"><div class="match-meta"><span>${match.matchDate}</span><span class="badge training">${t('training')}</span></div><div class="match-score"><span class="match-player ${result === 'win' ? 'winner' : ''}">${nameFor(player)}</span><strong class="score">${score}</strong><span class="match-player ${result === 'loss' ? 'winner' : ''}">${nameFor(opponent)}</span></div><div class="match-context"><span>${match.event || 'Little Kings Club Matches'}</span><b>${result === 'incomplete' ? t('incomplete') : opponent.schoolLevel || ''}</b></div></button>`; }).join('')}</div></section>`; }).join('');
}
fetch('./public-data.json').then(response => response.ok ? response.json() : Promise.reject()).catch(() => fetch(API_URL).then(response => response.json())).then(result => { data=result; player=data.players.find(item => item.playerId === playerId); if (!player) throw Error(); matches=data.matches.filter(match => (match.player1Id===playerId || match.player2Id===playerId) && eventType(match)==='Training').sort((a,b)=>b.matchDate.localeCompare(a.matchDate)); document.title=`${player.displayName} | Little Kings`; render(); const selectedMatch = requestedOpponentId && matches.find(match => match.player1Id === requestedOpponentId || match.player2Id === requestedOpponentId); if (selectedMatch) openHeadToHead(selectedMatch.matchId); }).catch(() => document.querySelector('#profile-hero').innerHTML='<div class="loading">Unable to load this player profile.</div>');
document.querySelector('#language-toggle').onclick=()=>{language=language==='en'?'ja':'en';localStorage.setItem('lk-language',language);render();}; document.querySelector('#player-month-prev').onclick=()=>{statsMonthStart++;render();}; document.querySelector('#player-month-next').onclick=()=>{statsMonthStart--;render();}; document.querySelector('#player-overall-select').onchange=event=>{statsOverallPeriod=event.target.value;render();}; document.addEventListener('click',event=>{const nav=event.target.closest('.opponent-nav button');if(nav){if(nav.dataset.period==='month')monthlyIndex+=Number(nav.dataset.direction);else yearlyIndex+=Number(nav.dataset.direction);render();return}const card=event.target.closest('.match-card');if(card?.dataset.matchId)openHeadToHead(card.dataset.matchId);if(event.target.closest('.modal-close'))document.querySelector('#head-to-head').close();});
